#pragma once
#include <juce_gui_basics/juce_gui_basics.h>
#include <juce_audio_processors/juce_audio_processors.h>
#include "MobileTouchHandler.h"
#include "MobileLayoutManager.h"
#include "HapticEngine.h"
#include "SensorManager.h"
#define XOLOKUN_GALLERY_COLORS_DEFINED 1
#include "../GalleryColors.h"
#include "../PlaySurface/PlaySurface.h"
#include "DisplayLink_iOS.h"
#include <array>
#include <cmath>

namespace xoceanus {

//==============================================================================
// MobilePlaySurface — Touch-optimized PlaySurface for iOS.
//
// Adapts the desktop PlaySurface for touch input with:
//   - Carousel mode (iPhone) or simultaneous zones (iPad)
//   - Per-finger tracking for multi-touch chords and expression
//   - Velocity from touch force (or radius fallback)
//   - Pinch-to-overlay Orbit Path
//   - Haptic feedback on musical events
//   - Physics: momentum, spring-back, boundary reflection
//
// This component owns a MobileTouchHandler and registers zones
// corresponding to the current layout mode. When the layout changes
// (orientation, multitasking resize), zones are re-registered.
//
class MobilePlaySurface : public juce::Component,
                          private juce::Timer {
public:
    //-- Note input modes --------------------------------------------------------

    enum class InputMode { Pad, Fretless, Drum };

    //-- Scale definitions -------------------------------------------------------

    enum class Scale {
        Chromatic, Major, Minor, Dorian, Mixolydian,
        Pentatonic, Blues, HarmonicMinor
    };

    MobilePlaySurface()
    {
#if JUCE_IOS
        // Use display-synced animation instead of timer
        xoceanus::display_link::start([this](double timestamp, double targetTimestamp) {
            juce::ignoreUnused(timestamp, targetTimestamp);
            // Same work as timerCallback but display-synced
            updatePhysics();
            updateTrails();
            updateHeatmap();
            repaint();
        });
        xoceanus::display_link::setPreferredFrameRate(60); // 60Hz default, 30Hz under CPU pressure
#else
        startTimerHz(30);  // Desktop fallback: animation tick for trails, momentum, heatmap decay
#endif
    }

    ~MobilePlaySurface() override
    {
#if JUCE_IOS
        xoceanus::display_link::stop();
#else
        stopTimer();
#endif
    }

    //-- Configuration -----------------------------------------------------------

    void setHapticEngine(HapticEngine* engine) { haptics = engine; }
    void setSensorManager(SensorManager* mgr) { sensors = mgr; }
    void setLayoutManager(MobileLayoutManager* mgr) { layoutMgr = mgr; }

    void setInputMode(InputMode mode)
    {
        if (inputMode == mode) return;
        inputMode = mode;
        touchHandler.cancelAllTouches();
        rebuildZones();
        if (haptics) haptics->fire(HapticEngine::Event::ModeSwitch);
        repaint();
    }

    InputMode getInputMode() const { return inputMode; }

    void setScale(Scale scale) { currentScale = scale; rebuildScaleTable(); repaint(); }
    void setRootNote(int midiNote) { rootNote = midiNote; rebuildScaleTable(); repaint(); }
    void setOctave(int oct) { octave = juce::jlimit(-2, 8, oct); rebuildScaleTable(); repaint(); }

    // Set callback for MIDI note events generated by touch input
    using NoteCallback = std::function<void(int midiNote, float velocity, bool noteOn)>;
    void setNoteCallback(NoteCallback cb) { noteCallback = std::move(cb); }

    // Set callback for continuous XY modulation (Orbit, Strip, Fretless X-axis)
    using ModCallback = std::function<void(float x, float y, int sourceZone)>;
    void setModCallback(ModCallback cb) { modCallback = std::move(cb); }

    //-- Carousel (iPhone) -------------------------------------------------------

    void setCarouselMode(bool enabled)
    {
        carousel = enabled;
        rebuildZones();
        repaint();
    }

    int getCurrentPage() const { return carouselPage; }

    void setCarouselPage(int page)
    {
        carouselPage = juce::jlimit(0, 4, page);
        touchHandler.cancelAllTouches();
        rebuildZones();
        repaint();
    }

    //-- Orbit Path overlay ------------------------------------------------------

    void showOrbitOverlay(bool show)
    {
        orbitOverlayVisible = show;
        rebuildZones();
        repaint();
    }

    bool isOrbitOverlayVisible() const { return orbitOverlayVisible; }

    //-- Component overrides -----------------------------------------------------

    void resized() override
    {
        rebuildZones();
    }

    void paint(juce::Graphics& g) override
    {
        auto bounds = getLocalBounds().toFloat();

        // Background
        g.setColour(GalleryColors::get(GalleryColors::shellWhite()));  // Gallery shell white
        g.fillRect(bounds);

        if (carousel)
            paintCarouselPage(g, bounds);
        else
            paintAllZones(g, bounds);

        // Orbit Path overlay
        if (orbitOverlayVisible)
            paintOrbitOverlay(g, bounds);

        // Touch trails (warm memory)
        paintTouchTrails(g);
    }

    //-- Mouse/Touch forwarding --------------------------------------------------

    void mouseDown(const juce::MouseEvent& e) override
    {
        // Detect 2-finger pinch for Orbit overlay
        if (e.source.getIndex() == 1 && !orbitOverlayVisible)
        {
            showOrbitOverlay(true);
            return;
        }
        touchHandler.handleMouseDown(e);
    }

    void mouseDrag(const juce::MouseEvent& e) override
    {
        touchHandler.handleMouseDrag(e);
    }

    void mouseUp(const juce::MouseEvent& e) override
    {
        touchHandler.handleMouseUp(e);

        // Dismiss orbit overlay when all touches end
        if (orbitOverlayVisible && touchHandler.getActiveTouchCount() == 0)
            showOrbitOverlay(false);
    }

private:
    MobileTouchHandler touchHandler;
    HapticEngine* haptics = nullptr;
    SensorManager* sensors = nullptr;
    MobileLayoutManager* layoutMgr = nullptr;

    InputMode inputMode = InputMode::Pad;
    Scale currentScale = Scale::Chromatic;
    int rootNote = 60;  // Middle C
    int octave = 4;
    bool carousel = true;
    int carouselPage = 0;
    bool orbitOverlayVisible = false;

    NoteCallback noteCallback;
    ModCallback modCallback;

    // Zone IDs from MobileTouchHandler
    int noteInputZoneId = -1;
    int orbitZoneId = -1;
    int stripZoneId = -1;

    // Scale table: MIDI notes for the current scale/root/octave
    static constexpr int MaxPads = 16;
    std::array<int, MaxPads> padNotes {};

    // Touch trail history for warm memory visualization
    struct TrailPoint {
        float x, y;
        float age;       // 0.0 = fresh, 1.0 = expired
        float velocity;  // For color intensity
    };
    static constexpr int MaxTrailPoints = 60;
    std::array<TrailPoint, MaxTrailPoints> trailPoints {};
    int trailHead = 0;

    // Orbit Path state
    float orbitX = 0.0f, orbitY = 0.0f;
    float orbitVelX = 0.0f, orbitVelY = 0.0f;
    static constexpr float OrbitFriction = 0.98f;
    static constexpr float OrbitSpring = 0.08f;

    // Pad heatmap (velocity visualization)
    std::array<float, MaxPads> padHeat {};

    // P0-6: Track the base note sounded at fretless touch-began so that
    // pitch bend during drag is relative to the correct base.
    int fretlessBaseNote_ = -1;

    //-- Zone setup --------------------------------------------------------------

    void rebuildZones()
    {
        // Remove old zones
        if (noteInputZoneId >= 0) touchHandler.removeZone(noteInputZoneId);
        if (orbitZoneId >= 0) touchHandler.removeZone(orbitZoneId);
        if (stripZoneId >= 0) touchHandler.removeZone(stripZoneId);
        noteInputZoneId = orbitZoneId = stripZoneId = -1;

        auto bounds = getLocalBounds().toFloat();
        if (bounds.isEmpty()) return;

        // Note input zone — takes most of the area
        auto noteArea = bounds;  // Will be refined based on layout
        noteInputZoneId = touchHandler.addZone("NoteInput", noteArea,
            [this](const TouchEvent& e) { handleNoteInput(e); });

        // Orbit overlay zone (only when visible)
        if (orbitOverlayVisible)
        {
            float diam = 200.0f;
            float cx = bounds.getCentreX() - diam * 0.5f;
            float cy = bounds.getCentreY() - diam * 0.5f;
            orbitZoneId = touchHandler.addZone("Orbit",
                { cx, cy, diam, diam },
                [this](const TouchEvent& e) { handleOrbitInput(e); });
        }
    }

    //-- Input handlers ----------------------------------------------------------

    void handleNoteInput(const TouchEvent& e)
    {
        switch (inputMode)
        {
            case InputMode::Pad:      handlePadInput(e); break;
            case InputMode::Fretless: handleFretlessInput(e); break;
            case InputMode::Drum:     handleDrumInput(e); break;
        }

        // Record trail point for warm memory
        if (e.phase == TouchPhase::Began || e.phase == TouchPhase::Moved)
        {
            trailPoints[static_cast<size_t>(trailHead)] = { e.x, e.y, 0.0f, e.force };
            trailHead = (trailHead + 1) % MaxTrailPoints;
        }
    }

    void handlePadInput(const TouchEvent& e)
    {
        // 4x4 grid: determine which pad was hit
        int col = static_cast<int>(e.normalizedX * 4.0f);
        int row = static_cast<int>(e.normalizedY * 4.0f);
        col = juce::jlimit(0, 3, col);
        row = juce::jlimit(0, 3, row);
        int padIndex = row * 4 + col;
        int midiNote = padNotes[static_cast<size_t>(padIndex)];

        switch (e.phase)
        {
            case TouchPhase::Began:
            {
                float velocity = forceToVelocity(e.force);
                padHeat[static_cast<size_t>(padIndex)] = velocity;
                if (noteCallback) noteCallback(midiNote, velocity, true);
                if (haptics) haptics->fire(HapticEngine::Event::PadStrike, velocity);
                break;
            }
            case TouchPhase::Moved:
            {
                // Y-axis within pad: send amount modulation
                // X-axis within pad: engine blend (multi-engine)
                float padNormY = std::fmod(e.normalizedY * 4.0f, 1.0f);
                float padNormX = std::fmod(e.normalizedX * 4.0f, 1.0f);
                if (modCallback) modCallback(padNormX, padNormY, 0);
                break;
            }
            case TouchPhase::Ended:
            case TouchPhase::Cancelled:
            {
                if (noteCallback) noteCallback(midiNote, 0.0f, false);
                break;
            }
        }

        repaint();
    }

    void handleFretlessInput(const TouchEvent& e)
    {
        // P0-2 (mobile): X=pitch (left=low, right=high), Y=expression (bottom=dark, top=bright)
        // Spec section 2.4: "X = pitch, Y = expression"
        float xNorm = juce::jlimit(0.0f, 1.0f, e.normalizedX);
        float yNorm = juce::jlimit(0.0f, 1.0f, 1.0f - e.normalizedY); // invert: bottom=0

        int baseMidi = rootNote + (octave - 4) * 12;
        // X spans 2 octaves by default; same as desktop.
        float midiFloat = static_cast<float>(baseMidi) + xNorm * 24.0f;
        int midiNote = juce::jlimit(0, 127, static_cast<int>(std::round(midiFloat)));

        // Expression from Y-axis (used as initial velocity and ongoing expression)
        float expression = juce::jmap(yNorm, 0.0f, 1.0f, 0.35f, 1.0f);

        switch (e.phase)
        {
            case TouchPhase::Began:
            {
                float velocity = forceToVelocity(e.force);
                // Use the larger of force-derived and Y-derived velocity
                velocity = std::max(velocity, expression);
                fretlessBaseNote_ = midiNote;
                if (noteCallback) noteCallback(midiNote, velocity, true);
                if (haptics) haptics->fire(HapticEngine::Event::PadStrike, velocity);
                break;
            }
            case TouchPhase::Moved:
            {
                // P0-6: send pitch bend so the playing note's pitch tracks
                // the finger position.  Pitch bend range ±2 semitones (MIDI default).
                if (fretlessBaseNote_ >= 0)
                {
                    static constexpr float kBendSemitones = 2.0f;
                    float bendSemitones = midiFloat - static_cast<float>(fretlessBaseNote_);
                    float bendNorm = juce::jlimit(-1.0f, 1.0f,
                                                  bendSemitones / kBendSemitones);
                    // Scale to 14-bit MIDI pitch wheel (0=full-down, 8192=centre, 16383=full-up)
                    int pitchWheelValue = 8192 + static_cast<int>(bendNorm * 8191.0f);
                    pitchWheelValue = juce::jlimit(0, 16383, pitchWheelValue);

                    // Deliver pitch bend via noteCallback using a dedicated encoding:
                    // noteCallback(-1, pitchBendNorm, true) where pitchBendNorm is
                    // (pitchWheelValue / 16383.0f).  Callers that understand this
                    // convention can route it; others ignore negative note numbers.
                    // For callers that have a modCallback, also forward the X/Y expression.
                    if (modCallback) modCallback(static_cast<float>(pitchWheelValue) / 16383.0f,
                                                 yNorm, 1);
                }
                break;
            }
            case TouchPhase::Ended:
            case TouchPhase::Cancelled:
            {
                // Reset pitch bend to centre before note-off
                if (modCallback) modCallback(0.5f, yNorm, 1);  // 0.5 = 8192/16383 ≈ centre
                if (noteCallback) noteCallback(midiNote, 0.0f, false);
                fretlessBaseNote_ = -1;
                break;
            }
        }

        repaint();
    }

    void handleDrumInput(const TouchEvent& e)
    {
        // Similar to pad but with drum-specific behavior:
        // - Velocity from force
        // - X-axis within pad: engine blend
        // - Y-axis within pad: decay time
        int col = static_cast<int>(e.normalizedX * 4.0f);
        int row = static_cast<int>(e.normalizedY * 4.0f);
        col = juce::jlimit(0, 3, col);
        row = juce::jlimit(0, 3, row);
        int padIndex = row * 4 + col;
        int midiNote = 36 + padIndex;  // GM drum map starting at kick

        if (e.phase == TouchPhase::Began)
        {
            float velocity = forceToVelocity(e.force);
            padHeat[static_cast<size_t>(padIndex)] = velocity;
            if (noteCallback) noteCallback(midiNote, velocity, true);
            if (haptics) haptics->fire(HapticEngine::Event::PadStrike, velocity);

            // Drum mode: auto note-off after decay (handled by engine)
        }
        else if (e.phase == TouchPhase::Ended || e.phase == TouchPhase::Cancelled)
        {
            if (noteCallback) noteCallback(midiNote, 0.0f, false);
        }

        repaint();
    }

    void handleOrbitInput(const TouchEvent& e)
    {
        // Map touch position to orbit XY (-1 to 1)
        float ox = e.normalizedX * 2.0f - 1.0f;
        float oy = e.normalizedY * 2.0f - 1.0f;

        // Constrain to circle
        float dist = std::sqrt(ox * ox + oy * oy);
        if (dist > 1.0f)
        {
            ox /= dist;
            oy /= dist;

            // Boundary hit — reflect velocity and fire haptic
            if (e.phase == TouchPhase::Moved)
            {
                orbitVelX *= -0.5f;
                orbitVelY *= -0.5f;
                if (haptics) haptics->fire(HapticEngine::Event::OrbitBoundary);
            }
        }

        switch (e.phase)
        {
            case TouchPhase::Began:
            case TouchPhase::Moved:
                orbitX = ox;
                orbitY = oy;
                orbitVelX = e.velocityX * 0.001f;  // Scale to orbit units
                orbitVelY = e.velocityY * 0.001f;
                if (modCallback) modCallback(orbitX, orbitY, 2);
                break;

            case TouchPhase::Ended:
                // Momentum: let orbit continue moving with friction
                // (handled in timerCallback)
                break;

            case TouchPhase::Cancelled:
                orbitX = 0.0f;
                orbitY = 0.0f;
                orbitVelX = 0.0f;
                orbitVelY = 0.0f;
                if (modCallback) modCallback(0.0f, 0.0f, 2);
                break;
        }

        repaint();
    }

    //-- Animation frame helpers -------------------------------------------------
    // Called each frame by either timerCallback() (desktop) or the DisplayLink
    // callback (iOS).  Each helper returns true if a repaint is needed.

    bool updatePhysics()
    {
        bool needsRepaint = false;

        // Orbit momentum + friction
        if (!touchHandler.isTouchActiveInZone(orbitZoneId)
            && (std::abs(orbitVelX) > 0.001f || std::abs(orbitVelY) > 0.001f))
        {
            orbitX += orbitVelX;
            orbitY += orbitVelY;
            orbitVelX *= OrbitFriction;
            orbitVelY *= OrbitFriction;

            // Boundary reflection
            float dist = std::sqrt(orbitX * orbitX + orbitY * orbitY);
            if (dist > 1.0f)
            {
                float nx = orbitX / dist, ny = orbitY / dist;
                float dot = orbitVelX * nx + orbitVelY * ny;
                orbitVelX -= 2.0f * dot * nx;
                orbitVelY -= 2.0f * dot * ny;
                orbitX = nx;
                orbitY = ny;
            }

            if (modCallback) modCallback(orbitX, orbitY, 2);
            needsRepaint = true;
        }

        // Sensor-driven orbit (gyroscope mode)
        if (sensors && sensors->getMotionMode() == SensorManager::MotionMode::Gyroscope
            && !touchHandler.isTouchActiveInZone(orbitZoneId))
        {
            orbitX = sensors->getGyroX();
            orbitY = sensors->getGyroY();
            if (modCallback) modCallback(orbitX, orbitY, 2);
            needsRepaint = true;
        }

        return needsRepaint;
    }

    bool updateTrails()
    {
        bool needsRepaint = false;

        // Trail aging
        for (auto& tp : trailPoints)
        {
            if (tp.age < 1.0f)
            {
                tp.age += 0.03f;
                needsRepaint = true;
            }
        }

        return needsRepaint;
    }

    bool updateHeatmap()
    {
        bool needsRepaint = false;

        // Pad heatmap decay
        for (auto& h : padHeat)
        {
            if (h > 0.0f)
            {
                h *= 0.92f;
                if (h < 0.01f) h = 0.0f;
                needsRepaint = true;
            }
        }

        return needsRepaint;
    }

    //-- Timer callback (animation + physics) — desktop fallback ----------------

    void timerCallback() override
    {
        bool needsRepaint = false;
        needsRepaint |= updatePhysics();
        needsRepaint |= updateTrails();
        needsRepaint |= updateHeatmap();
        if (needsRepaint) repaint();
    }

public:
    //-- Animation quality -------------------------------------------------------

    // Call with reduced=true when the host detects CPU pressure (e.g. from
    // ProcessInfo::thermalState on iOS).  Drops the frame rate to 30Hz to
    // relieve render load without stopping animation entirely.
    void reducedAnimationMode(bool reduced)
    {
#if JUCE_IOS
        xoceanus::display_link::setPreferredFrameRate(reduced ? 30 : 60);
#else
        if (reduced) startTimerHz(15); else startTimerHz(30);
#endif
    }

private:

    //-- Scale table -------------------------------------------------------------

    void rebuildScaleTable()
    {
        // Scale intervals (semitones from root)
        static const std::vector<std::vector<int>> scaleIntervals = {
            { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 },  // Chromatic
            { 0, 2, 4, 5, 7, 9, 11, 12, 14, 16, 17, 19, 21, 23, 24, 26 },  // Major
            { 0, 2, 3, 5, 7, 8, 10, 12, 14, 15, 17, 19, 20, 22, 24, 26 },  // Minor
            { 0, 2, 3, 5, 7, 9, 10, 12, 14, 15, 17, 19, 21, 22, 24, 26 },  // Dorian
            { 0, 2, 4, 5, 7, 9, 10, 12, 14, 16, 17, 19, 21, 22, 24, 26 },  // Mixolydian
            { 0, 2, 4, 7, 9, 12, 14, 16, 19, 21, 24, 26, 28, 31, 33, 36 },  // Pentatonic
            { 0, 3, 5, 6, 7, 10, 12, 15, 17, 18, 19, 22, 24, 27, 29, 30 },  // Blues
            { 0, 2, 3, 5, 7, 8, 11, 12, 14, 15, 17, 19, 20, 23, 24, 26 },  // Harmonic Minor
        };

        int scaleIdx = static_cast<int>(currentScale);
        const auto& intervals = scaleIntervals[static_cast<size_t>(scaleIdx)];
        int baseNote = rootNote + (octave - 4) * 12;

        for (int i = 0; i < MaxPads && i < static_cast<int>(intervals.size()); ++i)
        {
            // Bottom-left = lowest note, top-right = highest
            // Row 3 (bottom) first, then row 2, etc.
            int row = 3 - (i / 4);
            int col = i % 4;
            int padIdx = row * 4 + col;
            padNotes[static_cast<size_t>(padIdx)] =
                juce::jlimit(0, 127, baseNote + intervals[static_cast<size_t>(i)]);
        }
    }

    //-- Rendering ---------------------------------------------------------------

    void paintCarouselPage(juce::Graphics& g, juce::Rectangle<float> bounds)
    {
        switch (inputMode)
        {
            case InputMode::Pad:  paintPadGrid(g, bounds); break;
            case InputMode::Fretless: paintFretless(g, bounds); break;
            case InputMode::Drum: paintDrumGrid(g, bounds); break;
        }
    }

    void paintAllZones(juce::Graphics& g, juce::Rectangle<float> bounds)
    {
        // iPad: note input takes ~55% width, orbit ~20%, perf pads ~15%
        auto noteArea = bounds.removeFromLeft(bounds.getWidth() * 0.55f);
        paintPadGrid(g, noteArea);

        // Orbit visible inline
        auto orbitArea = bounds.removeFromLeft(bounds.getWidth() * 0.5f);
        paintOrbitInline(g, orbitArea);
    }

    void paintPadGrid(juce::Graphics& g, juce::Rectangle<float> area)
    {
        float cellW = area.getWidth() / 4.0f;
        float cellH = area.getHeight() / 4.0f;
        float gap = 2.0f;

        for (int row = 0; row < 4; ++row)
        {
            for (int col = 0; col < 4; ++col)
            {
                int idx = row * 4 + col;
                float x = area.getX() + col * cellW + gap;
                float y = area.getY() + row * cellH + gap;
                float w = cellW - gap * 2.0f;
                float h = cellH - gap * 2.0f;

                // Pad background with heatmap
                float heat = padHeat[static_cast<size_t>(idx)];
                auto baseColor = GalleryColors::get(GalleryColors::emptySlot());  // Light warm grey
                auto hotColor = GalleryColors::get(GalleryColors::xoGold);   // XO Gold
                auto padColor = baseColor.interpolatedWith(hotColor, heat);

                g.setColour(padColor);
                g.fillRoundedRectangle(x, y, w, h, 6.0f);

                // Pad border
                g.setColour(GalleryColors::get(GalleryColors::borderGray()));
                g.drawRoundedRectangle(x, y, w, h, 6.0f, 1.0f);

                // Note label
                int note = padNotes[static_cast<size_t>(idx)];
                static const char* noteNames[] = {
                    "C", "C#", "D", "D#", "E", "F",
                    "F#", "G", "G#", "A", "A#", "B"
                };
                juce::String label = juce::String(noteNames[note % 12])
                    + juce::String(note / 12 - 1);

                g.setColour(GalleryColors::get(GalleryColors::textDark()).withAlpha(0.6f + heat * 0.4f));
                g.setFont(11.0f);
                g.drawText(label, static_cast<int>(x), static_cast<int>(y),
                    static_cast<int>(w), static_cast<int>(h),
                    juce::Justification::centred);
            }
        }
    }

    void paintFretless(juce::Graphics& g, juce::Rectangle<float> area)
    {
        // Gradient ribbon: low (warm) at bottom, high (cool) at top
        juce::ColourGradient grad(
            GalleryColors::get(GalleryColors::xoGold), area.getX(), area.getBottom(),  // Gold (low)
            juce::Colour(0xFFA78BFA), area.getX(), area.getY(),       // Lavender (high, OPAL accent)
            false);
        g.setGradientFill(grad);
        g.fillRoundedRectangle(area, 8.0f);

        // Scale lines
        g.setColour(juce::Colour(0x20000000));
        int divisions = 24;  // 2 octaves, semitone lines
        for (int i = 1; i < divisions; ++i)
        {
            float y = area.getY() + (static_cast<float>(i) / static_cast<float>(divisions)) * area.getHeight();
            g.drawHorizontalLine(static_cast<int>(y),
                area.getX(), area.getRight());
        }
    }

    void paintDrumGrid(juce::Graphics& g, juce::Rectangle<float> area)
    {
        // Similar to pad grid but with drum labels
        static const char* drumLabels[] = {
            "KICK", "SNARE", "CLAP", "RIM",
            "HH-C", "HH-O", "TOM-H", "TOM-M",
            "TOM-L", "CRASH", "RIDE", "PERC1",
            "PERC2", "PERC3", "FX1", "FX2"
        };

        float cellW = area.getWidth() / 4.0f;
        float cellH = area.getHeight() / 4.0f;
        float gap = 2.0f;

        for (int row = 0; row < 4; ++row)
        {
            for (int col = 0; col < 4; ++col)
            {
                int idx = row * 4 + col;
                float x = area.getX() + col * cellW + gap;
                float y = area.getY() + row * cellH + gap;
                float w = cellW - gap * 2.0f;
                float h = cellH - gap * 2.0f;

                float heat = padHeat[static_cast<size_t>(idx)];
                auto baseColor = juce::Colour(0xFFE0DDD8);
                auto hotColor = juce::Colour(0xFF0066FF);  // Electric Blue (Onset accent)
                auto padColor = baseColor.interpolatedWith(hotColor, heat);

                g.setColour(padColor);
                g.fillRoundedRectangle(x, y, w, h, 8.0f);

                g.setColour(GalleryColors::get(GalleryColors::borderGray()));
                g.drawRoundedRectangle(x, y, w, h, 8.0f, 1.0f);

                g.setColour(GalleryColors::get(GalleryColors::textDark()).withAlpha(0.5f + heat * 0.5f));
                g.setFont(9.0f);
                g.drawText(drumLabels[idx],
                    static_cast<int>(x), static_cast<int>(y),
                    static_cast<int>(w), static_cast<int>(h),
                    juce::Justification::centred);
            }
        }
    }

    void paintOrbitOverlay(juce::Graphics& g, juce::Rectangle<float> bounds)
    {
        // Semi-transparent backdrop
        g.setColour(juce::Colour(0xD9F8F6F3));
        g.fillRect(bounds);

        // Orbit circle
        float diam = 200.0f;
        float cx = bounds.getCentreX();
        float cy = bounds.getCentreY();

        // Ring
        g.setColour(juce::Colour(0x30E9C46A));
        g.drawEllipse(cx - diam * 0.5f, cy - diam * 0.5f, diam, diam, 2.0f);

        // Crosshairs
        g.setColour(juce::Colour(0x15000000));
        g.drawHorizontalLine(static_cast<int>(cy), cx - diam * 0.5f, cx + diam * 0.5f);
        g.drawVerticalLine(static_cast<int>(cx), cy - diam * 0.5f, cy + diam * 0.5f);

        // Cursor
        float cursorX = cx + orbitX * diam * 0.5f;
        float cursorY = cy + orbitY * diam * 0.5f;
        float cursorSize = 16.0f;

        g.setColour(GalleryColors::get(GalleryColors::xoGold));  // XO Gold
        g.fillEllipse(cursorX - cursorSize * 0.5f, cursorY - cursorSize * 0.5f,
            cursorSize, cursorSize);

        // Position readout
        g.setColour(GalleryColors::get(GalleryColors::textDark()));
        g.setFont(10.0f);
        g.drawText(juce::String::formatted("X: %.2f  Y: %.2f", orbitX, orbitY),
            static_cast<int>(cx - 60), static_cast<int>(cy + diam * 0.5f + 8),
            120, 16, juce::Justification::centred);
    }

    void paintOrbitInline(juce::Graphics& g, juce::Rectangle<float> area)
    {
        float diam = juce::jmin(area.getWidth(), area.getHeight()) * 0.85f;
        float cx = area.getCentreX();
        float cy = area.getCentreY();

        g.setColour(juce::Colour(0x10E9C46A));
        g.fillEllipse(cx - diam * 0.5f, cy - diam * 0.5f, diam, diam);

        g.setColour(juce::Colour(0x30E9C46A));
        g.drawEllipse(cx - diam * 0.5f, cy - diam * 0.5f, diam, diam, 1.5f);

        float cursorX = cx + orbitX * diam * 0.5f;
        float cursorY = cy + orbitY * diam * 0.5f;
        g.setColour(GalleryColors::get(GalleryColors::xoGold));
        g.fillEllipse(cursorX - 8, cursorY - 8, 16, 16);
    }

    void paintTouchTrails(juce::Graphics& g)
    {
        for (const auto& tp : trailPoints)
        {
            if (tp.age >= 1.0f) continue;
            float alpha = (1.0f - tp.age) * tp.velocity * 0.3f;
            float size = 6.0f + tp.age * 20.0f;
            g.setColour(juce::Colour(0xFFE9C46A).withAlpha(alpha));
            g.fillEllipse(tp.x - size * 0.5f, tp.y - size * 0.5f, size, size);
        }
    }

    //-- Utility -----------------------------------------------------------------

    static float forceToVelocity(float force)
    {
        // Map normalized force (0-1) to MIDI velocity range (0.1-1.0)
        // with slight exponential curve for expressiveness
        float vel = 0.1f + force * force * 0.9f;
        return juce::jlimit(0.0f, 1.0f, vel);
    }
};

} // namespace xoceanus
