#!/usr/bin/env bash
# ObrixReef — One-shot Android build setup (no Android Studio)
#
# What this does:
#   1. Downloads Android SDK command-line tools (~150MB)
#   2. Accepts licenses automatically
#   3. Installs: platform-tools, platform 36, build-tools, NDK r27, CMake
#   4. Creates local.properties pointing to the SDK
#
# Prerequisites: JDK 17+ (check with: java -version)
#
# Usage:
#   cd android/obrixreef
#   chmod +x setup-android-sdk.sh
#   ./setup-android-sdk.sh
#   ./gradlew assembleDebug
#   ./gradlew installDebug  # with phone connected via USB
set -euo pipefail

SDK_ROOT="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Android/Sdk}}"

echo "=== ObrixReef Android SDK Setup ==="
echo "Target: $SDK_ROOT"
echo ""

# Detect OS
case "$(uname -s)" in
    Darwin*) PLATFORM="mac" ;;
    Linux*)  PLATFORM="linux" ;;
    MINGW*|MSYS*|CYGWIN*) PLATFORM="win" ;;
    *) echo "Unsupported OS: $(uname -s)"; exit 1 ;;
esac

# Download cmdline-tools if needed
SDKMANAGER="$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
if [ ! -f "$SDKMANAGER" ]; then
    echo "[1/4] Downloading command-line tools for $PLATFORM..."
    mkdir -p "$SDK_ROOT/cmdline-tools"
    ZIPURL="https://dl.google.com/android/repository/commandlinetools-${PLATFORM}-11076708_latest.zip"
    TMPZIP="$(mktemp)"
    curl -# -L -o "$TMPZIP" "$ZIPURL"
    unzip -q -o "$TMPZIP" -d "$SDK_ROOT/cmdline-tools"
    # The zip extracts to cmdline-tools/ — rename to latest/
    if [ -d "$SDK_ROOT/cmdline-tools/cmdline-tools" ]; then
        rm -rf "$SDK_ROOT/cmdline-tools/latest"
        mv "$SDK_ROOT/cmdline-tools/cmdline-tools" "$SDK_ROOT/cmdline-tools/latest"
    fi
    rm -f "$TMPZIP"
    echo "  Done."
else
    echo "[1/4] Command-line tools already installed."
fi

export ANDROID_HOME="$SDK_ROOT"
export ANDROID_SDK_ROOT="$SDK_ROOT"
export PATH="$SDK_ROOT/cmdline-tools/latest/bin:$SDK_ROOT/platform-tools:$PATH"

# Accept all licenses
echo "[2/4] Accepting licenses..."
yes 2>/dev/null | "$SDKMANAGER" --licenses > /dev/null 2>&1 || true

# Install required SDK components
echo "[3/4] Installing SDK components (this may take a few minutes)..."
"$SDKMANAGER" --install \
    "platform-tools" \
    "platforms;android-36" \
    "build-tools;36.0.0" \
    "ndk;27.0.12077973" \
    "cmake;3.22.1" 2>&1 | grep -E "^(Downloading|Installing|  )"

# Write local.properties
echo "[4/4] Writing local.properties..."
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cat > "$SCRIPT_DIR/local.properties" << PROPS
# Auto-generated by setup-android-sdk.sh
sdk.dir=$SDK_ROOT
PROPS

echo ""
echo "=== Setup complete ==="
echo ""
echo "Build:"
echo "  cd android/obrixreef"
echo "  ./gradlew assembleDebug"
echo ""
echo "Install to phone (USB debugging enabled):"
echo "  ./gradlew installDebug"
echo ""
echo "To enable USB debugging on Nothing Phone:"
echo "  Settings > About Phone > tap 'Build number' 7 times"
echo "  Settings > System > Developer options > USB debugging > ON"
echo ""
echo "Add to your shell (~/.zshrc or ~/.bashrc) for future sessions:"
echo "  export ANDROID_HOME=\"$SDK_ROOT\""
echo "  export PATH=\"\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$PATH\""
