#!/usr/bin/env python3
"""
generate_oven_presets.py
Generate 111 factory presets for the Oven engine (cast iron concert grand).
Target: bring Oven from 9 → 120 presets.

Mood distribution:
  Foundation  25  (concert grand)
  Deep        20  (cast iron mass, low register)
  Ethereal    18  (sympathetic drones)
  Submerged   12  (slow bloom)
  Luminous    12  (bright modal attacks)
  Kinetic     10  (forte attack, short bloom)
  Organic      8  (wooden body resonance)
  Crystalline  6  (metallic, prepared)

18+ high-aggression presets (dna.aggression >= 0.7).
"""

import json
import os
import sys

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..")
PRESETS_DIR = os.path.join(REPO_ROOT, "Presets", "XOceanus")


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def oven_params(
    brightness=3000.0,
    body_resonance=0.6,
    hf_amount=0.5,
    hardness=0.4,
    density=0.7,
    temperature=0.5,
    sympathetic=0.4,
    bloom_time=0.0,
    sustain_time=4.0,
    filter_env_amt=0.4,
    amp_attack=0.001,
    amp_decay=2.0,
    amp_sustain=0.3,
    amp_release=1.5,
    bend_range=2.0,
    macro_character=0.0,
    macro_movement=0.0,
    macro_coupling=0.0,
    macro_space=0.0,
    lfo1_rate=0.3,
    lfo1_depth=0.05,
    lfo1_shape=0,
    lfo2_rate=0.8,
    lfo2_depth=0.0,
    lfo2_shape=0,
    competition=0.0,
    coupling_resonance=0.0,
):
    return {
        "Oven": {
            "oven_brightness": clamp(brightness, 200.0, 16000.0),
            "oven_bodyResonance": clamp(body_resonance, 0.0, 1.0),
            "oven_hfAmount": clamp(hf_amount, 0.0, 1.0),
            "oven_hardness": clamp(hardness, 0.0, 1.0),
            "oven_density": clamp(density, 0.0, 1.0),
            "oven_temperature": clamp(temperature, 0.0, 1.0),
            "oven_sympathetic": clamp(sympathetic, 0.0, 1.0),
            "oven_bloomTime": clamp(bloom_time, 0.0, 1.0),
            "oven_sustainTime": clamp(sustain_time, 0.5, 15.0),
            "oven_filterEnvAmt": clamp(filter_env_amt, 0.0, 1.0),
            "oven_ampAttack": clamp(amp_attack, 0.001, 2.0),
            "oven_ampDecay": clamp(amp_decay, 0.05, 10.0),
            "oven_ampSustain": clamp(amp_sustain, 0.0, 1.0),
            "oven_ampRelease": clamp(amp_release, 0.05, 10.0),
            "oven_bendRange": clamp(bend_range, 1.0, 24.0),
            "oven_macroCharacter": clamp(macro_character, 0.0, 1.0),
            "oven_macroMovement": clamp(macro_movement, 0.0, 1.0),
            "oven_macroCoupling": clamp(macro_coupling, 0.0, 1.0),
            "oven_macroSpace": clamp(macro_space, 0.0, 1.0),
            "oven_lfo1Rate": clamp(lfo1_rate, 0.005, 20.0),
            "oven_lfo1Depth": clamp(lfo1_depth, 0.0, 1.0),
            "oven_lfo1Shape": int(clamp(lfo1_shape, 0, 4)),
            "oven_lfo2Rate": clamp(lfo2_rate, 0.005, 20.0),
            "oven_lfo2Depth": clamp(lfo2_depth, 0.0, 1.0),
            "oven_lfo2Shape": int(clamp(lfo2_shape, 0, 4)),
            "oven_competition": clamp(competition, 0.0, 1.0),
            "oven_couplingResonance": clamp(coupling_resonance, 0.0, 1.0),
        }
    }


def make_preset(name, mood, description, tags, dna, params):
    return {
        "schema_version": 1,
        "name": name,
        "mood": mood,
        "engines": ["Oven"],
        "author": "XO_OX Designs",
        "version": "1.0.0",
        "description": description,
        "tags": tags,
        "macroLabels": ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        "couplingIntensity": "None",
        "tempo": None,
        "dna": dna,
        "parameters": params,
        "coupling": {"pairs": []},
        "sequencer": None,
    }


def write_preset(preset):
    mood = preset["mood"]
    name = preset["name"]
    safe_name = name.replace(" ", "_").replace("/", "-")
    dest_dir = os.path.join(PRESETS_DIR, mood, "Oven")
    os.makedirs(dest_dir, exist_ok=True)
    path = os.path.join(dest_dir, f"Oven_{safe_name}.xometa")
    with open(path, "w") as f:
        json.dump(preset, f, indent=2)
    return path


# ---------------------------------------------------------------------------
# PRESETS
# ---------------------------------------------------------------------------

PRESETS = []

# ===========================  FOUNDATION (25)  =============================

PRESETS += [
    make_preset(
        "Iron Cathedral",
        "Foundation",
        "Full concert grand at room temperature. Deep modal resonators ring true, sympathetic strings shimmer behind every note. The cast iron frame gives the tone a slight metallic warmth absent from spruce-board instruments.",
        ["piano", "concert grand", "classical", "iron", "resonant"],
        {"brightness": 0.55, "warmth": 0.7, "movement": 0.15, "density": 0.75, "space": 0.5, "aggression": 0.3},
        oven_params(brightness=4500.0, body_resonance=0.65, hf_amount=0.55, hardness=0.45, density=0.75, temperature=0.5,
                    sympathetic=0.5, bloom_time=0.0, sustain_time=5.0, filter_env_amt=0.4,
                    amp_attack=0.001, amp_decay=3.0, amp_sustain=0.35, amp_release=2.0,
                    lfo1_rate=0.2, lfo1_depth=0.04),
    ),
    make_preset(
        "Grand Standard",
        "Foundation",
        "The default concert hall voice. Balanced brightness, medium sustain, just enough body resonance to feel physical without masking. Works in any musical context.",
        ["piano", "concert grand", "neutral", "versatile"],
        {"brightness": 0.5, "warmth": 0.65, "movement": 0.1, "density": 0.7, "space": 0.45, "aggression": 0.25},
        oven_params(brightness=3500.0, body_resonance=0.6, hf_amount=0.5, hardness=0.4, density=0.7, temperature=0.5,
                    sympathetic=0.4, bloom_time=0.0, sustain_time=4.5, filter_env_amt=0.35,
                    amp_attack=0.001, amp_decay=2.5, amp_sustain=0.3, amp_release=1.8),
    ),
    make_preset(
        "Parlour Iron",
        "Foundation",
        "Smaller room, closer mic placement. More body, less air. The cast iron resonators feel intimate rather than cavernous.",
        ["piano", "parlour", "intimate", "warm"],
        {"brightness": 0.4, "warmth": 0.75, "movement": 0.12, "density": 0.8, "space": 0.3, "aggression": 0.2},
        oven_params(brightness=2800.0, body_resonance=0.75, hf_amount=0.4, hardness=0.35, density=0.8, temperature=0.45,
                    sympathetic=0.35, bloom_time=0.0, sustain_time=3.5, filter_env_amt=0.3,
                    amp_attack=0.001, amp_decay=2.2, amp_sustain=0.35, amp_release=1.5),
    ),
    make_preset(
        "Recital Hall",
        "Foundation",
        "Mid-sized hall with natural reverb tail. Sympathetic resonance is more present; feels like sitting in the fifth row, not at the lid.",
        ["piano", "hall", "space", "classical"],
        {"brightness": 0.52, "warmth": 0.6, "movement": 0.18, "density": 0.65, "space": 0.65, "aggression": 0.2},
        oven_params(brightness=4000.0, body_resonance=0.55, hf_amount=0.5, hardness=0.42, density=0.65, temperature=0.52,
                    sympathetic=0.55, bloom_time=0.05, sustain_time=5.5, filter_env_amt=0.38,
                    amp_attack=0.001, amp_decay=3.2, amp_sustain=0.3, amp_release=2.5,
                    macro_space=0.35),
    ),
    make_preset(
        "Forte Strike",
        "Foundation",
        "Hard hammer, immediate attack. The pianist is playing forte. High hardness reveals the inharmonic click of the cast iron frame on the transient.",
        ["piano", "forte", "attack", "dynamic"],
        {"brightness": 0.65, "warmth": 0.55, "movement": 0.1, "density": 0.7, "space": 0.4, "aggression": 0.7},
        oven_params(brightness=6000.0, body_resonance=0.55, hf_amount=0.65, hardness=0.8, density=0.7, temperature=0.55,
                    sympathetic=0.3, bloom_time=0.0, sustain_time=3.5, filter_env_amt=0.55,
                    amp_attack=0.001, amp_decay=2.0, amp_sustain=0.25, amp_release=1.5),
    ),
    make_preset(
        "Pianissimo",
        "Foundation",
        "Soft pedal pressed. Low hardness, slow attack onset, long sustain. The modal resonators hum quietly behind sparse notes.",
        ["piano", "soft", "gentle", "pianissimo"],
        {"brightness": 0.35, "warmth": 0.7, "movement": 0.1, "density": 0.6, "space": 0.5, "aggression": 0.05},
        oven_params(brightness=2200.0, body_resonance=0.7, hf_amount=0.25, hardness=0.15, density=0.6, temperature=0.4,
                    sympathetic=0.45, bloom_time=0.0, sustain_time=6.0, filter_env_amt=0.2,
                    amp_attack=0.005, amp_decay=3.5, amp_sustain=0.4, amp_release=3.0),
    ),
    make_preset(
        "Sostenuto",
        "Foundation",
        "Selected notes ring on while others damp. Modeled by long sustain time and high sympathetic. Works beautifully with sparse voicings.",
        ["piano", "sustain", "resonant", "pedal"],
        {"brightness": 0.5, "warmth": 0.68, "movement": 0.12, "density": 0.7, "space": 0.55, "aggression": 0.15},
        oven_params(brightness=3800.0, body_resonance=0.7, hf_amount=0.45, hardness=0.38, density=0.7, temperature=0.5,
                    sympathetic=0.65, bloom_time=0.05, sustain_time=7.0, filter_env_amt=0.35,
                    amp_attack=0.001, amp_decay=4.0, amp_sustain=0.4, amp_release=3.5),
    ),
    make_preset(
        "Steinway Morning",
        "Foundation",
        "Early morning light through the practice room. Warm, slightly diffuse, unhurried. Temperature is cool, density medium.",
        ["piano", "morning", "warm", "practice"],
        {"brightness": 0.45, "warmth": 0.72, "movement": 0.12, "density": 0.65, "space": 0.5, "aggression": 0.12},
        oven_params(brightness=3200.0, body_resonance=0.65, hf_amount=0.42, hardness=0.32, density=0.65, temperature=0.38,
                    sympathetic=0.42, bloom_time=0.0, sustain_time=4.0, filter_env_amt=0.32,
                    amp_attack=0.002, amp_decay=2.8, amp_sustain=0.35, amp_release=2.0),
    ),
    make_preset(
        "Nocturne Cast",
        "Foundation",
        "Night session. Temperature slightly elevated, sympathetic resonance wide. For slow chord progressions with the sustain pedal held.",
        ["piano", "nocturne", "night", "sustain"],
        {"brightness": 0.42, "warmth": 0.75, "movement": 0.15, "density": 0.68, "space": 0.58, "aggression": 0.1},
        oven_params(brightness=2800.0, body_resonance=0.7, hf_amount=0.38, hardness=0.3, density=0.68, temperature=0.55,
                    sympathetic=0.55, bloom_time=0.08, sustain_time=5.5, filter_env_amt=0.3,
                    amp_attack=0.002, amp_decay=3.2, amp_sustain=0.38, amp_release=2.8),
    ),
    make_preset(
        "Upright Iron",
        "Foundation",
        "Upright piano character despite the grand frame. Body resonance up, brightness down, shorter sustain. Reminiscent of a pub piano that happens to be made of cast iron.",
        ["piano", "upright", "character", "bar"],
        {"brightness": 0.38, "warmth": 0.72, "movement": 0.15, "density": 0.78, "space": 0.3, "aggression": 0.3},
        oven_params(brightness=2500.0, body_resonance=0.8, hf_amount=0.55, hardness=0.5, density=0.78, temperature=0.48,
                    sympathetic=0.25, bloom_time=0.0, sustain_time=2.5, filter_env_amt=0.42,
                    amp_attack=0.001, amp_decay=1.8, amp_sustain=0.25, amp_release=1.2),
    ),
    make_preset(
        "Classical Study",
        "Foundation",
        "Dry, focused, for contrapuntal work. Minimal sympathetic, controlled sustain. Every voice is distinct.",
        ["piano", "classical", "dry", "contrapuntal"],
        {"brightness": 0.5, "warmth": 0.6, "movement": 0.08, "density": 0.65, "space": 0.25, "aggression": 0.2},
        oven_params(brightness=3800.0, body_resonance=0.5, hf_amount=0.45, hardness=0.42, density=0.65, temperature=0.45,
                    sympathetic=0.2, bloom_time=0.0, sustain_time=3.0, filter_env_amt=0.35,
                    amp_attack=0.001, amp_decay=2.0, amp_sustain=0.25, amp_release=1.2),
    ),
    make_preset(
        "Romantic Grand",
        "Foundation",
        "Full Romantic era expression. High density, elevated sympathetic resonance, long release. Schumann and Brahms territory.",
        ["piano", "romantic", "expressive", "classical"],
        {"brightness": 0.48, "warmth": 0.72, "movement": 0.2, "density": 0.82, "space": 0.55, "aggression": 0.3},
        oven_params(brightness=3500.0, body_resonance=0.75, hf_amount=0.5, hardness=0.45, density=0.82, temperature=0.52,
                    sympathetic=0.6, bloom_time=0.1, sustain_time=6.0, filter_env_amt=0.4,
                    amp_attack=0.001, amp_decay=3.5, amp_sustain=0.4, amp_release=3.0),
    ),
    make_preset(
        "Jazz Trio",
        "Foundation",
        "Classic jazz trio sound. Warm attack, medium decay, crisp but not harsh. The cast iron gives the midrange a pleasing density.",
        ["piano", "jazz", "trio", "warm"],
        {"brightness": 0.52, "warmth": 0.68, "movement": 0.12, "density": 0.72, "space": 0.4, "aggression": 0.35},
        oven_params(brightness=4200.0, body_resonance=0.62, hf_amount=0.5, hardness=0.5, density=0.72, temperature=0.5,
                    sympathetic=0.32, bloom_time=0.0, sustain_time=3.0, filter_env_amt=0.38,
                    amp_attack=0.001, amp_decay=2.2, amp_sustain=0.28, amp_release=1.4),
    ),
    make_preset(
        "Gospel Pound",
        "Foundation",
        "Gospel piano energy. High hardness, strong body resonance, punchy decay. The iron frame sings.",
        ["piano", "gospel", "church", "attack"],
        {"brightness": 0.6, "warmth": 0.65, "movement": 0.15, "density": 0.75, "space": 0.4, "aggression": 0.72},
        oven_params(brightness=5000.0, body_resonance=0.7, hf_amount=0.6, hardness=0.75, density=0.75, temperature=0.55,
                    sympathetic=0.35, bloom_time=0.0, sustain_time=2.8, filter_env_amt=0.5,
                    amp_attack=0.001, amp_decay=1.8, amp_sustain=0.3, amp_release=1.3),
    ),
    make_preset(
        "Honky Tonk",
        "Foundation",
        "Slightly detuned, high temperature, rattling body resonance. The cast iron frame vibrating at a slightly wrong temperature.",
        ["piano", "honky-tonk", "detuned", "bar"],
        {"brightness": 0.5, "warmth": 0.6, "movement": 0.55, "density": 0.7, "space": 0.3, "aggression": 0.45},
        oven_params(brightness=3800.0, body_resonance=0.78, hf_amount=0.6, hardness=0.55, density=0.7, temperature=0.88,
                    sympathetic=0.3, bloom_time=0.12, sustain_time=3.0, filter_env_amt=0.4,
                    amp_attack=0.001, amp_decay=2.0, amp_sustain=0.25, amp_release=1.5,
                    lfo1_rate=5.2, lfo1_depth=0.06, lfo1_shape=1),
    ),
    make_preset(
        "Campanology",
        "Foundation",
        "Bell-like piano with metallic sustain from the cast iron frame. High HF fill, elevated sympathetic resonance. Notes ring like gongs.",
        ["piano", "bell", "metallic", "ring"],
        {"brightness": 0.75, "warmth": 0.4, "movement": 0.2, "density": 0.55, "space": 0.65, "aggression": 0.45},
        oven_params(brightness=8000.0, body_resonance=0.45, hf_amount=0.75, hardness=0.65, density=0.55, temperature=0.6,
                    sympathetic=0.7, bloom_time=0.15, sustain_time=7.0, filter_env_amt=0.5,
                    amp_attack=0.001, amp_decay=4.5, amp_sustain=0.2, amp_release=4.0),
    ),
    make_preset(
        "Slow Ballad",
        "Foundation",
        "Singer-songwriter ballad tone. Long decay, soft attack, warm. Leave space for the vocal.",
        ["piano", "ballad", "soft", "pop"],
        {"brightness": 0.4, "warmth": 0.72, "movement": 0.1, "density": 0.62, "space": 0.48, "aggression": 0.1},
        oven_params(brightness=2800.0, body_resonance=0.65, hf_amount=0.38, hardness=0.28, density=0.62, temperature=0.42,
                    sympathetic=0.4, bloom_time=0.0, sustain_time=4.5, filter_env_amt=0.28,
                    amp_attack=0.003, amp_decay=3.0, amp_sustain=0.38, amp_release=2.5),
    ),
    make_preset(
        "Neo Soul Keys",
        "Foundation",
        "D'Angelo and Erykah Badu era. Slightly overdriven, high body resonance, warm top. The iron frame contributes a subtle saturation.",
        ["piano", "neo-soul", "warm", "r&b"],
        {"brightness": 0.48, "warmth": 0.78, "movement": 0.18, "density": 0.78, "space": 0.42, "aggression": 0.4},
        oven_params(brightness=3200.0, body_resonance=0.82, hf_amount=0.48, hardness=0.52, density=0.78, temperature=0.58,
                    sympathetic=0.38, bloom_time=0.05, sustain_time=3.5, filter_env_amt=0.42,
                    amp_attack=0.002, amp_decay=2.5, amp_sustain=0.32, amp_release=1.8),
    ),
    make_preset(
        "Bossa Grand",
        "Foundation",
        "Bossa nova voicing. Medium attack, short-ish decay. Clean, articulate, slightly bright.",
        ["piano", "bossa", "jazz", "clean"],
        {"brightness": 0.55, "warmth": 0.62, "movement": 0.12, "density": 0.62, "space": 0.45, "aggression": 0.25},
        oven_params(brightness=4500.0, body_resonance=0.55, hf_amount=0.5, hardness=0.45, density=0.62, temperature=0.48,
                    sympathetic=0.28, bloom_time=0.0, sustain_time=2.8, filter_env_amt=0.35,
                    amp_attack=0.001, amp_decay=1.8, amp_sustain=0.28, amp_release=1.3),
    ),
    make_preset(
        "Minimalist Touch",
        "Foundation",
        "Philip Glass territory. Repetitive but each note sounds fresh. Low sympathetic, crisp attack, medium sustain.",
        ["piano", "minimalist", "repetitive", "modern"],
        {"brightness": 0.52, "warmth": 0.58, "movement": 0.08, "density": 0.6, "space": 0.4, "aggression": 0.2},
        oven_params(brightness=4000.0, body_resonance=0.5, hf_amount=0.48, hardness=0.4, density=0.6, temperature=0.45,
                    sympathetic=0.22, bloom_time=0.0, sustain_time=3.0, filter_env_amt=0.3,
                    amp_attack=0.001, amp_decay=2.0, amp_sustain=0.25, amp_release=1.5),
    ),
    make_preset(
        "Baroque Iron",
        "Foundation",
        "Harpsichord character with piano sustain. High hardness, fast attack, crisply articulated. The cast iron frame adds a non-authentic warmth.",
        ["piano", "baroque", "harpsichord", "crisp"],
        {"brightness": 0.68, "warmth": 0.5, "movement": 0.08, "density": 0.58, "space": 0.3, "aggression": 0.5},
        oven_params(brightness=7000.0, body_resonance=0.42, hf_amount=0.6, hardness=0.82, density=0.58, temperature=0.45,
                    sympathetic=0.18, bloom_time=0.0, sustain_time=2.0, filter_env_amt=0.45,
                    amp_attack=0.001, amp_decay=1.2, amp_sustain=0.15, amp_release=0.8),
    ),
    make_preset(
        "Impressionist",
        "Foundation",
        "Debussy and Ravel voicings. Soft attack, extended sympathetic, hazy HF fill. Notes dissolve into each other.",
        ["piano", "impressionist", "debussy", "soft"],
        {"brightness": 0.45, "warmth": 0.7, "movement": 0.2, "density": 0.65, "space": 0.6, "aggression": 0.08},
        oven_params(brightness=3000.0, body_resonance=0.65, hf_amount=0.52, hardness=0.22, density=0.65, temperature=0.5,
                    sympathetic=0.65, bloom_time=0.1, sustain_time=6.5, filter_env_amt=0.28,
                    amp_attack=0.004, amp_decay=4.0, amp_sustain=0.42, amp_release=3.5),
    ),
    make_preset(
        "Concert Attack",
        "Foundation",
        "Aggressive concert touch. High hardness and HF, the iron frame clangs on the transient before settling.",
        ["piano", "attack", "concert", "forte"],
        {"brightness": 0.7, "warmth": 0.5, "movement": 0.1, "density": 0.7, "space": 0.35, "aggression": 0.8},
        oven_params(brightness=7500.0, body_resonance=0.55, hf_amount=0.75, hardness=0.9, density=0.7, temperature=0.55,
                    sympathetic=0.25, bloom_time=0.0, sustain_time=3.0, filter_env_amt=0.6,
                    amp_attack=0.001, amp_decay=2.0, amp_sustain=0.25, amp_release=1.5),
    ),
    make_preset(
        "Stage Grand",
        "Foundation",
        "Amplified concert piano for large stage. Full and present with slight mid-forward EQ curve implied by high body resonance.",
        ["piano", "stage", "live", "present"],
        {"brightness": 0.58, "warmth": 0.65, "movement": 0.12, "density": 0.78, "space": 0.45, "aggression": 0.4},
        oven_params(brightness=4800.0, body_resonance=0.75, hf_amount=0.55, hardness=0.55, density=0.78, temperature=0.52,
                    sympathetic=0.35, bloom_time=0.0, sustain_time=3.5, filter_env_amt=0.42,
                    amp_attack=0.001, amp_decay=2.5, amp_sustain=0.32, amp_release=1.8),
    ),
    make_preset(
        "Chamber Delicate",
        "Foundation",
        "Chamber music piano. Delicate, intimate, each note counts. Low hardness, soft body, clear sympathetic.",
        ["piano", "chamber", "delicate", "classical"],
        {"brightness": 0.45, "warmth": 0.68, "movement": 0.12, "density": 0.58, "space": 0.52, "aggression": 0.08},
        oven_params(brightness=3200.0, body_resonance=0.55, hf_amount=0.38, hardness=0.22, density=0.58, temperature=0.42,
                    sympathetic=0.48, bloom_time=0.05, sustain_time=4.0, filter_env_amt=0.25,
                    amp_attack=0.003, amp_decay=2.8, amp_sustain=0.35, amp_release=2.2),
    ),
]

# ===========================  DEEP (20)  =====================================

PRESETS += [
    make_preset(
        "Iron Mass Low",
        "Deep",
        "The lowest register of the cast iron piano. Dense, rumbling modal resonators. Each note feels like a weight being placed on the floor.",
        ["piano", "bass", "deep", "iron", "heavy"],
        {"brightness": 0.2, "warmth": 0.8, "movement": 0.1, "density": 0.95, "space": 0.4, "aggression": 0.4},
        oven_params(brightness=500.0, body_resonance=0.9, hf_amount=0.15, hardness=0.6, density=0.95, temperature=0.5,
                    sympathetic=0.35, bloom_time=0.0, sustain_time=5.0, filter_env_amt=0.25,
                    amp_attack=0.002, amp_decay=3.0, amp_sustain=0.4, amp_release=2.5),
    ),
    make_preset(
        "Forge Foundation",
        "Deep",
        "Subterranean resonance. The modal bank tuned to the lower partial series. Temperature at maximum — every note is slightly sharp.",
        ["piano", "deep", "forge", "hot"],
        {"brightness": 0.18, "warmth": 0.85, "movement": 0.15, "density": 0.92, "space": 0.35, "aggression": 0.5},
        oven_params(brightness=400.0, body_resonance=0.88, hf_amount=0.12, hardness=0.7, density=0.92, temperature=1.0,
                    sympathetic=0.3, bloom_time=0.1, sustain_time=4.5, filter_env_amt=0.22,
                    amp_attack=0.001, amp_decay=3.5, amp_sustain=0.45, amp_release=3.0),
    ),
    make_preset(
        "Bass Rumble",
        "Deep",
        "Pure low-frequency mass. Near-subsonic modal resonators with high density and body resonance. Not a melody instrument — a tectonic event.",
        ["bass", "deep", "subsonic", "heavy"],
        {"brightness": 0.12, "warmth": 0.82, "movement": 0.08, "density": 1.0, "space": 0.3, "aggression": 0.6},
        oven_params(brightness=300.0, body_resonance=0.95, hf_amount=0.05, hardness=0.75, density=1.0, temperature=0.55,
                    sympathetic=0.2, bloom_time=0.0, sustain_time=6.0, filter_env_amt=0.18,
                    amp_attack=0.002, amp_decay=4.0, amp_sustain=0.5, amp_release=3.5),
    ),
    make_preset(
        "Dungeon Piano",
        "Deep",
        "Thick, dark, cold iron. Minimal HF fill, maximum density. Sounds like playing a piano at the bottom of a stone dungeon.",
        ["piano", "dark", "dungeon", "gothic"],
        {"brightness": 0.15, "warmth": 0.75, "movement": 0.08, "density": 0.9, "space": 0.25, "aggression": 0.35},
        oven_params(brightness=350.0, body_resonance=0.85, hf_amount=0.08, hardness=0.55, density=0.9, temperature=0.35,
                    sympathetic=0.28, bloom_time=0.0, sustain_time=4.0, filter_env_amt=0.2,
                    amp_attack=0.002, amp_decay=3.0, amp_sustain=0.38, amp_release=2.5),
    ),
    make_preset(
        "Iron Pressure",
        "Deep",
        "Cast iron under compression. High density and hardness at mid-low brightness. The attack has a plosive quality before the sustain fills.",
        ["piano", "pressure", "dense", "attack"],
        {"brightness": 0.25, "warmth": 0.75, "movement": 0.1, "density": 0.92, "space": 0.35, "aggression": 0.75},
        oven_params(brightness=700.0, body_resonance=0.85, hf_amount=0.2, hardness=0.85, density=0.92, temperature=0.55,
                    sympathetic=0.25, bloom_time=0.0, sustain_time=3.5, filter_env_amt=0.35,
                    amp_attack=0.001, amp_decay=2.5, amp_sustain=0.35, amp_release=2.0),
    ),
    make_preset(
        "Thermal Basement",
        "Deep",
        "Warm low register. High temperature keeps the low resonators slightly sharp and beating against each other. Organic liveness.",
        ["piano", "deep", "warm", "thermal"],
        {"brightness": 0.2, "warmth": 0.88, "movement": 0.22, "density": 0.85, "space": 0.38, "aggression": 0.3},
        oven_params(brightness=500.0, body_resonance=0.88, hf_amount=0.18, hardness=0.5, density=0.85, temperature=0.82,
                    sympathetic=0.38, bloom_time=0.12, sustain_time=5.0, filter_env_amt=0.25,
                    amp_attack=0.002, amp_decay=3.5, amp_sustain=0.42, amp_release=3.0,
                    lfo1_rate=0.08, lfo1_depth=0.05),
    ),
    make_preset(
        "Heavy Chord",
        "Deep",
        "Orchestral bass chord hammer. The entire piano frame vibrates. Sustained for three beats.",
        ["piano", "chord", "orchestra", "bass"],
        {"brightness": 0.28, "warmth": 0.78, "movement": 0.12, "density": 0.88, "space": 0.5, "aggression": 0.7},
        oven_params(brightness=800.0, body_resonance=0.82, hf_amount=0.25, hardness=0.78, density=0.88, temperature=0.52,
                    sympathetic=0.42, bloom_time=0.05, sustain_time=5.5, filter_env_amt=0.3,
                    amp_attack=0.001, amp_decay=4.0, amp_sustain=0.45, amp_release=3.0),
    ),
    make_preset(
        "Cast Iron Solo",
        "Deep",
        "The lowest register solo voice. Full range of the piano but biased deep. Like Monk comping in the bass clef.",
        ["piano", "solo", "bass", "jazz"],
        {"brightness": 0.3, "warmth": 0.72, "movement": 0.1, "density": 0.82, "space": 0.38, "aggression": 0.4},
        oven_params(brightness=900.0, body_resonance=0.78, hf_amount=0.28, hardness=0.55, density=0.82, temperature=0.5,
                    sympathetic=0.32, bloom_time=0.0, sustain_time=4.0, filter_env_amt=0.28,
                    amp_attack=0.001, amp_decay=2.8, amp_sustain=0.38, amp_release=2.2),
    ),
    make_preset(
        "Sub Register",
        "Deep",
        "The string bass territory of the piano — low As and Gs played with authority. High HF fill adds a physical thump to each strike.",
        ["piano", "bass", "sub", "register"],
        {"brightness": 0.22, "warmth": 0.78, "movement": 0.08, "density": 0.9, "space": 0.32, "aggression": 0.55},
        oven_params(brightness=450.0, body_resonance=0.88, hf_amount=0.3, hardness=0.68, density=0.9, temperature=0.48,
                    sympathetic=0.22, bloom_time=0.0, sustain_time=4.5, filter_env_amt=0.28,
                    amp_attack=0.001, amp_decay=3.5, amp_sustain=0.42, amp_release=2.8),
    ),
    make_preset(
        "Anvil Tone",
        "Deep",
        "The iron as instrument rather than piano. Metallic, dense, ring. High hardness and HF at low brightness create a struck-metal timbre.",
        ["piano", "metal", "anvil", "industrial"],
        {"brightness": 0.3, "warmth": 0.62, "movement": 0.2, "density": 0.85, "space": 0.45, "aggression": 0.85},
        oven_params(brightness=800.0, body_resonance=0.7, hf_amount=0.7, hardness=0.92, density=0.85, temperature=0.65,
                    sympathetic=0.5, bloom_time=0.08, sustain_time=5.0, filter_env_amt=0.45,
                    amp_attack=0.001, amp_decay=3.0, amp_sustain=0.25, amp_release=2.5),
    ),
    make_preset(
        "Gravity Notes",
        "Deep",
        "Each note feels heavy. High density, maximum sympathetic depth, long release. Notes resolve downward.",
        ["piano", "heavy", "gravity", "sustain"],
        {"brightness": 0.28, "warmth": 0.78, "movement": 0.15, "density": 0.92, "space": 0.55, "aggression": 0.3},
        oven_params(brightness=700.0, body_resonance=0.9, hf_amount=0.22, hardness=0.45, density=0.92, temperature=0.5,
                    sympathetic=0.72, bloom_time=0.1, sustain_time=7.0, filter_env_amt=0.22,
                    amp_attack=0.003, amp_decay=4.5, amp_sustain=0.48, amp_release=4.0),
    ),
    make_preset(
        "Iron Chamber Low",
        "Deep",
        "Low strings in a stone chamber. Dense and reverberant even before external reverb. Sympathetic resonance fills the space.",
        ["piano", "chamber", "low", "stone"],
        {"brightness": 0.22, "warmth": 0.72, "movement": 0.18, "density": 0.82, "space": 0.62, "aggression": 0.2},
        oven_params(brightness=550.0, body_resonance=0.82, hf_amount=0.15, hardness=0.38, density=0.82, temperature=0.45,
                    sympathetic=0.68, bloom_time=0.12, sustain_time=6.5, filter_env_amt=0.2,
                    amp_attack=0.003, amp_decay=4.0, amp_sustain=0.45, amp_release=3.8),
    ),
    make_preset(
        "Low Thermal Mass",
        "Deep",
        "Cast iron's defining characteristic: thermal inertia. Temperature is maximum, low end heats slowly, resonators drift.",
        ["piano", "thermal", "low", "drift"],
        {"brightness": 0.2, "warmth": 0.85, "movement": 0.3, "density": 0.88, "space": 0.42, "aggression": 0.25},
        oven_params(brightness=450.0, body_resonance=0.88, hf_amount=0.12, hardness=0.42, density=0.88, temperature=0.95,
                    sympathetic=0.4, bloom_time=0.2, sustain_time=5.5, filter_env_amt=0.2,
                    amp_attack=0.004, amp_decay=4.0, amp_sustain=0.45, amp_release=3.5,
                    lfo1_rate=0.06, lfo1_depth=0.07),
    ),
    make_preset(
        "Deep Bloom",
        "Deep",
        "Bloom time is extended at low frequency. The note begins almost inaudible then swells. Like a low string bowed slowly.",
        ["piano", "bloom", "deep", "swell"],
        {"brightness": 0.2, "warmth": 0.8, "movement": 0.35, "density": 0.8, "space": 0.5, "aggression": 0.15},
        oven_params(brightness=500.0, body_resonance=0.82, hf_amount=0.15, hardness=0.3, density=0.8, temperature=0.55,
                    sympathetic=0.5, bloom_time=0.55, sustain_time=6.0, filter_env_amt=0.18,
                    amp_attack=0.1, amp_decay=4.5, amp_sustain=0.42, amp_release=4.0),
    ),
    make_preset(
        "Subterranean",
        "Deep",
        "Rock bottom. Minimum brightness, maximum density and body resonance. Seismic event piano.",
        ["piano", "subterranean", "bass", "seismic"],
        {"brightness": 0.1, "warmth": 0.88, "movement": 0.06, "density": 0.98, "space": 0.28, "aggression": 0.5},
        oven_params(brightness=250.0, body_resonance=0.98, hf_amount=0.05, hardness=0.72, density=0.98, temperature=0.5,
                    sympathetic=0.18, bloom_time=0.0, sustain_time=5.0, filter_env_amt=0.15,
                    amp_attack=0.002, amp_decay=3.5, amp_sustain=0.48, amp_release=3.0),
    ),
    make_preset(
        "Muddy Waters",
        "Deep",
        "Blues bass piano. Low brightness, high body resonance, slightly elevated temperature for that lived-in character.",
        ["piano", "blues", "bass", "muddy"],
        {"brightness": 0.25, "warmth": 0.8, "movement": 0.15, "density": 0.85, "space": 0.35, "aggression": 0.45},
        oven_params(brightness=650.0, body_resonance=0.85, hf_amount=0.22, hardness=0.62, density=0.85, temperature=0.65,
                    sympathetic=0.28, bloom_time=0.05, sustain_time=3.5, filter_env_amt=0.32,
                    amp_attack=0.001, amp_decay=2.5, amp_sustain=0.38, amp_release=2.0),
    ),
    make_preset(
        "Iron Root",
        "Deep",
        "The deepest natural resonance of the instrument. Dense, slow, absolute. A single low D in a large room.",
        ["piano", "root", "deep", "resonant"],
        {"brightness": 0.18, "warmth": 0.82, "movement": 0.12, "density": 0.95, "space": 0.48, "aggression": 0.3},
        oven_params(brightness=380.0, body_resonance=0.92, hf_amount=0.1, hardness=0.5, density=0.95, temperature=0.48,
                    sympathetic=0.45, bloom_time=0.08, sustain_time=6.5, filter_env_amt=0.18,
                    amp_attack=0.002, amp_decay=4.2, amp_sustain=0.48, amp_release=3.8),
    ),
    make_preset(
        "Seismic Bloom",
        "Deep",
        "Bloom time long, low register, maximum thermal mass. The note arrives seconds after the hammer falls.",
        ["piano", "seismic", "bloom", "slow"],
        {"brightness": 0.15, "warmth": 0.82, "movement": 0.4, "density": 0.88, "space": 0.5, "aggression": 0.15},
        oven_params(brightness=380.0, body_resonance=0.88, hf_amount=0.1, hardness=0.28, density=0.88, temperature=0.7,
                    sympathetic=0.52, bloom_time=0.75, sustain_time=7.0, filter_env_amt=0.15,
                    amp_attack=0.15, amp_decay=5.0, amp_sustain=0.45, amp_release=5.0),
    ),
    make_preset(
        "Foundry Tone",
        "Deep",
        "Steel foundry acoustic. High temperature, dense material, forced bloom, metallic sustain.",
        ["piano", "foundry", "industrial", "iron"],
        {"brightness": 0.32, "warmth": 0.72, "movement": 0.3, "density": 0.88, "space": 0.42, "aggression": 0.72},
        oven_params(brightness=900.0, body_resonance=0.8, hf_amount=0.45, hardness=0.82, density=0.88, temperature=0.92,
                    sympathetic=0.35, bloom_time=0.25, sustain_time=4.0, filter_env_amt=0.38,
                    amp_attack=0.005, amp_decay=3.0, amp_sustain=0.35, amp_release=2.5,
                    lfo1_rate=0.1, lfo1_depth=0.06),
    ),
    make_preset(
        "Tectonic",
        "Deep",
        "Plate-tectonic scale. Low, inexorable, slow. Maximum competition means single notes suppress all others.",
        ["piano", "tectonic", "deep", "bass"],
        {"brightness": 0.15, "warmth": 0.8, "movement": 0.05, "density": 0.95, "space": 0.35, "aggression": 0.55},
        oven_params(brightness=300.0, body_resonance=0.92, hf_amount=0.08, hardness=0.65, density=0.95, temperature=0.5,
                    sympathetic=0.25, bloom_time=0.0, sustain_time=5.5, filter_env_amt=0.18,
                    amp_attack=0.002, amp_decay=4.0, amp_sustain=0.5, amp_release=3.5,
                    competition=0.6),
    ),
]

# ===========================  ETHEREAL (18)  ==================================

PRESETS += [
    make_preset(
        "Sympathetic Field",
        "Ethereal",
        "Only the sympathetic resonance strings exist. The actual note decays fast; what remains is the shimmer network.",
        ["piano", "sympathetic", "ethereal", "shimmer"],
        {"brightness": 0.55, "warmth": 0.6, "movement": 0.35, "density": 0.45, "space": 0.75, "aggression": 0.05},
        oven_params(brightness=5000.0, body_resonance=0.4, hf_amount=0.55, hardness=0.2, density=0.45, temperature=0.5,
                    sympathetic=0.95, bloom_time=0.2, sustain_time=8.0, filter_env_amt=0.2,
                    amp_attack=0.01, amp_decay=6.0, amp_sustain=0.3, amp_release=5.0,
                    lfo1_rate=0.15, lfo1_depth=0.08, lfo2_rate=0.22, lfo2_depth=0.05),
    ),
    make_preset(
        "Ghost Piano",
        "Ethereal",
        "The piano as memory. Long bloom, long sustain, high sympathetic. Notes arrive slowly and depart reluctantly.",
        ["piano", "ghost", "memory", "slow"],
        {"brightness": 0.45, "warmth": 0.65, "movement": 0.28, "density": 0.48, "space": 0.8, "aggression": 0.04},
        oven_params(brightness=3500.0, body_resonance=0.45, hf_amount=0.42, hardness=0.15, density=0.48, temperature=0.52,
                    sympathetic=0.88, bloom_time=0.45, sustain_time=9.0, filter_env_amt=0.18,
                    amp_attack=0.08, amp_decay=6.5, amp_sustain=0.32, amp_release=5.5),
    ),
    make_preset(
        "Iron Shimmer",
        "Ethereal",
        "Pure sympathetic resonance shimmer with fast LFO movement. The instrument is mostly air and vibration.",
        ["piano", "shimmer", "air", "resonant"],
        {"brightness": 0.6, "warmth": 0.55, "movement": 0.45, "density": 0.4, "space": 0.78, "aggression": 0.06},
        oven_params(brightness=6000.0, body_resonance=0.38, hf_amount=0.6, hardness=0.18, density=0.4, temperature=0.55,
                    sympathetic=0.92, bloom_time=0.3, sustain_time=9.0, filter_env_amt=0.22,
                    amp_attack=0.05, amp_decay=5.5, amp_sustain=0.28, amp_release=5.0,
                    lfo1_rate=0.4, lfo1_depth=0.1, lfo1_shape=2),
    ),
    make_preset(
        "Thermal Dream",
        "Ethereal",
        "High temperature causes pitch drift. The sympathetic strings wander. A dream of piano.",
        ["piano", "dream", "drift", "thermal"],
        {"brightness": 0.45, "warmth": 0.62, "movement": 0.55, "density": 0.45, "space": 0.72, "aggression": 0.04},
        oven_params(brightness=3500.0, body_resonance=0.42, hf_amount=0.45, hardness=0.15, density=0.45, temperature=0.95,
                    sympathetic=0.85, bloom_time=0.4, sustain_time=8.0, filter_env_amt=0.18,
                    amp_attack=0.1, amp_decay=5.5, amp_sustain=0.3, amp_release=5.0,
                    lfo1_rate=0.12, lfo1_depth=0.1),
    ),
    make_preset(
        "Cathedral Drone",
        "Ethereal",
        "A single note fills a cathedral. Very long sustain, maximum sympathetic, slow filter envelope. Meditative.",
        ["piano", "drone", "cathedral", "meditative"],
        {"brightness": 0.5, "warmth": 0.68, "movement": 0.18, "density": 0.5, "space": 0.88, "aggression": 0.03},
        oven_params(brightness=4000.0, body_resonance=0.5, hf_amount=0.48, hardness=0.15, density=0.5, temperature=0.5,
                    sympathetic=0.98, bloom_time=0.55, sustain_time=12.0, filter_env_amt=0.15,
                    amp_attack=0.15, amp_decay=8.0, amp_sustain=0.35, amp_release=7.0),
    ),
    make_preset(
        "Piano Haze",
        "Ethereal",
        "Notes dissolve before they fully form. Very fast attack but extremely long bloom that blurs the onset.",
        ["piano", "haze", "diffuse", "ambient"],
        {"brightness": 0.42, "warmth": 0.65, "movement": 0.3, "density": 0.42, "space": 0.82, "aggression": 0.04},
        oven_params(brightness=3200.0, body_resonance=0.42, hf_amount=0.4, hardness=0.12, density=0.42, temperature=0.6,
                    sympathetic=0.88, bloom_time=0.5, sustain_time=10.0, filter_env_amt=0.15,
                    amp_attack=0.12, amp_decay=6.0, amp_sustain=0.32, amp_release=6.0,
                    lfo1_rate=0.08, lfo1_depth=0.06, lfo2_rate=0.15, lfo2_depth=0.04),
    ),
    make_preset(
        "Suspended Chord",
        "Ethereal",
        "A chord held indefinitely. Time has stopped. The sympathetic network holds the harmony in suspension.",
        ["piano", "chord", "sustained", "ambient"],
        {"brightness": 0.5, "warmth": 0.65, "movement": 0.15, "density": 0.5, "space": 0.78, "aggression": 0.04},
        oven_params(brightness=4000.0, body_resonance=0.5, hf_amount=0.45, hardness=0.15, density=0.5, temperature=0.52,
                    sympathetic=0.92, bloom_time=0.35, sustain_time=11.0, filter_env_amt=0.18,
                    amp_attack=0.08, amp_decay=7.0, amp_sustain=0.35, amp_release=6.5),
    ),
    make_preset(
        "Resonant Aura",
        "Ethereal",
        "The resonance of the room after the pianist walks away. Only sympathetic and body resonance remain.",
        ["piano", "ambient", "room", "resonant"],
        {"brightness": 0.48, "warmth": 0.65, "movement": 0.25, "density": 0.45, "space": 0.85, "aggression": 0.03},
        oven_params(brightness=3800.0, body_resonance=0.55, hf_amount=0.4, hardness=0.1, density=0.45, temperature=0.5,
                    sympathetic=0.95, bloom_time=0.6, sustain_time=12.0, filter_env_amt=0.12,
                    amp_attack=0.2, amp_decay=7.5, amp_sustain=0.3, amp_release=7.0),
    ),
    make_preset(
        "Spectral Iron",
        "Ethereal",
        "Piano at the edge of audibility. High frequency only, low density, pure sympathetic shimmer.",
        ["piano", "spectral", "bright", "shimmer"],
        {"brightness": 0.78, "warmth": 0.38, "movement": 0.38, "density": 0.32, "space": 0.75, "aggression": 0.06},
        oven_params(brightness=10000.0, body_resonance=0.28, hf_amount=0.82, hardness=0.2, density=0.32, temperature=0.55,
                    sympathetic=0.88, bloom_time=0.25, sustain_time=8.0, filter_env_amt=0.28,
                    amp_attack=0.05, amp_decay=4.5, amp_sustain=0.22, amp_release=4.5),
    ),
    make_preset(
        "Night Modal",
        "Ethereal",
        "The modal resonators audible as separate frequencies in the silence of night. Slow LFO drift.",
        ["piano", "modal", "night", "ambient"],
        {"brightness": 0.45, "warmth": 0.7, "movement": 0.35, "density": 0.48, "space": 0.72, "aggression": 0.04},
        oven_params(brightness=3000.0, body_resonance=0.5, hf_amount=0.38, hardness=0.12, density=0.48, temperature=0.55,
                    sympathetic=0.85, bloom_time=0.4, sustain_time=9.5, filter_env_amt=0.15,
                    amp_attack=0.1, amp_decay=6.0, amp_sustain=0.32, amp_release=5.5,
                    lfo1_rate=0.07, lfo1_depth=0.08, lfo1_shape=0, lfo2_rate=0.12, lfo2_depth=0.05),
    ),
    make_preset(
        "Liminal Piano",
        "Ethereal",
        "Threshold between piano and atmosphere. Extremely soft attack, very long decay, sympathetic resonance dominant.",
        ["piano", "ambient", "liminal", "threshold"],
        {"brightness": 0.42, "warmth": 0.65, "movement": 0.3, "density": 0.42, "space": 0.85, "aggression": 0.03},
        oven_params(brightness=3200.0, body_resonance=0.45, hf_amount=0.38, hardness=0.1, density=0.42, temperature=0.5,
                    sympathetic=0.95, bloom_time=0.55, sustain_time=11.0, filter_env_amt=0.12,
                    amp_attack=0.18, amp_decay=7.0, amp_sustain=0.32, amp_release=7.5),
    ),
    make_preset(
        "Thermal Aether",
        "Ethereal",
        "Maximum temperature ethereal. The entire instrument shimmers with thermal drift. Slow LFOs on both axes.",
        ["piano", "thermal", "ethereal", "drift"],
        {"brightness": 0.5, "warmth": 0.65, "movement": 0.5, "density": 0.42, "space": 0.78, "aggression": 0.04},
        oven_params(brightness=4000.0, body_resonance=0.42, hf_amount=0.48, hardness=0.12, density=0.42, temperature=1.0,
                    sympathetic=0.9, bloom_time=0.45, sustain_time=10.0, filter_env_amt=0.15,
                    amp_attack=0.12, amp_decay=6.5, amp_sustain=0.3, amp_release=6.5,
                    lfo1_rate=0.08, lfo1_depth=0.1, lfo2_rate=0.14, lfo2_depth=0.06),
    ),
    make_preset(
        "Vibrational Tide",
        "Ethereal",
        "The sympathetic resonance waxes and wanes like a tide. LFO2 modulates at a slow sine rate.",
        ["piano", "tide", "wave", "ambient"],
        {"brightness": 0.48, "warmth": 0.65, "movement": 0.42, "density": 0.45, "space": 0.8, "aggression": 0.04},
        oven_params(brightness=3800.0, body_resonance=0.45, hf_amount=0.42, hardness=0.12, density=0.45, temperature=0.55,
                    sympathetic=0.92, bloom_time=0.5, sustain_time=10.0, filter_env_amt=0.15,
                    amp_attack=0.12, amp_decay=6.5, amp_sustain=0.32, amp_release=6.0,
                    lfo1_rate=0.1, lfo1_depth=0.08, lfo2_rate=0.05, lfo2_depth=0.1, lfo2_shape=0),
    ),
    make_preset(
        "Iron Whisper",
        "Ethereal",
        "The quietest voice the instrument can make. Below pianissimo. The frame absorbs the impact and returns a breath.",
        ["piano", "quiet", "whisper", "soft"],
        {"brightness": 0.4, "warmth": 0.68, "movement": 0.18, "density": 0.38, "space": 0.75, "aggression": 0.02},
        oven_params(brightness=2800.0, body_resonance=0.4, hf_amount=0.3, hardness=0.08, density=0.38, temperature=0.48,
                    sympathetic=0.85, bloom_time=0.35, sustain_time=9.0, filter_env_amt=0.1,
                    amp_attack=0.2, amp_decay=5.5, amp_sustain=0.3, amp_release=6.0),
    ),
    make_preset(
        "Resonance Bloom",
        "Ethereal",
        "Bloom time set to maximum. The note swells up over 1+ seconds before reaching full voice. Ethereal entry.",
        ["piano", "bloom", "swell", "ambient"],
        {"brightness": 0.48, "warmth": 0.65, "movement": 0.42, "density": 0.48, "space": 0.75, "aggression": 0.04},
        oven_params(brightness=3500.0, body_resonance=0.5, hf_amount=0.42, hardness=0.15, density=0.48, temperature=0.55,
                    sympathetic=0.85, bloom_time=0.95, sustain_time=9.0, filter_env_amt=0.18,
                    amp_attack=0.5, amp_decay=6.0, amp_sustain=0.35, amp_release=5.5),
    ),
    make_preset(
        "Crystalline Memory",
        "Ethereal",
        "High brightness, very low density, pure sympathetic. Notes leave crystal impressions rather than physical tones.",
        ["piano", "crystal", "memory", "bright"],
        {"brightness": 0.75, "warmth": 0.4, "movement": 0.32, "density": 0.32, "space": 0.82, "aggression": 0.06},
        oven_params(brightness=9000.0, body_resonance=0.28, hf_amount=0.75, hardness=0.18, density=0.32, temperature=0.52,
                    sympathetic=0.9, bloom_time=0.3, sustain_time=8.5, filter_env_amt=0.22,
                    amp_attack=0.08, amp_decay=5.0, amp_sustain=0.22, amp_release=5.0),
    ),
    make_preset(
        "Floating Stave",
        "Ethereal",
        "Notes from the top of the staff rise upward and float. High register, high sympathetic, near-zero density.",
        ["piano", "high", "floating", "top"],
        {"brightness": 0.72, "warmth": 0.42, "movement": 0.35, "density": 0.3, "space": 0.8, "aggression": 0.05},
        oven_params(brightness=10000.0, body_resonance=0.25, hf_amount=0.72, hardness=0.15, density=0.3, temperature=0.5,
                    sympathetic=0.92, bloom_time=0.35, sustain_time=8.0, filter_env_amt=0.2,
                    amp_attack=0.1, amp_decay=5.0, amp_sustain=0.22, amp_release=5.5),
    ),
    make_preset(
        "Halo Overtones",
        "Ethereal",
        "Every note is surrounded by a halo of sympathetic resonance overtones. High HF, high sympathetic, slow bloom.",
        ["piano", "overtone", "halo", "harmonic"],
        {"brightness": 0.65, "warmth": 0.5, "movement": 0.32, "density": 0.42, "space": 0.78, "aggression": 0.06},
        oven_params(brightness=7000.0, body_resonance=0.38, hf_amount=0.75, hardness=0.18, density=0.42, temperature=0.55,
                    sympathetic=0.92, bloom_time=0.3, sustain_time=8.5, filter_env_amt=0.25,
                    amp_attack=0.08, amp_decay=5.5, amp_sustain=0.25, amp_release=5.0),
    ),
]

# ===========================  SUBMERGED (12)  =================================

PRESETS += [
    make_preset(
        "Underwater Grand",
        "Submerged",
        "Piano heard through water. Low brightness, high density, long bloom. The attack travels slowly to the surface.",
        ["piano", "underwater", "slow", "ambient"],
        {"brightness": 0.25, "warmth": 0.72, "movement": 0.4, "density": 0.78, "space": 0.62, "aggression": 0.08},
        oven_params(brightness=600.0, body_resonance=0.82, hf_amount=0.12, hardness=0.22, density=0.78, temperature=0.52,
                    sympathetic=0.62, bloom_time=0.65, sustain_time=7.0, filter_env_amt=0.15,
                    amp_attack=0.2, amp_decay=5.0, amp_sustain=0.4, amp_release=5.0),
    ),
    make_preset(
        "Sunken Notes",
        "Submerged",
        "Notes sinking beneath the surface. Slow bloom, high sympathetic depth, low temperature. The Titanics piano.",
        ["piano", "sunken", "deep", "slow"],
        {"brightness": 0.2, "warmth": 0.75, "movement": 0.35, "density": 0.82, "space": 0.55, "aggression": 0.06},
        oven_params(brightness=450.0, body_resonance=0.85, hf_amount=0.1, hardness=0.18, density=0.82, temperature=0.35,
                    sympathetic=0.72, bloom_time=0.75, sustain_time=8.0, filter_env_amt=0.12,
                    amp_attack=0.3, amp_decay=5.5, amp_sustain=0.4, amp_release=5.5),
    ),
    make_preset(
        "Slow Submersion",
        "Submerged",
        "A piano being slowly lowered into water. Bloom time at maximum. The attack drowns.",
        ["piano", "submersion", "slow", "bloom"],
        {"brightness": 0.25, "warmth": 0.72, "movement": 0.5, "density": 0.75, "space": 0.55, "aggression": 0.05},
        oven_params(brightness=600.0, body_resonance=0.8, hf_amount=0.1, hardness=0.15, density=0.75, temperature=0.45,
                    sympathetic=0.68, bloom_time=0.9, sustain_time=8.0, filter_env_amt=0.12,
                    amp_attack=0.5, amp_decay=5.0, amp_sustain=0.4, amp_release=6.0),
    ),
    make_preset(
        "Deep Tide",
        "Submerged",
        "The tidal motion of a deep body of water translated into piano bloom. LFO2 at very low rate.",
        ["piano", "tide", "deep", "motion"],
        {"brightness": 0.3, "warmth": 0.72, "movement": 0.45, "density": 0.72, "space": 0.62, "aggression": 0.06},
        oven_params(brightness=800.0, body_resonance=0.78, hf_amount=0.15, hardness=0.18, density=0.72, temperature=0.5,
                    sympathetic=0.65, bloom_time=0.7, sustain_time=7.5, filter_env_amt=0.15,
                    amp_attack=0.4, amp_decay=5.0, amp_sustain=0.38, amp_release=5.5,
                    lfo2_rate=0.04, lfo2_depth=0.1, lfo2_shape=0),
    ),
    make_preset(
        "Pressure Drone",
        "Submerged",
        "Low frequency under water pressure. High density, long sustain, high body resonance, minimum attack.",
        ["piano", "pressure", "drone", "deep"],
        {"brightness": 0.18, "warmth": 0.8, "movement": 0.2, "density": 0.9, "space": 0.52, "aggression": 0.12},
        oven_params(brightness=350.0, body_resonance=0.9, hf_amount=0.08, hardness=0.35, density=0.9, temperature=0.45,
                    sympathetic=0.68, bloom_time=0.6, sustain_time=9.0, filter_env_amt=0.12,
                    amp_attack=0.35, amp_decay=6.0, amp_sustain=0.45, amp_release=6.5),
    ),
    make_preset(
        "Brine Chord",
        "Submerged",
        "Saltwater acoustic: density increased, resonance longer, thermal drift more pronounced. Like tuning in a submarine.",
        ["piano", "water", "brine", "deep"],
        {"brightness": 0.28, "warmth": 0.75, "movement": 0.35, "density": 0.82, "space": 0.5, "aggression": 0.1},
        oven_params(brightness=700.0, body_resonance=0.82, hf_amount=0.12, hardness=0.25, density=0.82, temperature=0.65,
                    sympathetic=0.6, bloom_time=0.6, sustain_time=7.0, filter_env_amt=0.14,
                    amp_attack=0.3, amp_decay=4.5, amp_sustain=0.38, amp_release=5.0,
                    lfo1_rate=0.05, lfo1_depth=0.07),
    ),
    make_preset(
        "Fathom Tone",
        "Submerged",
        "Six thousand feet down. Every parameter pushed toward depth and density. Barely recognizable as piano.",
        ["piano", "fathom", "deep", "ambient"],
        {"brightness": 0.12, "warmth": 0.85, "movement": 0.28, "density": 0.95, "space": 0.42, "aggression": 0.1},
        oven_params(brightness=280.0, body_resonance=0.95, hf_amount=0.05, hardness=0.3, density=0.95, temperature=0.48,
                    sympathetic=0.72, bloom_time=0.8, sustain_time=10.0, filter_env_amt=0.1,
                    amp_attack=0.5, amp_decay=6.5, amp_sustain=0.45, amp_release=7.0),
    ),
    make_preset(
        "Bloom Surge",
        "Submerged",
        "Mid-length bloom with a surge at the peak. Bloom time 0.5, filter env high. The note erupts from the surface.",
        ["piano", "bloom", "surge", "submerged"],
        {"brightness": 0.35, "warmth": 0.72, "movement": 0.45, "density": 0.72, "space": 0.55, "aggression": 0.2},
        oven_params(brightness=1500.0, body_resonance=0.75, hf_amount=0.22, hardness=0.35, density=0.72, temperature=0.55,
                    sympathetic=0.55, bloom_time=0.5, sustain_time=6.0, filter_env_amt=0.45,
                    amp_attack=0.25, amp_decay=4.0, amp_sustain=0.35, amp_release=4.5),
    ),
    make_preset(
        "Current Drift",
        "Submerged",
        "Thermal drift carries the pitch like an ocean current. Maximum temperature, long bloom, high sympathetic.",
        ["piano", "drift", "current", "submerged"],
        {"brightness": 0.32, "warmth": 0.78, "movement": 0.55, "density": 0.68, "space": 0.55, "aggression": 0.06},
        oven_params(brightness=900.0, body_resonance=0.78, hf_amount=0.15, hardness=0.18, density=0.68, temperature=0.98,
                    sympathetic=0.65, bloom_time=0.65, sustain_time=7.5, filter_env_amt=0.15,
                    amp_attack=0.4, amp_decay=5.0, amp_sustain=0.38, amp_release=5.5,
                    lfo1_rate=0.06, lfo1_depth=0.09),
    ),
    make_preset(
        "Ocean Floor",
        "Submerged",
        "Absolute bottom. Maximum density, minimum brightness, very long bloom. Geological time scale.",
        ["piano", "ocean", "floor", "deep"],
        {"brightness": 0.1, "warmth": 0.88, "movement": 0.3, "density": 0.98, "space": 0.38, "aggression": 0.1},
        oven_params(brightness=250.0, body_resonance=0.98, hf_amount=0.04, hardness=0.28, density=0.98, temperature=0.5,
                    sympathetic=0.68, bloom_time=0.85, sustain_time=10.0, filter_env_amt=0.1,
                    amp_attack=0.6, amp_decay=7.0, amp_sustain=0.45, amp_release=7.5),
    ),
    make_preset(
        "Still Water",
        "Submerged",
        "Perfectly still water. Bloom is medium, sympathetic high, temperature low. Peaceful and resolute.",
        ["piano", "still", "water", "calm"],
        {"brightness": 0.35, "warmth": 0.72, "movement": 0.2, "density": 0.65, "space": 0.68, "aggression": 0.04},
        oven_params(brightness=1200.0, body_resonance=0.72, hf_amount=0.15, hardness=0.2, density=0.65, temperature=0.38,
                    sympathetic=0.72, bloom_time=0.45, sustain_time=7.0, filter_env_amt=0.14,
                    amp_attack=0.25, amp_decay=4.5, amp_sustain=0.38, amp_release=5.0),
    ),
    make_preset(
        "Murk Tone",
        "Submerged",
        "Turbid water. Low brightness, high body resonance, maximum density. Organic murk before the clarifying strike.",
        ["piano", "murk", "turbid", "dense"],
        {"brightness": 0.2, "warmth": 0.8, "movement": 0.25, "density": 0.9, "space": 0.45, "aggression": 0.18},
        oven_params(brightness=400.0, body_resonance=0.92, hf_amount=0.1, hardness=0.38, density=0.9, temperature=0.55,
                    sympathetic=0.58, bloom_time=0.55, sustain_time=6.5, filter_env_amt=0.15,
                    amp_attack=0.35, amp_decay=4.5, amp_sustain=0.4, amp_release=5.0),
    ),
]

# ===========================  LUMINOUS (12)  ==================================

PRESETS += [
    make_preset(
        "Bright Attack",
        "Luminous",
        "Maximum brightness, very high hardness. The modal resonators at full HF register. Crisp, immediate, luminous.",
        ["piano", "bright", "attack", "luminous"],
        {"brightness": 0.92, "warmth": 0.35, "movement": 0.1, "density": 0.55, "space": 0.45, "aggression": 0.75},
        oven_params(brightness=14000.0, body_resonance=0.35, hf_amount=0.9, hardness=0.88, density=0.55, temperature=0.55,
                    sympathetic=0.28, bloom_time=0.0, sustain_time=2.5, filter_env_amt=0.65,
                    amp_attack=0.001, amp_decay=1.5, amp_sustain=0.22, amp_release=1.2),
    ),
    make_preset(
        "Tine Glint",
        "Luminous",
        "The bright tine of an electric piano model expressed through modal resonators. Sparkling, immediate.",
        ["piano", "bright", "tine", "sparkle"],
        {"brightness": 0.85, "warmth": 0.4, "movement": 0.12, "density": 0.5, "space": 0.48, "aggression": 0.6},
        oven_params(brightness=12000.0, body_resonance=0.3, hf_amount=0.85, hardness=0.78, density=0.5, temperature=0.55,
                    sympathetic=0.22, bloom_time=0.0, sustain_time=2.0, filter_env_amt=0.55,
                    amp_attack=0.001, amp_decay=1.2, amp_sustain=0.2, amp_release=1.0),
    ),
    make_preset(
        "Sunlit Keys",
        "Luminous",
        "High brightness with warmth. Morning sunlight on piano keys. Bright but not harsh.",
        ["piano", "sunlit", "bright", "warm"],
        {"brightness": 0.8, "warmth": 0.5, "movement": 0.12, "density": 0.55, "space": 0.48, "aggression": 0.45},
        oven_params(brightness=11000.0, body_resonance=0.4, hf_amount=0.78, hardness=0.68, density=0.55, temperature=0.55,
                    sympathetic=0.28, bloom_time=0.0, sustain_time=2.5, filter_env_amt=0.5,
                    amp_attack=0.001, amp_decay=1.5, amp_sustain=0.25, amp_release=1.3),
    ),
    make_preset(
        "Chord Shimmer",
        "Luminous",
        "Bright chord voiced at the top. HF modal resonators ring clear. Sympathetic shimmer adds a halo.",
        ["piano", "chord", "shimmer", "bright"],
        {"brightness": 0.78, "warmth": 0.45, "movement": 0.22, "density": 0.5, "space": 0.58, "aggression": 0.4},
        oven_params(brightness=10000.0, body_resonance=0.38, hf_amount=0.8, hardness=0.6, density=0.5, temperature=0.55,
                    sympathetic=0.55, bloom_time=0.1, sustain_time=3.5, filter_env_amt=0.5,
                    amp_attack=0.001, amp_decay=2.0, amp_sustain=0.28, amp_release=2.0),
    ),
    make_preset(
        "Bright Forte",
        "Luminous",
        "Forte attack at high brightness. The iron frame rings clear at the transient. Powerful and luminous.",
        ["piano", "forte", "bright", "attack"],
        {"brightness": 0.88, "warmth": 0.38, "movement": 0.1, "density": 0.55, "space": 0.4, "aggression": 0.88},
        oven_params(brightness=13000.0, body_resonance=0.32, hf_amount=0.88, hardness=0.95, density=0.55, temperature=0.6,
                    sympathetic=0.2, bloom_time=0.0, sustain_time=2.0, filter_env_amt=0.7,
                    amp_attack=0.001, amp_decay=1.5, amp_sustain=0.2, amp_release=1.2),
    ),
    make_preset(
        "Glass Resonance",
        "Luminous",
        "Like a glass harmonica played at the piano. Very high brightness, minimum density, maximum HF fill.",
        ["piano", "glass", "bright", "crystal"],
        {"brightness": 0.9, "warmth": 0.3, "movement": 0.18, "density": 0.38, "space": 0.6, "aggression": 0.5},
        oven_params(brightness=14000.0, body_resonance=0.25, hf_amount=0.92, hardness=0.7, density=0.38, temperature=0.5,
                    sympathetic=0.42, bloom_time=0.1, sustain_time=4.0, filter_env_amt=0.55,
                    amp_attack=0.001, amp_decay=2.5, amp_sustain=0.2, amp_release=2.5),
    ),
    make_preset(
        "High Octave",
        "Luminous",
        "The treble register of the concert grand pushed further. Bright, fast-decaying, physical.",
        ["piano", "treble", "high", "bright"],
        {"brightness": 0.82, "warmth": 0.42, "movement": 0.1, "density": 0.52, "space": 0.42, "aggression": 0.55},
        oven_params(brightness=11500.0, body_resonance=0.35, hf_amount=0.82, hardness=0.72, density=0.52, temperature=0.52,
                    sympathetic=0.22, bloom_time=0.0, sustain_time=1.8, filter_env_amt=0.55,
                    amp_attack=0.001, amp_decay=1.2, amp_sustain=0.18, amp_release=1.0),
    ),
    make_preset(
        "Bell Strike",
        "Luminous",
        "High brightness metallic bell character from the cast iron. Ringing, pure, long decay.",
        ["piano", "bell", "bright", "metallic"],
        {"brightness": 0.85, "warmth": 0.35, "movement": 0.2, "density": 0.45, "space": 0.65, "aggression": 0.55},
        oven_params(brightness=12500.0, body_resonance=0.28, hf_amount=0.85, hardness=0.75, density=0.45, temperature=0.58,
                    sympathetic=0.55, bloom_time=0.12, sustain_time=5.0, filter_env_amt=0.55,
                    amp_attack=0.001, amp_decay=3.5, amp_sustain=0.18, amp_release=3.5),
    ),
    make_preset(
        "Daylight Keys",
        "Luminous",
        "Open, airy, full daylight. Bright but with warmth in the body resonance. Afternoon practice session.",
        ["piano", "bright", "airy", "daylight"],
        {"brightness": 0.75, "warmth": 0.52, "movement": 0.12, "density": 0.55, "space": 0.5, "aggression": 0.35},
        oven_params(brightness=9500.0, body_resonance=0.45, hf_amount=0.75, hardness=0.6, density=0.55, temperature=0.52,
                    sympathetic=0.32, bloom_time=0.05, sustain_time=3.0, filter_env_amt=0.45,
                    amp_attack=0.001, amp_decay=1.8, amp_sustain=0.28, amp_release=1.5),
    ),
    make_preset(
        "Electro Grand",
        "Luminous",
        "Piano processed for electronic music. High HF, punchy decay, bright attack. Works against synth pads.",
        ["piano", "electronic", "bright", "processed"],
        {"brightness": 0.82, "warmth": 0.42, "movement": 0.1, "density": 0.58, "space": 0.42, "aggression": 0.7},
        oven_params(brightness=11000.0, body_resonance=0.4, hf_amount=0.82, hardness=0.8, density=0.58, temperature=0.55,
                    sympathetic=0.25, bloom_time=0.0, sustain_time=2.0, filter_env_amt=0.6,
                    amp_attack=0.001, amp_decay=1.5, amp_sustain=0.22, amp_release=1.2),
    ),
    make_preset(
        "Star Strike",
        "Luminous",
        "The piano as celestial object. Extreme brightness, minimal body, sympathetic shimmer like a star field.",
        ["piano", "bright", "star", "shimmer"],
        {"brightness": 0.95, "warmth": 0.28, "movement": 0.28, "density": 0.32, "space": 0.72, "aggression": 0.62},
        oven_params(brightness=15000.0, body_resonance=0.22, hf_amount=0.95, hardness=0.78, density=0.32, temperature=0.6,
                    sympathetic=0.65, bloom_time=0.12, sustain_time=4.5, filter_env_amt=0.6,
                    amp_attack=0.001, amp_decay=2.5, amp_sustain=0.18, amp_release=3.0),
    ),
    make_preset(
        "Crystal Attack",
        "Luminous",
        "The transient is pure crystal — hard, bright, instant. The sustain is almost inaudible by comparison.",
        ["piano", "crystal", "attack", "bright"],
        {"brightness": 0.9, "warmth": 0.32, "movement": 0.08, "density": 0.42, "space": 0.38, "aggression": 0.82},
        oven_params(brightness=14000.0, body_resonance=0.28, hf_amount=0.92, hardness=0.95, density=0.42, temperature=0.58,
                    sympathetic=0.18, bloom_time=0.0, sustain_time=1.2, filter_env_amt=0.72,
                    amp_attack=0.001, amp_decay=0.8, amp_sustain=0.12, amp_release=0.8),
    ),
]

# ===========================  KINETIC (10)  ===================================

PRESETS += [
    make_preset(
        "Forge Strike",
        "Kinetic",
        "Maximum hardness, minimum bloom, short sustain. A hammer falling on iron. Percussive and immediate.",
        ["piano", "percussive", "attack", "kinetic"],
        {"brightness": 0.65, "warmth": 0.52, "movement": 0.08, "density": 0.75, "space": 0.3, "aggression": 0.9},
        oven_params(brightness=6000.0, body_resonance=0.6, hf_amount=0.7, hardness=0.98, density=0.75, temperature=0.55,
                    sympathetic=0.2, bloom_time=0.0, sustain_time=1.5, filter_env_amt=0.65,
                    amp_attack=0.001, amp_decay=0.8, amp_sustain=0.15, amp_release=0.6),
    ),
    make_preset(
        "Kinetic Grand",
        "Kinetic",
        "Full concert piano velocity with short decay. Forte keys with staccato intent. Every note a decision.",
        ["piano", "forte", "staccato", "kinetic"],
        {"brightness": 0.6, "warmth": 0.55, "movement": 0.08, "density": 0.72, "space": 0.32, "aggression": 0.78},
        oven_params(brightness=5500.0, body_resonance=0.58, hf_amount=0.65, hardness=0.88, density=0.72, temperature=0.52,
                    sympathetic=0.18, bloom_time=0.0, sustain_time=1.8, filter_env_amt=0.58,
                    amp_attack=0.001, amp_decay=1.0, amp_sustain=0.15, amp_release=0.7),
    ),
    make_preset(
        "Piano Clang",
        "Kinetic",
        "The metallic clang of cast iron at high hardness. Piano-derived but percussive. Works as a rhythmic element.",
        ["piano", "clang", "metal", "rhythm"],
        {"brightness": 0.7, "warmth": 0.45, "movement": 0.1, "density": 0.68, "space": 0.35, "aggression": 0.88},
        oven_params(brightness=7000.0, body_resonance=0.52, hf_amount=0.75, hardness=0.95, density=0.68, temperature=0.6,
                    sympathetic=0.22, bloom_time=0.0, sustain_time=1.2, filter_env_amt=0.65,
                    amp_attack=0.001, amp_decay=0.7, amp_sustain=0.12, amp_release=0.5),
    ),
    make_preset(
        "Short Sustain",
        "Kinetic",
        "Pedal off. Every note dies immediately. Crisp, rhythmic, articulate. Like a piano sampler set to minimum decay.",
        ["piano", "staccato", "short", "dry"],
        {"brightness": 0.55, "warmth": 0.55, "movement": 0.05, "density": 0.65, "space": 0.22, "aggression": 0.55},
        oven_params(brightness=4500.0, body_resonance=0.55, hf_amount=0.55, hardness=0.65, density=0.65, temperature=0.48,
                    sympathetic=0.15, bloom_time=0.0, sustain_time=0.7, filter_env_amt=0.45,
                    amp_attack=0.001, amp_decay=0.5, amp_sustain=0.1, amp_release=0.3),
    ),
    make_preset(
        "Hot Hammer",
        "Kinetic",
        "Maximum temperature, maximum hardness. The hammer is hot from the forge. Immediate and slightly sharp.",
        ["piano", "hammer", "hot", "forge"],
        {"brightness": 0.68, "warmth": 0.5, "movement": 0.18, "density": 0.72, "space": 0.32, "aggression": 0.92},
        oven_params(brightness=7500.0, body_resonance=0.58, hf_amount=0.72, hardness=0.98, density=0.72, temperature=1.0,
                    sympathetic=0.18, bloom_time=0.0, sustain_time=1.5, filter_env_amt=0.65,
                    amp_attack=0.001, amp_decay=0.9, amp_sustain=0.15, amp_release=0.7),
    ),
    make_preset(
        "Rhythmic Iron",
        "Kinetic",
        "Rhythm section piano. Short notes, mid attack, high body resonance. For chop patterns and syncopation.",
        ["piano", "rhythm", "chop", "body"],
        {"brightness": 0.55, "warmth": 0.62, "movement": 0.1, "density": 0.78, "space": 0.3, "aggression": 0.65},
        oven_params(brightness=4500.0, body_resonance=0.78, hf_amount=0.58, hardness=0.75, density=0.78, temperature=0.52,
                    sympathetic=0.18, bloom_time=0.0, sustain_time=1.2, filter_env_amt=0.5,
                    amp_attack=0.001, amp_decay=0.8, amp_sustain=0.15, amp_release=0.5),
    ),
    make_preset(
        "Velocity Peak",
        "Kinetic",
        "Designed to respond maximally to velocity dynamics. High hardness and filter env let velocity fully sculpt the tone.",
        ["piano", "velocity", "dynamic", "expressive"],
        {"brightness": 0.62, "warmth": 0.55, "movement": 0.1, "density": 0.68, "space": 0.35, "aggression": 0.72},
        oven_params(brightness=6000.0, body_resonance=0.6, hf_amount=0.65, hardness=0.85, density=0.68, temperature=0.52,
                    sympathetic=0.22, bloom_time=0.0, sustain_time=2.0, filter_env_amt=0.7,
                    amp_attack=0.001, amp_decay=1.5, amp_sustain=0.2, amp_release=1.0),
    ),
    make_preset(
        "Snap Piano",
        "Kinetic",
        "The note snaps: very short sustain, high hardness, medium brightness. A whip crack in piano form.",
        ["piano", "snap", "short", "percussive"],
        {"brightness": 0.58, "warmth": 0.5, "movement": 0.06, "density": 0.65, "space": 0.25, "aggression": 0.82},
        oven_params(brightness=5000.0, body_resonance=0.52, hf_amount=0.65, hardness=0.92, density=0.65, temperature=0.5,
                    sympathetic=0.12, bloom_time=0.0, sustain_time=0.8, filter_env_amt=0.6,
                    amp_attack=0.001, amp_decay=0.5, amp_sustain=0.1, amp_release=0.35),
    ),
    make_preset(
        "Impact Key",
        "Kinetic",
        "The physical impact of the hammer is the sound. Very high hardness, short sustain, pronounced HF transient.",
        ["piano", "impact", "attack", "percussive"],
        {"brightness": 0.7, "warmth": 0.45, "movement": 0.08, "density": 0.7, "space": 0.28, "aggression": 0.9},
        oven_params(brightness=8000.0, body_resonance=0.5, hf_amount=0.78, hardness=0.96, density=0.7, temperature=0.55,
                    sympathetic=0.15, bloom_time=0.0, sustain_time=1.0, filter_env_amt=0.68,
                    amp_attack=0.001, amp_decay=0.6, amp_sustain=0.1, amp_release=0.4),
    ),
    make_preset(
        "Iron Drum",
        "Kinetic",
        "The piano as percussion instrument. Short decay, high hardness, maximum body resonance. Pitch is secondary.",
        ["piano", "drum", "percussion", "iron"],
        {"brightness": 0.58, "warmth": 0.58, "movement": 0.08, "density": 0.85, "space": 0.28, "aggression": 0.85},
        oven_params(brightness=5000.0, body_resonance=0.88, hf_amount=0.68, hardness=0.95, density=0.85, temperature=0.58,
                    sympathetic=0.15, bloom_time=0.0, sustain_time=0.8, filter_env_amt=0.6,
                    amp_attack=0.001, amp_decay=0.5, amp_sustain=0.08, amp_release=0.3),
    ),
]

# ===========================  ORGANIC (8)  ====================================

PRESETS += [
    make_preset(
        "Wooden Body",
        "Organic",
        "The wooden hammer and body resonance dominate. Low HF fill, high body resonance, warm density. A piano that grew from a forest.",
        ["piano", "wooden", "body", "warm"],
        {"brightness": 0.38, "warmth": 0.82, "movement": 0.15, "density": 0.82, "space": 0.45, "aggression": 0.2},
        oven_params(brightness=2500.0, body_resonance=0.92, hf_amount=0.25, hardness=0.38, density=0.82, temperature=0.48,
                    sympathetic=0.35, bloom_time=0.05, sustain_time=4.0, filter_env_amt=0.28,
                    amp_attack=0.002, amp_decay=2.8, amp_sustain=0.38, amp_release=2.2),
    ),
    make_preset(
        "Oak Resonance",
        "Organic",
        "Oak-paneled room acoustic. High body resonance, warm temperature, slow LFO drift. Living wood vibrating.",
        ["piano", "oak", "wood", "resonant"],
        {"brightness": 0.35, "warmth": 0.85, "movement": 0.2, "density": 0.78, "space": 0.48, "aggression": 0.18},
        oven_params(brightness=2200.0, body_resonance=0.88, hf_amount=0.22, hardness=0.32, density=0.78, temperature=0.55,
                    sympathetic=0.42, bloom_time=0.08, sustain_time=4.5, filter_env_amt=0.25,
                    amp_attack=0.003, amp_decay=3.2, amp_sustain=0.4, amp_release=2.5,
                    lfo1_rate=0.08, lfo1_depth=0.05),
    ),
    make_preset(
        "Living Iron",
        "Organic",
        "Cast iron as organic material. The thermal expansion creates a living, breathing quality.",
        ["piano", "organic", "thermal", "living"],
        {"brightness": 0.45, "warmth": 0.78, "movement": 0.28, "density": 0.75, "space": 0.42, "aggression": 0.22},
        oven_params(brightness=3000.0, body_resonance=0.82, hf_amount=0.38, hardness=0.4, density=0.75, temperature=0.72,
                    sympathetic=0.45, bloom_time=0.12, sustain_time=4.5, filter_env_amt=0.32,
                    amp_attack=0.002, amp_decay=3.0, amp_sustain=0.38, amp_release=2.5,
                    lfo1_rate=0.1, lfo1_depth=0.06),
    ),
    make_preset(
        "Forest Floor",
        "Organic",
        "Deep body resonance like old-growth forest. Low brightness, dense, warm. Rooted.",
        ["piano", "forest", "deep", "warm"],
        {"brightness": 0.28, "warmth": 0.85, "movement": 0.15, "density": 0.88, "space": 0.42, "aggression": 0.18},
        oven_params(brightness=1800.0, body_resonance=0.9, hf_amount=0.18, hardness=0.35, density=0.88, temperature=0.52,
                    sympathetic=0.38, bloom_time=0.1, sustain_time=5.0, filter_env_amt=0.22,
                    amp_attack=0.003, amp_decay=3.5, amp_sustain=0.42, amp_release=3.0),
    ),
    make_preset(
        "Grain Touch",
        "Organic",
        "High body resonance reveals the grain of the instrument. Each note has a woody texture before the tone.",
        ["piano", "grain", "texture", "wood"],
        {"brightness": 0.42, "warmth": 0.75, "movement": 0.15, "density": 0.8, "space": 0.38, "aggression": 0.32},
        oven_params(brightness=2800.0, body_resonance=0.85, hf_amount=0.35, hardness=0.5, density=0.8, temperature=0.5,
                    sympathetic=0.32, bloom_time=0.05, sustain_time=3.5, filter_env_amt=0.35,
                    amp_attack=0.002, amp_decay=2.5, amp_sustain=0.35, amp_release=2.0),
    ),
    make_preset(
        "Moss and Iron",
        "Organic",
        "An old iron instrument left in the forest. High body resonance, medium temperature, organic drift.",
        ["piano", "old", "iron", "organic"],
        {"brightness": 0.35, "warmth": 0.82, "movement": 0.32, "density": 0.82, "space": 0.45, "aggression": 0.2},
        oven_params(brightness=2200.0, body_resonance=0.88, hf_amount=0.28, hardness=0.38, density=0.82, temperature=0.62,
                    sympathetic=0.45, bloom_time=0.15, sustain_time=5.0, filter_env_amt=0.28,
                    amp_attack=0.003, amp_decay=3.5, amp_sustain=0.4, amp_release=3.0,
                    lfo1_rate=0.06, lfo1_depth=0.07, lfo1_shape=0),
    ),
    make_preset(
        "Rustic Resonance",
        "Organic",
        "Rustic country piano. High body, warm temperature, medium hardness. Aged and honest.",
        ["piano", "rustic", "country", "aged"],
        {"brightness": 0.4, "warmth": 0.8, "movement": 0.18, "density": 0.78, "space": 0.38, "aggression": 0.28},
        oven_params(brightness=2600.0, body_resonance=0.85, hf_amount=0.32, hardness=0.48, density=0.78, temperature=0.58,
                    sympathetic=0.32, bloom_time=0.08, sustain_time=3.5, filter_env_amt=0.32,
                    amp_attack=0.002, amp_decay=2.5, amp_sustain=0.35, amp_release=2.0),
    ),
    make_preset(
        "Earth Tone",
        "Organic",
        "The piano as earth. Dense, low, natural. No pretense of polish — just material resonance.",
        ["piano", "earth", "natural", "material"],
        {"brightness": 0.3, "warmth": 0.88, "movement": 0.12, "density": 0.9, "space": 0.35, "aggression": 0.25},
        oven_params(brightness=1800.0, body_resonance=0.92, hf_amount=0.2, hardness=0.45, density=0.9, temperature=0.5,
                    sympathetic=0.35, bloom_time=0.08, sustain_time=4.5, filter_env_amt=0.25,
                    amp_attack=0.002, amp_decay=3.2, amp_sustain=0.42, amp_release=2.8),
    ),
    make_preset(
        "Root Resonance",
        "Organic",
        "The foundational resonance of wood, iron, and air. Each material contributing its natural voice. Understated and honest.",
        ["piano", "root", "resonant", "organic"],
        {"brightness": 0.38, "warmth": 0.85, "movement": 0.15, "density": 0.82, "space": 0.42, "aggression": 0.18},
        oven_params(brightness=2400.0, body_resonance=0.88, hf_amount=0.25, hardness=0.4, density=0.82, temperature=0.52,
                    sympathetic=0.38, bloom_time=0.07, sustain_time=4.2, filter_env_amt=0.26,
                    amp_attack=0.003, amp_decay=3.0, amp_sustain=0.4, amp_release=2.4),
    ),
]

# ===========================  CRYSTALLINE (6)  ================================

PRESETS += [
    make_preset(
        "Prepared Iron",
        "Crystalline",
        "John Cage prepared piano via cast iron. Objects placed on the strings alter the modal resonator timbre. Metallic and pure.",
        ["piano", "prepared", "john cage", "metallic"],
        {"brightness": 0.72, "warmth": 0.35, "movement": 0.25, "density": 0.5, "space": 0.6, "aggression": 0.55},
        oven_params(brightness=9000.0, body_resonance=0.32, hf_amount=0.85, hardness=0.75, density=0.5, temperature=0.65,
                    sympathetic=0.55, bloom_time=0.15, sustain_time=5.0, filter_env_amt=0.55,
                    amp_attack=0.001, amp_decay=3.0, amp_sustain=0.2, amp_release=3.0),
    ),
    make_preset(
        "Metal Tines",
        "Crystalline",
        "The metallic ping of tines. High brightness, low density, short sustain. Each note is crystalline and pure.",
        ["piano", "metal", "tine", "crystal"],
        {"brightness": 0.82, "warmth": 0.32, "movement": 0.15, "density": 0.38, "space": 0.52, "aggression": 0.58},
        oven_params(brightness=12000.0, body_resonance=0.25, hf_amount=0.88, hardness=0.78, density=0.38, temperature=0.6,
                    sympathetic=0.38, bloom_time=0.05, sustain_time=3.0, filter_env_amt=0.55,
                    amp_attack=0.001, amp_decay=2.0, amp_sustain=0.15, amp_release=2.0),
    ),
    make_preset(
        "Ice Cathedral",
        "Crystalline",
        "Crystalline ice acoustics. Very high brightness and HF fill, low body. Cold and clear.",
        ["piano", "ice", "cold", "bright"],
        {"brightness": 0.88, "warmth": 0.22, "movement": 0.18, "density": 0.35, "space": 0.68, "aggression": 0.52},
        oven_params(brightness=14000.0, body_resonance=0.2, hf_amount=0.92, hardness=0.72, density=0.35, temperature=0.28,
                    sympathetic=0.52, bloom_time=0.1, sustain_time=4.5, filter_env_amt=0.55,
                    amp_attack=0.001, amp_decay=2.8, amp_sustain=0.18, amp_release=3.0),
    ),
    make_preset(
        "Crystal Modal",
        "Crystalline",
        "The 16 modal resonators ringing as crystal bowls. Very high brightness, maximum HF, high sympathetic.",
        ["piano", "crystal", "modal", "pure"],
        {"brightness": 0.85, "warmth": 0.28, "movement": 0.28, "density": 0.38, "space": 0.72, "aggression": 0.5},
        oven_params(brightness=13000.0, body_resonance=0.22, hf_amount=0.9, hardness=0.68, density=0.38, temperature=0.55,
                    sympathetic=0.72, bloom_time=0.18, sustain_time=6.0, filter_env_amt=0.55,
                    amp_attack=0.001, amp_decay=4.0, amp_sustain=0.18, amp_release=4.0),
    ),
    make_preset(
        "Sine Purity",
        "Crystalline",
        "Maximum brightness and purity. The modal resonators at their highest harmonic register. Pure sine-like sustain.",
        ["piano", "sine", "pure", "crystal"],
        {"brightness": 0.92, "warmth": 0.25, "movement": 0.12, "density": 0.32, "space": 0.55, "aggression": 0.45},
        oven_params(brightness=15000.0, body_resonance=0.18, hf_amount=0.85, hardness=0.62, density=0.32, temperature=0.52,
                    sympathetic=0.42, bloom_time=0.08, sustain_time=4.0, filter_env_amt=0.48,
                    amp_attack=0.001, amp_decay=2.5, amp_sustain=0.18, amp_release=3.5),
    ),
    make_preset(
        "Glass Hammer",
        "Crystalline",
        "Like striking crystal glass with a glass hammer. Pure, brittle, resonant. Each note vibrates at a precise frequency.",
        ["piano", "glass", "crystal", "pure"],
        {"brightness": 0.88, "warmth": 0.28, "movement": 0.22, "density": 0.35, "space": 0.62, "aggression": 0.65},
        oven_params(brightness=13500.0, body_resonance=0.2, hf_amount=0.9, hardness=0.82, density=0.35, temperature=0.55,
                    sympathetic=0.58, bloom_time=0.12, sustain_time=4.5, filter_env_amt=0.6,
                    amp_attack=0.001, amp_decay=2.8, amp_sustain=0.16, amp_release=3.0),
    ),
]

# ---------------------------------------------------------------------------
# COUNT CHECK
# ---------------------------------------------------------------------------

def main():
    counts = {}
    for p in PRESETS:
        m = p["mood"]
        counts[m] = counts.get(m, 0) + 1

    print(f"Total presets to write: {len(PRESETS)}")
    for mood, count in sorted(counts.items()):
        print(f"  {mood}: {count}")

    # Check aggression targets (18+ at >= 0.7)
    high_agg = [p for p in PRESETS if p["dna"]["aggression"] >= 0.7]
    print(f"High-aggression (>=0.7): {len(high_agg)}")

    written = 0
    for p in PRESETS:
        path = write_preset(p)
        written += 1

    print(f"Written: {written} presets")


if __name__ == "__main__":
    main()
