#!/usr/bin/env python3
"""
generate_okeanos_presets.py
Generate 110 factory presets for the Okeanos engine (Rhodes EP physical model).
Target: bring Okeanos from 10 → 120 presets.

IMPORTANT: okan_migration is held at 0.0 pending FATHOM prefix collision fix.

Mood distribution:
  Foundation  30  (classic Rhodes)
  Organic     18  (natural, woody)
  Flux        15  (heavy tremolo)
  Luminous    12  (bright tines)
  Deep        12  (dark Rhodes)
  Kinetic     10  (percussive, short decay)
  Ethereal     8  (pad-like, long release)
  Crystalline  5  (bell-like, pure)

12+ high-aggression presets (dna.aggression >= 0.7).
"""

import json
import os
import sys

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..")
PRESETS_DIR = os.path.join(REPO_ROOT, "Presets", "XOceanus")


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def okan_params(
    warmth=0.3,
    bell=0.5,
    brightness=6000.0,
    trem_rate=4.0,
    trem_depth=0.0,
    attack=0.005,
    decay=0.8,
    sustain=0.6,
    release=0.5,
    filter_env_amt=0.4,
    migration=0.0,        # ALWAYS 0.0 — FATHOM collision pending
    stereo_width=0.5,
    bend_range=2.0,
    macro_character=0.0,
    macro_movement=0.0,
    macro_coupling=0.0,
    macro_space=0.0,
    lfo1_rate=0.5,
    lfo1_depth=0.0,
    lfo1_shape=0,
    lfo2_rate=1.0,
    lfo2_depth=0.0,
    lfo2_shape=0,
):
    return {
        "Okeanos": {
            "okan_warmth": clamp(warmth, 0.0, 1.0),
            "okan_bell": clamp(bell, 0.0, 1.0),
            "okan_brightness": clamp(brightness, 200.0, 20000.0),
            "okan_tremRate": clamp(trem_rate, 0.5, 12.0),
            "okan_tremDepth": clamp(trem_depth, 0.0, 1.0),
            "okan_attack": clamp(attack, 0.001, 0.5),
            "okan_decay": clamp(decay, 0.05, 5.0),
            "okan_sustain": clamp(sustain, 0.0, 1.0),
            "okan_release": clamp(release, 0.01, 5.0),
            "okan_filterEnvAmt": clamp(filter_env_amt, 0.0, 1.0),
            "okan_migration": 0.0,   # SAFE ZONE — never change
            "okan_stereoWidth": clamp(stereo_width, 0.0, 1.0),
            "okan_bendRange": clamp(bend_range, 1.0, 24.0),
            "okan_macroCharacter": clamp(macro_character, 0.0, 1.0),
            "okan_macroMovement": clamp(macro_movement, 0.0, 1.0),
            "okan_macroCoupling": clamp(macro_coupling, 0.0, 1.0),
            "okan_macroSpace": clamp(macro_space, 0.0, 1.0),
            "okan_lfo1Rate": clamp(lfo1_rate, 0.005, 20.0),
            "okan_lfo1Depth": clamp(lfo1_depth, 0.0, 1.0),
            "okan_lfo1Shape": int(clamp(lfo1_shape, 0, 4)),
            "okan_lfo2Rate": clamp(lfo2_rate, 0.005, 20.0),
            "okan_lfo2Depth": clamp(lfo2_depth, 0.0, 1.0),
            "okan_lfo2Shape": int(clamp(lfo2_shape, 0, 4)),
        }
    }


def make_preset(name, mood, description, tags, dna, params):
    return {
        "schema_version": 1,
        "name": name,
        "mood": mood,
        "engines": ["Okeanos"],
        "author": "XO_OX Designs",
        "version": "1.0.0",
        "description": description,
        "tags": tags,
        "macroLabels": ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        "couplingIntensity": "None",
        "tempo": None,
        "dna": dna,
        "parameters": params,
        "coupling": {"pairs": []},
        "sequencer": None,
    }


def write_preset(preset):
    mood = preset["mood"]
    name = preset["name"]
    safe_name = name.replace(" ", "_").replace("/", "-")
    dest_dir = os.path.join(PRESETS_DIR, mood, "Okeanos")
    os.makedirs(dest_dir, exist_ok=True)
    path = os.path.join(dest_dir, f"Okeanos_{safe_name}.xometa")
    with open(path, "w") as f:
        json.dump(preset, f, indent=2)
    return path


# ---------------------------------------------------------------------------
# PRESETS
# ---------------------------------------------------------------------------

PRESETS = []

# ===========================  FOUNDATION (30)  ================================

PRESETS += [
    make_preset(
        "Classic Suitcase",
        "Foundation",
        "The iconic Mark I suitcase Rhodes. Warm mid-range tines, gentle bell tone, medium stereo width. The reference point for all electric piano sounds.",
        ["rhodes", "classic", "suitcase", "mark i"],
        {"brightness": 0.55, "warmth": 0.72, "movement": 0.08, "density": 0.65, "space": 0.5, "aggression": 0.25},
        okan_params(warmth=0.35, bell=0.55, brightness=6000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.005, decay=0.9, sustain=0.65, release=0.5, filter_env_amt=0.38,
                    stereo_width=0.55),
    ),
    make_preset(
        "Midnight Suitcase",
        "Foundation",
        "3 AM session with just the lamp on. Dark tines, warm bell, medium tremolo barely ticking. The Rhodes at its most intimate.",
        ["rhodes", "midnight", "intimate", "warm"],
        {"brightness": 0.42, "warmth": 0.82, "movement": 0.2, "density": 0.65, "space": 0.48, "aggression": 0.15},
        okan_params(warmth=0.65, bell=0.45, brightness=4500.0, trem_rate=3.5, trem_depth=0.18,
                    attack=0.005, decay=0.85, sustain=0.6, release=0.55, filter_env_amt=0.3,
                    stereo_width=0.5, macro_movement=0.2),
    ),
    make_preset(
        "Jazz Club 2AM",
        "Foundation",
        "Late-night jazz club. Clean tines, medium decay, almost no tremolo. Bill Evans territory.",
        ["rhodes", "jazz", "club", "late night"],
        {"brightness": 0.52, "warmth": 0.72, "movement": 0.08, "density": 0.6, "space": 0.45, "aggression": 0.2},
        okan_params(warmth=0.35, bell=0.5, brightness=6500.0, trem_rate=4.5, trem_depth=0.05,
                    attack=0.004, decay=0.8, sustain=0.62, release=0.48, filter_env_amt=0.35,
                    stereo_width=0.45),
    ),
    make_preset(
        "Stage 73",
        "Foundation",
        "73-key stage model. Slightly brighter than the suitcase. Medium bell, tight response. Herbie on stage.",
        ["rhodes", "stage", "73 key", "live"],
        {"brightness": 0.58, "warmth": 0.65, "movement": 0.08, "density": 0.62, "space": 0.45, "aggression": 0.3},
        okan_params(warmth=0.28, bell=0.52, brightness=7000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.004, decay=0.75, sustain=0.6, release=0.45, filter_env_amt=0.38,
                    stereo_width=0.5),
    ),
    make_preset(
        "Soul Ballad",
        "Foundation",
        "Marvin Gaye era soul ballad Rhodes. Very warm, medium bell, gentle tremolo. Supportive and intimate.",
        ["rhodes", "soul", "ballad", "warm"],
        {"brightness": 0.45, "warmth": 0.8, "movement": 0.25, "density": 0.65, "space": 0.5, "aggression": 0.12},
        okan_params(warmth=0.6, bell=0.48, brightness=5000.0, trem_rate=3.8, trem_depth=0.22,
                    attack=0.005, decay=0.9, sustain=0.65, release=0.6, filter_env_amt=0.28,
                    stereo_width=0.5, macro_movement=0.25),
    ),
    make_preset(
        "Neo Soul Juice",
        "Foundation",
        "D'Angelo and J Dilla session feel. Medium warmth, pronounced bell, wide stereo. Contemporary but vintage.",
        ["rhodes", "neo-soul", "contemporary", "bell"],
        {"brightness": 0.55, "warmth": 0.7, "movement": 0.15, "density": 0.68, "space": 0.6, "aggression": 0.35},
        okan_params(warmth=0.4, bell=0.65, brightness=6500.0, trem_rate=4.0, trem_depth=0.08,
                    attack=0.004, decay=0.85, sustain=0.62, release=0.55, filter_env_amt=0.4,
                    stereo_width=0.72),
    ),
    make_preset(
        "Mellow Comp",
        "Foundation",
        "Comping tone for jazz. Not too much, not too little. Medium warmth and bell, just enough width.",
        ["rhodes", "jazz", "comp", "mellow"],
        {"brightness": 0.5, "warmth": 0.68, "movement": 0.08, "density": 0.6, "space": 0.45, "aggression": 0.2},
        okan_params(warmth=0.32, bell=0.5, brightness=6200.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.004, decay=0.78, sustain=0.6, release=0.48, filter_env_amt=0.35,
                    stereo_width=0.48),
    ),
    make_preset(
        "Tine Cathedral",
        "Foundation",
        "The tines ringing in a large hall. High stereo width, pronounced bell, long sustain. Architectural sound.",
        ["rhodes", "tine", "hall", "cathedral"],
        {"brightness": 0.58, "warmth": 0.6, "movement": 0.18, "density": 0.58, "space": 0.78, "aggression": 0.3},
        okan_params(warmth=0.3, bell=0.75, brightness=7500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.004, decay=1.2, sustain=0.58, release=0.8, filter_env_amt=0.38,
                    stereo_width=0.88, macro_space=0.4),
    ),
    make_preset(
        "Breakfast Keys",
        "Foundation",
        "Warm morning Rhodes. Cheerful and clean. Not too dark, not too bright. Ready for anything.",
        ["rhodes", "morning", "cheerful", "clean"],
        {"brightness": 0.55, "warmth": 0.7, "movement": 0.1, "density": 0.6, "space": 0.5, "aggression": 0.18},
        okan_params(warmth=0.38, bell=0.52, brightness=6800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.004, decay=0.82, sustain=0.62, release=0.5, filter_env_amt=0.35,
                    stereo_width=0.5),
    ),
    make_preset(
        "Autumn Session",
        "Foundation",
        "Autumnal warmth. Slightly warm tones, medium bell, natural decay. October in the studio.",
        ["rhodes", "autumn", "warm", "session"],
        {"brightness": 0.48, "warmth": 0.75, "movement": 0.12, "density": 0.62, "space": 0.48, "aggression": 0.15},
        okan_params(warmth=0.5, bell=0.5, brightness=5500.0, trem_rate=3.8, trem_depth=0.05,
                    attack=0.005, decay=0.88, sustain=0.62, release=0.55, filter_env_amt=0.32,
                    stereo_width=0.5),
    ),
    make_preset(
        "Blue Note",
        "Foundation",
        "Blue Note Records era acoustic. Very close-mic feel. Dense, warm, slightly compressed.",
        ["rhodes", "blue note", "jazz", "vintage"],
        {"brightness": 0.5, "warmth": 0.75, "movement": 0.08, "density": 0.72, "space": 0.38, "aggression": 0.25},
        okan_params(warmth=0.55, bell=0.48, brightness=5800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.004, decay=0.75, sustain=0.65, release=0.45, filter_env_amt=0.35,
                    stereo_width=0.38),
    ),
    make_preset(
        "Rhodes Standard",
        "Foundation",
        "The factory default voice refined. Every parameter at its sweetest point. The reference standard.",
        ["rhodes", "standard", "default", "clean"],
        {"brightness": 0.52, "warmth": 0.68, "movement": 0.08, "density": 0.62, "space": 0.5, "aggression": 0.2},
        okan_params(warmth=0.3, bell=0.5, brightness=6000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.005, decay=0.8, sustain=0.6, release=0.5, filter_env_amt=0.4,
                    stereo_width=0.5),
    ),
    make_preset(
        "Headphones Mix",
        "Foundation",
        "Wide stereo for headphones. Full spatial separation. Maximum stereo width makes the tines float left and right.",
        ["rhodes", "stereo", "headphones", "wide"],
        {"brightness": 0.52, "warmth": 0.68, "movement": 0.12, "density": 0.6, "space": 0.88, "aggression": 0.2},
        okan_params(warmth=0.32, bell=0.52, brightness=6200.0, trem_rate=4.0, trem_depth=0.1,
                    attack=0.004, decay=0.85, sustain=0.62, release=0.55, filter_env_amt=0.38,
                    stereo_width=0.95, macro_space=0.5),
    ),
    make_preset(
        "Philly Soul",
        "Foundation",
        "Philadelphia International soul. Lush tines, medium bell, soft tremolo. Gamble and Huff production.",
        ["rhodes", "soul", "philly", "lush"],
        {"brightness": 0.5, "warmth": 0.75, "movement": 0.2, "density": 0.68, "space": 0.55, "aggression": 0.18},
        okan_params(warmth=0.52, bell=0.55, brightness=5800.0, trem_rate=3.5, trem_depth=0.2,
                    attack=0.005, decay=0.95, sustain=0.65, release=0.6, filter_env_amt=0.32,
                    stereo_width=0.6, macro_movement=0.22),
    ),
    make_preset(
        "Garage Band",
        "Foundation",
        "Rehearsal space Rhodes. Slightly gritty, medium bell. Real and unpolished.",
        ["rhodes", "garage", "gritty", "band"],
        {"brightness": 0.52, "warmth": 0.65, "movement": 0.1, "density": 0.68, "space": 0.42, "aggression": 0.38},
        okan_params(warmth=0.38, bell=0.52, brightness=6500.0, trem_rate=4.0, trem_depth=0.04,
                    attack=0.004, decay=0.75, sustain=0.58, release=0.45, filter_env_amt=0.42,
                    stereo_width=0.42),
    ),
    make_preset(
        "Velvet Tine",
        "Foundation",
        "The softest possible Rhodes tone. Very warm, gentle bell, cushioned attack. Like brushed velvet.",
        ["rhodes", "soft", "velvet", "gentle"],
        {"brightness": 0.42, "warmth": 0.85, "movement": 0.1, "density": 0.62, "space": 0.5, "aggression": 0.08},
        okan_params(warmth=0.72, bell=0.42, brightness=4500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.008, decay=1.0, sustain=0.68, release=0.65, filter_env_amt=0.25,
                    stereo_width=0.48),
    ),
    make_preset(
        "Club Set",
        "Foundation",
        "Club-stage presence. Slightly brighter, punchy, sits in the mix. Works over drums and bass without fighting.",
        ["rhodes", "club", "live", "punchy"],
        {"brightness": 0.6, "warmth": 0.6, "movement": 0.12, "density": 0.65, "space": 0.48, "aggression": 0.42},
        okan_params(warmth=0.25, bell=0.55, brightness=7500.0, trem_rate=4.0, trem_depth=0.06,
                    attack=0.004, decay=0.72, sustain=0.58, release=0.42, filter_env_amt=0.45,
                    stereo_width=0.52),
    ),
    make_preset(
        "Chord Swell",
        "Foundation",
        "Slow attack chords. Slightly swelling onset, long sustain. For pad-like chordal playing with the Rhodes.",
        ["rhodes", "chord", "swell", "pad"],
        {"brightness": 0.5, "warmth": 0.72, "movement": 0.15, "density": 0.62, "space": 0.55, "aggression": 0.12},
        okan_params(warmth=0.45, bell=0.5, brightness=5800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.02, decay=1.1, sustain=0.65, release=0.8, filter_env_amt=0.3,
                    stereo_width=0.6),
    ),
    make_preset(
        "Funk Comp",
        "Foundation",
        "Funk comping. Slightly higher bell, shorter decay, clean. For syncopated patterns.",
        ["rhodes", "funk", "comp", "clean"],
        {"brightness": 0.58, "warmth": 0.62, "movement": 0.1, "density": 0.62, "space": 0.45, "aggression": 0.48},
        okan_params(warmth=0.28, bell=0.62, brightness=7200.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.004, decay=0.65, sustain=0.58, release=0.4, filter_env_amt=0.42,
                    stereo_width=0.48),
    ),
    make_preset(
        "Rhodes Ballad",
        "Foundation",
        "Slow ballad tone. Warm, long decay, gentle bell, minimal movement. For slow melodies.",
        ["rhodes", "ballad", "slow", "gentle"],
        {"brightness": 0.45, "warmth": 0.78, "movement": 0.08, "density": 0.62, "space": 0.5, "aggression": 0.1},
        okan_params(warmth=0.55, bell=0.45, brightness=5200.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.006, decay=1.0, sustain=0.65, release=0.7, filter_env_amt=0.28,
                    stereo_width=0.5),
    ),
    make_preset(
        "Gospel Keys",
        "Foundation",
        "Gospel piano style on the Rhodes. Bright bell, high warmth, full stereo. Call-and-response voicings.",
        ["rhodes", "gospel", "church", "bell"],
        {"brightness": 0.62, "warmth": 0.72, "movement": 0.15, "density": 0.68, "space": 0.58, "aggression": 0.42},
        okan_params(warmth=0.45, bell=0.72, brightness=7500.0, trem_rate=4.0, trem_depth=0.1,
                    attack=0.004, decay=0.85, sustain=0.65, release=0.55, filter_env_amt=0.42,
                    stereo_width=0.62),
    ),
    make_preset(
        "Island Session",
        "Foundation",
        "Tropical session feel. Light, warm, breezy. For pop and acoustic contexts.",
        ["rhodes", "tropical", "light", "pop"],
        {"brightness": 0.55, "warmth": 0.72, "movement": 0.12, "density": 0.58, "space": 0.5, "aggression": 0.18},
        okan_params(warmth=0.42, bell=0.52, brightness=6500.0, trem_rate=4.2, trem_depth=0.05,
                    attack=0.004, decay=0.82, sustain=0.6, release=0.5, filter_env_amt=0.35,
                    stereo_width=0.52),
    ),
    make_preset(
        "Studio A",
        "Foundation",
        "World-class studio A grade. Perfect balance of warmth and bell. The tone that won a thousand records.",
        ["rhodes", "studio", "professional", "balanced"],
        {"brightness": 0.55, "warmth": 0.7, "movement": 0.08, "density": 0.65, "space": 0.5, "aggression": 0.28},
        okan_params(warmth=0.35, bell=0.55, brightness=6500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.004, decay=0.85, sustain=0.62, release=0.52, filter_env_amt=0.38,
                    stereo_width=0.55),
    ),
    make_preset(
        "Floating Keys",
        "Foundation",
        "Weightless Rhodes. Medium bell, high stereo width, just enough warmth. Notes float in the mix.",
        ["rhodes", "floating", "wide", "light"],
        {"brightness": 0.55, "warmth": 0.65, "movement": 0.12, "density": 0.55, "space": 0.72, "aggression": 0.2},
        okan_params(warmth=0.3, bell=0.55, brightness=6500.0, trem_rate=4.0, trem_depth=0.08,
                    attack=0.004, decay=0.88, sustain=0.6, release=0.55, filter_env_amt=0.35,
                    stereo_width=0.8),
    ),
    make_preset(
        "Sixties Session",
        "Foundation",
        "Late 1960s soul era. Pre-CBS warmth, medium bell. The sound that launched a genre.",
        ["rhodes", "1960s", "soul", "vintage"],
        {"brightness": 0.48, "warmth": 0.78, "movement": 0.12, "density": 0.68, "space": 0.45, "aggression": 0.2},
        okan_params(warmth=0.55, bell=0.5, brightness=5500.0, trem_rate=3.8, trem_depth=0.1,
                    attack=0.005, decay=0.88, sustain=0.65, release=0.55, filter_env_amt=0.32,
                    stereo_width=0.45),
    ),
    make_preset(
        "Rhodes Duo",
        "Foundation",
        "Two-piano session blend. Wider stereo, complementary tones. For layered arrangements.",
        ["rhodes", "wide", "layered", "duo"],
        {"brightness": 0.52, "warmth": 0.7, "movement": 0.1, "density": 0.6, "space": 0.75, "aggression": 0.2},
        okan_params(warmth=0.38, bell=0.52, brightness=6200.0, trem_rate=4.0, trem_depth=0.06,
                    attack=0.004, decay=0.85, sustain=0.62, release=0.52, filter_env_amt=0.36,
                    stereo_width=0.82),
    ),
    make_preset(
        "Seventies Groove",
        "Foundation",
        "1970s groove session. Warm, punchy, with that decade's specific tone. Herbie, Stevie, Rhodes.",
        ["rhodes", "1970s", "groove", "soul"],
        {"brightness": 0.52, "warmth": 0.75, "movement": 0.15, "density": 0.68, "space": 0.5, "aggression": 0.38},
        okan_params(warmth=0.45, bell=0.55, brightness=6000.0, trem_rate=3.8, trem_depth=0.12,
                    attack=0.004, decay=0.82, sustain=0.62, release=0.5, filter_env_amt=0.38,
                    stereo_width=0.55),
    ),
    make_preset(
        "Electric Soul",
        "Foundation",
        "The Rhodes as the soul of electric music. Full tone, balanced warmth and brightness, ready for everything.",
        ["rhodes", "soul", "electric", "full"],
        {"brightness": 0.55, "warmth": 0.72, "movement": 0.12, "density": 0.65, "space": 0.52, "aggression": 0.3},
        okan_params(warmth=0.38, bell=0.58, brightness=6500.0, trem_rate=4.0, trem_depth=0.06,
                    attack=0.004, decay=0.85, sustain=0.62, release=0.52, filter_env_amt=0.4,
                    stereo_width=0.55),
    ),
    make_preset(
        "Night Shift",
        "Foundation",
        "Recording at 2 AM. Slightly warmer than studio noon. The tines know the hour.",
        ["rhodes", "night", "late", "warm"],
        {"brightness": 0.45, "warmth": 0.8, "movement": 0.1, "density": 0.65, "space": 0.48, "aggression": 0.15},
        okan_params(warmth=0.62, bell=0.46, brightness=5000.0, trem_rate=3.8, trem_depth=0.04,
                    attack=0.005, decay=0.9, sustain=0.65, release=0.58, filter_env_amt=0.3,
                    stereo_width=0.5),
    ),
]

# ===========================  ORGANIC (18)  ===================================

PRESETS += [
    make_preset(
        "Worn Felt",
        "Organic",
        "The felt-wrapped tines of an old Rhodes. Very warm, soft attack, rounded. This instrument has been played for decades.",
        ["rhodes", "worn", "felt", "vintage"],
        {"brightness": 0.38, "warmth": 0.88, "movement": 0.12, "density": 0.68, "space": 0.45, "aggression": 0.12},
        okan_params(warmth=0.75, bell=0.35, brightness=4200.0, trem_rate=3.8, trem_depth=0.04,
                    attack=0.008, decay=1.0, sustain=0.68, release=0.65, filter_env_amt=0.22,
                    stereo_width=0.45),
    ),
    make_preset(
        "Oak Tine",
        "Foundation",
        "Woodier tone quality. High warmth, low bell emphasis. Like a Rhodes made from a different material.",
        ["rhodes", "wood", "organic", "warm"],
        {"brightness": 0.4, "warmth": 0.85, "movement": 0.1, "density": 0.72, "space": 0.45, "aggression": 0.18},
        okan_params(warmth=0.78, bell=0.3, brightness=4500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.006, decay=0.95, sustain=0.68, release=0.6, filter_env_amt=0.25,
                    stereo_width=0.45),
    ),
    make_preset(
        "Mellow Body",
        "Organic",
        "High warmth, minimal bell, low filter envelope. The body of the instrument is the sound. Acoustic heritage.",
        ["rhodes", "body", "warm", "acoustic"],
        {"brightness": 0.35, "warmth": 0.88, "movement": 0.08, "density": 0.72, "space": 0.42, "aggression": 0.12},
        okan_params(warmth=0.82, bell=0.25, brightness=4000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.007, decay=1.0, sustain=0.7, release=0.65, filter_env_amt=0.2,
                    stereo_width=0.42),
    ),
    make_preset(
        "Tine Breath",
        "Organic",
        "The tines breathing. Slight LFO1 movement at very low depth. Like the natural resonance of a room.",
        ["rhodes", "breath", "organic", "lfo"],
        {"brightness": 0.5, "warmth": 0.75, "movement": 0.25, "density": 0.62, "space": 0.5, "aggression": 0.12},
        okan_params(warmth=0.5, bell=0.48, brightness=5800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.005, decay=0.9, sustain=0.65, release=0.58, filter_env_amt=0.32,
                    stereo_width=0.5, lfo1_rate=0.15, lfo1_depth=0.06, lfo1_shape=0),
    ),
    make_preset(
        "Aged Suitcase",
        "Organic",
        "A 50-year-old suitcase Rhodes. High warmth, slightly degraded bell, natural imperfection. Perfect in its age.",
        ["rhodes", "aged", "vintage", "character"],
        {"brightness": 0.42, "warmth": 0.85, "movement": 0.18, "density": 0.7, "space": 0.45, "aggression": 0.15},
        okan_params(warmth=0.72, bell=0.38, brightness=4500.0, trem_rate=3.8, trem_depth=0.08,
                    attack=0.007, decay=0.95, sustain=0.65, release=0.62, filter_env_amt=0.25,
                    stereo_width=0.48, lfo1_rate=0.1, lfo1_depth=0.04),
    ),
    make_preset(
        "Natural Decay",
        "Organic",
        "The natural physical decay of the tines without processing. Pure, acoustic, physical.",
        ["rhodes", "natural", "acoustic", "decay"],
        {"brightness": 0.5, "warmth": 0.72, "movement": 0.08, "density": 0.65, "space": 0.45, "aggression": 0.18},
        okan_params(warmth=0.42, bell=0.48, brightness=5800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.004, decay=0.88, sustain=0.62, release=0.55, filter_env_amt=0.33,
                    stereo_width=0.45),
    ),
    make_preset(
        "Earth Rhodes",
        "Organic",
        "Grounded, earthy, natural. Low brightness, high warmth, minimal bell. The Rhodes as a natural object.",
        ["rhodes", "earth", "natural", "ground"],
        {"brightness": 0.35, "warmth": 0.88, "movement": 0.1, "density": 0.75, "space": 0.4, "aggression": 0.15},
        okan_params(warmth=0.82, bell=0.28, brightness=4000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.007, decay=1.0, sustain=0.7, release=0.65, filter_env_amt=0.22,
                    stereo_width=0.42),
    ),
    make_preset(
        "Cotton Soft",
        "Organic",
        "Cotton-damped tines. Very soft attack, high warmth, very low bell. Hushed and organic.",
        ["rhodes", "soft", "cotton", "muted"],
        {"brightness": 0.3, "warmth": 0.9, "movement": 0.08, "density": 0.65, "space": 0.42, "aggression": 0.06},
        okan_params(warmth=0.88, bell=0.2, brightness=3500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.012, decay=1.05, sustain=0.72, release=0.72, filter_env_amt=0.18,
                    stereo_width=0.42),
    ),
    make_preset(
        "Lived In",
        "Organic",
        "An instrument that has been lived in. Slight warmth asymmetry, organic drift, character.",
        ["rhodes", "character", "vintage", "organic"],
        {"brightness": 0.45, "warmth": 0.8, "movement": 0.22, "density": 0.68, "space": 0.45, "aggression": 0.18},
        okan_params(warmth=0.62, bell=0.42, brightness=5200.0, trem_rate=3.8, trem_depth=0.07,
                    attack=0.006, decay=0.9, sustain=0.65, release=0.58, filter_env_amt=0.28,
                    stereo_width=0.48, lfo1_rate=0.08, lfo1_depth=0.04),
    ),
    make_preset(
        "Piano Body",
        "Organic",
        "The body resonance dominates. Acoustic piano DNA bleeding into the tine character.",
        ["rhodes", "piano", "body", "acoustic"],
        {"brightness": 0.42, "warmth": 0.82, "movement": 0.1, "density": 0.75, "space": 0.45, "aggression": 0.18},
        okan_params(warmth=0.72, bell=0.32, brightness=4800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.006, decay=0.95, sustain=0.68, release=0.62, filter_env_amt=0.28,
                    stereo_width=0.48),
    ),
    make_preset(
        "Mahogany Tine",
        "Organic",
        "Cabinet resonance of a mahogany Rhodes case. Warm, dense body resonance, low bell.",
        ["rhodes", "mahogany", "wood", "cabinet"],
        {"brightness": 0.38, "warmth": 0.88, "movement": 0.1, "density": 0.72, "space": 0.42, "aggression": 0.15},
        okan_params(warmth=0.78, bell=0.28, brightness=4200.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.007, decay=1.0, sustain=0.7, release=0.65, filter_env_amt=0.22,
                    stereo_width=0.42),
    ),
    make_preset(
        "Summer Rhodes",
        "Organic",
        "A warm summer day studio session. Light, natural, airy warmth. Organic and easygoing.",
        ["rhodes", "summer", "warm", "natural"],
        {"brightness": 0.52, "warmth": 0.75, "movement": 0.12, "density": 0.62, "space": 0.5, "aggression": 0.15},
        okan_params(warmth=0.52, bell=0.48, brightness=6000.0, trem_rate=4.0, trem_depth=0.04,
                    attack=0.005, decay=0.88, sustain=0.65, release=0.55, filter_env_amt=0.32,
                    stereo_width=0.5),
    ),
    make_preset(
        "Mineral Tine",
        "Organic",
        "Like tines made from compressed earth and mineral. Dense warmth, very low bell, organic texture.",
        ["rhodes", "mineral", "dense", "organic"],
        {"brightness": 0.32, "warmth": 0.88, "movement": 0.08, "density": 0.8, "space": 0.38, "aggression": 0.15},
        okan_params(warmth=0.85, bell=0.22, brightness=3800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.008, decay=1.05, sustain=0.72, release=0.7, filter_env_amt=0.2,
                    stereo_width=0.38),
    ),
    make_preset(
        "Patina Keys",
        "Organic",
        "Patinated, aged tines. The bell tone has developed a natural oxidation. Organic aging.",
        ["rhodes", "patina", "aged", "organic"],
        {"brightness": 0.45, "warmth": 0.78, "movement": 0.18, "density": 0.68, "space": 0.45, "aggression": 0.2},
        okan_params(warmth=0.65, bell=0.4, brightness=5000.0, trem_rate=3.8, trem_depth=0.08,
                    attack=0.006, decay=0.9, sustain=0.65, release=0.6, filter_env_amt=0.28,
                    stereo_width=0.45, lfo1_rate=0.07, lfo1_depth=0.04),
    ),
    make_preset(
        "Root Tone",
        "Organic",
        "Root-level warmth. Maximum warmth, minimal bell, minimal stereo. The tone before processing.",
        ["rhodes", "root", "pure", "organic"],
        {"brightness": 0.38, "warmth": 0.92, "movement": 0.06, "density": 0.7, "space": 0.35, "aggression": 0.1},
        okan_params(warmth=0.9, bell=0.18, brightness=4000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.008, decay=1.0, sustain=0.7, release=0.65, filter_env_amt=0.18,
                    stereo_width=0.35),
    ),
    make_preset(
        "Hand Wound",
        "Organic",
        "Hand-wound tines with natural variation. High warmth, medium bell, organic movement from the slight imperfection.",
        ["rhodes", "hand-wound", "organic", "natural"],
        {"brightness": 0.48, "warmth": 0.8, "movement": 0.2, "density": 0.68, "space": 0.48, "aggression": 0.18},
        okan_params(warmth=0.65, bell=0.45, brightness=5500.0, trem_rate=4.0, trem_depth=0.04,
                    attack=0.005, decay=0.9, sustain=0.65, release=0.58, filter_env_amt=0.3,
                    stereo_width=0.5, lfo1_rate=0.12, lfo1_depth=0.05),
    ),
    make_preset(
        "Linen Keys",
        "Organic",
        "Linen-damped soft quality. Very warm, rounded, soft. The damper felt is thick and natural.",
        ["rhodes", "soft", "linen", "damped"],
        {"brightness": 0.32, "warmth": 0.9, "movement": 0.08, "density": 0.68, "space": 0.42, "aggression": 0.06},
        okan_params(warmth=0.88, bell=0.22, brightness=3800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.012, decay=1.05, sustain=0.72, release=0.72, filter_env_amt=0.2,
                    stereo_width=0.42),
    ),
    make_preset(
        "Amber Warmth",
        "Organic",
        "The amber-like warmth of a perfectly maintained Rhodes. Rich, dense, golden.",
        ["rhodes", "amber", "warm", "golden"],
        {"brightness": 0.45, "warmth": 0.88, "movement": 0.1, "density": 0.72, "space": 0.48, "aggression": 0.15},
        okan_params(warmth=0.8, bell=0.38, brightness=4800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.006, decay=0.95, sustain=0.68, release=0.62, filter_env_amt=0.25,
                    stereo_width=0.48),
    ),
    make_preset(
        "Dusk Session",
        "Organic",
        "Late afternoon session. Warmth increasing as the day fades. Organic shift from neutral to warm.",
        ["rhodes", "dusk", "warm", "session"],
        {"brightness": 0.42, "warmth": 0.82, "movement": 0.14, "density": 0.68, "space": 0.46, "aggression": 0.15},
        okan_params(warmth=0.72, bell=0.38, brightness=4600.0, trem_rate=4.0, trem_depth=0.03,
                    attack=0.006, decay=0.92, sustain=0.66, release=0.6, filter_env_amt=0.26,
                    stereo_width=0.46),
    ),
]

# ===========================  FLUX (15)  ======================================

PRESETS += [
    make_preset(
        "Full Vibrato",
        "Flux",
        "Maximum tremolo depth with natural tremolo rate. The iconic Rhodes vibrato circuit fully engaged.",
        ["rhodes", "tremolo", "vibrato", "movement"],
        {"brightness": 0.52, "warmth": 0.7, "movement": 0.85, "density": 0.62, "space": 0.65, "aggression": 0.25},
        okan_params(warmth=0.38, bell=0.52, brightness=6200.0, trem_rate=4.8, trem_depth=0.88,
                    attack=0.004, decay=0.85, sustain=0.62, release=0.52, filter_env_amt=0.35,
                    stereo_width=0.75, macro_movement=0.8),
    ),
    make_preset(
        "Tremolo Slow",
        "Flux",
        "Very slow tremolo at medium depth. Heartbeat rate. Majestic oscillation.",
        ["rhodes", "tremolo", "slow", "movement"],
        {"brightness": 0.5, "warmth": 0.72, "movement": 0.65, "density": 0.62, "space": 0.6, "aggression": 0.18},
        okan_params(warmth=0.42, bell=0.5, brightness=6000.0, trem_rate=1.2, trem_depth=0.65,
                    attack=0.005, decay=0.88, sustain=0.62, release=0.55, filter_env_amt=0.32,
                    stereo_width=0.65, macro_movement=0.65),
    ),
    make_preset(
        "Fast Trem",
        "Flux",
        "High-rate tremolo. The classic fast Rhodes shimmer. Like an amplifier spring in overdrive.",
        ["rhodes", "tremolo", "fast", "shimmer"],
        {"brightness": 0.55, "warmth": 0.65, "movement": 0.88, "density": 0.6, "space": 0.68, "aggression": 0.35},
        okan_params(warmth=0.32, bell=0.55, brightness=7000.0, trem_rate=8.5, trem_depth=0.75,
                    attack=0.004, decay=0.82, sustain=0.6, release=0.5, filter_env_amt=0.38,
                    stereo_width=0.72, macro_movement=0.85),
    ),
    make_preset(
        "Vibrato Circuit",
        "Flux",
        "Deep stereo tremolo with wide spread. Panning like the original suitcase vibrato.",
        ["rhodes", "vibrato", "stereo", "pan"],
        {"brightness": 0.5, "warmth": 0.6, "movement": 0.75, "density": 0.4, "space": 0.6, "aggression": 0.15},
        okan_params(warmth=0.35, bell=0.5, brightness=6000.0, trem_rate=5.5, trem_depth=0.7,
                    attack=0.005, decay=1.0, sustain=0.6, release=0.5, filter_env_amt=0.35,
                    stereo_width=0.8, macro_movement=0.7),
    ),
    make_preset(
        "Trem Funk",
        "Flux",
        "Funk groove with heavy tremolo. The tempo-appropriate rate gives a rhythmic pulse.",
        ["rhodes", "funk", "tremolo", "rhythm"],
        {"brightness": 0.58, "warmth": 0.65, "movement": 0.8, "density": 0.62, "space": 0.55, "aggression": 0.55},
        okan_params(warmth=0.3, bell=0.58, brightness=7000.0, trem_rate=6.0, trem_depth=0.82,
                    attack=0.004, decay=0.72, sustain=0.58, release=0.42, filter_env_amt=0.45,
                    stereo_width=0.62, macro_movement=0.8),
    ),
    make_preset(
        "Pulse Width",
        "Flux",
        "Medium tremolo with wide stereo creates a pulse-width effect. Electronic-leaning Rhodes.",
        ["rhodes", "pulse", "electronic", "movement"],
        {"brightness": 0.55, "warmth": 0.62, "movement": 0.72, "density": 0.55, "space": 0.75, "aggression": 0.3},
        okan_params(warmth=0.3, bell=0.55, brightness=6800.0, trem_rate=4.5, trem_depth=0.65,
                    attack=0.004, decay=0.85, sustain=0.6, release=0.52, filter_env_amt=0.38,
                    stereo_width=0.88),
    ),
    make_preset(
        "Shimmer Trail",
        "Flux",
        "Medium tremolo on long sustain. The shimmer follows behind each note like a trail.",
        ["rhodes", "shimmer", "trail", "sustain"],
        {"brightness": 0.52, "warmth": 0.68, "movement": 0.62, "density": 0.55, "space": 0.65, "aggression": 0.18},
        okan_params(warmth=0.38, bell=0.52, brightness=6000.0, trem_rate=3.8, trem_depth=0.55,
                    attack=0.005, decay=1.0, sustain=0.62, release=0.65, filter_env_amt=0.32,
                    stereo_width=0.72, macro_movement=0.6),
    ),
    make_preset(
        "Ocean Trem",
        "Flux",
        "Tidal tremolo rate. The slowest natural oscillation. Notes breathe like ocean swells.",
        ["rhodes", "ocean", "tremolo", "slow"],
        {"brightness": 0.5, "warmth": 0.72, "movement": 0.55, "density": 0.6, "space": 0.62, "aggression": 0.12},
        okan_params(warmth=0.42, bell=0.48, brightness=5800.0, trem_rate=0.8, trem_depth=0.58,
                    attack=0.005, decay=0.9, sustain=0.65, release=0.6, filter_env_amt=0.3,
                    stereo_width=0.65, macro_movement=0.55),
    ),
    make_preset(
        "Dual Wave",
        "Flux",
        "LFO1 and tremolo at slightly different rates create interference beats. Pulsing like two waves.",
        ["rhodes", "wave", "interference", "movement"],
        {"brightness": 0.52, "warmth": 0.68, "movement": 0.72, "density": 0.58, "space": 0.62, "aggression": 0.22},
        okan_params(warmth=0.38, bell=0.5, brightness=6200.0, trem_rate=4.0, trem_depth=0.55,
                    attack=0.004, decay=0.88, sustain=0.62, release=0.55, filter_env_amt=0.35,
                    stereo_width=0.7, lfo1_rate=3.7, lfo1_depth=0.12),
    ),
    make_preset(
        "Mad Trem",
        "Flux",
        "Extreme tremolo rate, maximum depth. The Rhodes as modulation source. Frenzied.",
        ["rhodes", "tremolo", "extreme", "mod"],
        {"brightness": 0.58, "warmth": 0.6, "movement": 0.98, "density": 0.55, "space": 0.62, "aggression": 0.72},
        okan_params(warmth=0.28, bell=0.55, brightness=7000.0, trem_rate=11.5, trem_depth=1.0,
                    attack=0.004, decay=0.78, sustain=0.58, release=0.45, filter_env_amt=0.45,
                    stereo_width=0.75, macro_movement=0.95),
    ),
    make_preset(
        "Headhunters Comp",
        "Flux",
        "Herbie Hancock Headhunters session. Tremolo at the right pace, bell up, stereo. Maximum funk.",
        ["rhodes", "funk", "herbie", "headhunters"],
        {"brightness": 0.62, "warmth": 0.65, "movement": 0.78, "density": 0.65, "space": 0.62, "aggression": 0.62},
        okan_params(warmth=0.32, bell=0.65, brightness=7500.0, trem_rate=5.8, trem_depth=0.75,
                    attack=0.004, decay=0.75, sustain=0.6, release=0.45, filter_env_amt=0.45,
                    stereo_width=0.68, macro_movement=0.78),
    ),
    make_preset(
        "Slow Motion",
        "Flux",
        "Everything slow. Slow tremolo, long decay, gentle. Time has expanded.",
        ["rhodes", "slow", "gentle", "movement"],
        {"brightness": 0.48, "warmth": 0.75, "movement": 0.45, "density": 0.58, "space": 0.6, "aggression": 0.1},
        okan_params(warmth=0.52, bell=0.46, brightness=5500.0, trem_rate=1.5, trem_depth=0.42,
                    attack=0.006, decay=0.95, sustain=0.65, release=0.65, filter_env_amt=0.28,
                    stereo_width=0.62, macro_movement=0.45),
    ),
    make_preset(
        "Swing Vibrato",
        "Flux",
        "Tremolo at swing feel tempo. The oscillation lands on the off-beat. Natural rhythmic feel.",
        ["rhodes", "swing", "tremolo", "rhythm"],
        {"brightness": 0.52, "warmth": 0.68, "movement": 0.7, "density": 0.6, "space": 0.58, "aggression": 0.3},
        okan_params(warmth=0.38, bell=0.52, brightness=6200.0, trem_rate=5.2, trem_depth=0.62,
                    attack=0.004, decay=0.82, sustain=0.62, release=0.5, filter_env_amt=0.38,
                    stereo_width=0.62, macro_movement=0.7),
    ),
    make_preset(
        "Heavy Shimmer",
        "Flux",
        "Deep tremolo over wide stereo. Maximum shimmer. Notes undulate heavily.",
        ["rhodes", "heavy", "shimmer", "tremolo"],
        {"brightness": 0.55, "warmth": 0.65, "movement": 0.88, "density": 0.58, "space": 0.75, "aggression": 0.35},
        okan_params(warmth=0.35, bell=0.52, brightness=6500.0, trem_rate=4.8, trem_depth=0.92,
                    attack=0.004, decay=0.88, sustain=0.6, release=0.55, filter_env_amt=0.35,
                    stereo_width=0.85, macro_movement=0.88),
    ),
    make_preset(
        "Beat Trem",
        "Flux",
        "Tremolo synced to quarter-note at 120 BPM (4 Hz). For rhythmically locked session work.",
        ["rhodes", "tremolo", "rhythmic", "sync"],
        {"brightness": 0.55, "warmth": 0.65, "movement": 0.72, "density": 0.62, "space": 0.58, "aggression": 0.38},
        okan_params(warmth=0.35, bell=0.52, brightness=6800.0, trem_rate=4.0, trem_depth=0.72,
                    attack=0.004, decay=0.78, sustain=0.6, release=0.48, filter_env_amt=0.42,
                    stereo_width=0.65, macro_movement=0.72),
    ),
]

# ===========================  LUMINOUS (12)  ==================================

PRESETS += [
    make_preset(
        "Bright Bell",
        "Luminous",
        "High brightness, pronounced bell tone. The tines at their most metallic and brilliant.",
        ["rhodes", "bright", "bell", "luminous"],
        {"brightness": 0.85, "warmth": 0.38, "movement": 0.1, "density": 0.5, "space": 0.52, "aggression": 0.62},
        okan_params(warmth=0.12, bell=0.88, brightness=16000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.65, sustain=0.52, release=0.45, filter_env_amt=0.6,
                    stereo_width=0.55),
    ),
    make_preset(
        "Sunlight Tine",
        "Luminous",
        "High brightness with warmth. Morning sunlight through the studio window onto the tines.",
        ["rhodes", "bright", "sunlight", "warm"],
        {"brightness": 0.78, "warmth": 0.52, "movement": 0.1, "density": 0.55, "space": 0.5, "aggression": 0.48},
        okan_params(warmth=0.25, bell=0.75, brightness=14000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.72, sustain=0.55, release=0.48, filter_env_amt=0.55,
                    stereo_width=0.55),
    ),
    make_preset(
        "Crisp Attack",
        "Luminous",
        "Very bright attack, short decay, high bell. Punchy and luminous. Like a photograph of a tine strike.",
        ["rhodes", "bright", "crisp", "attack"],
        {"brightness": 0.82, "warmth": 0.38, "movement": 0.08, "density": 0.52, "space": 0.45, "aggression": 0.75},
        okan_params(warmth=0.12, bell=0.85, brightness=15000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.55, sustain=0.48, release=0.38, filter_env_amt=0.65,
                    stereo_width=0.48),
    ),
    make_preset(
        "Shimmer Top",
        "Luminous",
        "High-register luminous shimmer. Maximum brightness with slight tremolo creates a glittering surface.",
        ["rhodes", "shimmer", "bright", "treble"],
        {"brightness": 0.88, "warmth": 0.32, "movement": 0.28, "density": 0.45, "space": 0.62, "aggression": 0.55},
        okan_params(warmth=0.08, bell=0.88, brightness=17000.0, trem_rate=5.0, trem_depth=0.25,
                    attack=0.003, decay=0.7, sustain=0.5, release=0.48, filter_env_amt=0.62,
                    stereo_width=0.68),
    ),
    make_preset(
        "Electro Bright",
        "Luminous",
        "Electronic music ready. Very bright tines cut through dense mixes. Maximum filter envelope sweep.",
        ["rhodes", "electronic", "bright", "mix"],
        {"brightness": 0.88, "warmth": 0.35, "movement": 0.08, "density": 0.52, "space": 0.48, "aggression": 0.78},
        okan_params(warmth=0.1, bell=0.85, brightness=17000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.65, sustain=0.5, release=0.42, filter_env_amt=0.75,
                    stereo_width=0.55),
    ),
    make_preset(
        "Gold Tine",
        "Luminous",
        "Golden bright tone. High brightness with medium warmth. Neither cold nor warm — golden.",
        ["rhodes", "golden", "bright", "tine"],
        {"brightness": 0.78, "warmth": 0.5, "movement": 0.1, "density": 0.58, "space": 0.52, "aggression": 0.52},
        okan_params(warmth=0.2, bell=0.78, brightness=13000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.75, sustain=0.55, release=0.48, filter_env_amt=0.58,
                    stereo_width=0.55),
    ),
    make_preset(
        "Bell Full",
        "Luminous",
        "Bell value at maximum. The Rhodes bell tone completely dominates. Like a music box.",
        ["rhodes", "bell", "full", "luminous"],
        {"brightness": 0.72, "warmth": 0.42, "movement": 0.15, "density": 0.5, "space": 0.55, "aggression": 0.48},
        okan_params(warmth=0.15, bell=1.0, brightness=12000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.8, sustain=0.5, release=0.55, filter_env_amt=0.55,
                    stereo_width=0.58),
    ),
    make_preset(
        "Ice Tine",
        "Luminous",
        "Cold, crystalline, icy brightness. Very low warmth, very high brightness. Like tines forged from ice.",
        ["rhodes", "ice", "cold", "bright"],
        {"brightness": 0.9, "warmth": 0.22, "movement": 0.1, "density": 0.42, "space": 0.52, "aggression": 0.65},
        okan_params(warmth=0.05, bell=0.88, brightness=18000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.6, sustain=0.45, release=0.4, filter_env_amt=0.68,
                    stereo_width=0.52),
    ),
    make_preset(
        "Bright Comp",
        "Luminous",
        "Bright comping tone. High brightness, short decay. For fast chord changes in a bright register.",
        ["rhodes", "bright", "comp", "fast"],
        {"brightness": 0.8, "warmth": 0.42, "movement": 0.08, "density": 0.52, "space": 0.45, "aggression": 0.62},
        okan_params(warmth=0.15, bell=0.78, brightness=14000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.62, sustain=0.5, release=0.4, filter_env_amt=0.6,
                    stereo_width=0.48),
    ),
    make_preset(
        "Spark Keys",
        "Luminous",
        "Sparkling brightness with slight tremolo for added movement. Like electrostatic sparks.",
        ["rhodes", "spark", "bright", "movement"],
        {"brightness": 0.85, "warmth": 0.35, "movement": 0.25, "density": 0.48, "space": 0.58, "aggression": 0.62},
        okan_params(warmth=0.1, bell=0.85, brightness=16000.0, trem_rate=6.0, trem_depth=0.22,
                    attack=0.003, decay=0.68, sustain=0.5, release=0.45, filter_env_amt=0.65,
                    stereo_width=0.62),
    ),
    make_preset(
        "Noon Light",
        "Luminous",
        "Noon-brightness. Direct, full-value, unfiltered. Maximum tine exposure.",
        ["rhodes", "noon", "direct", "bright"],
        {"brightness": 0.82, "warmth": 0.42, "movement": 0.08, "density": 0.52, "space": 0.5, "aggression": 0.58},
        okan_params(warmth=0.14, bell=0.82, brightness=15000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.72, sustain=0.52, release=0.45, filter_env_amt=0.62,
                    stereo_width=0.52),
    ),
    make_preset(
        "Tine Flash",
        "Luminous",
        "Flash of pure tine. Short attack, very short decay, maximum brightness. Like a camera flash in audio.",
        ["rhodes", "flash", "short", "bright"],
        {"brightness": 0.9, "warmth": 0.28, "movement": 0.06, "density": 0.42, "space": 0.42, "aggression": 0.85},
        okan_params(warmth=0.05, bell=0.92, brightness=18000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.45, sustain=0.38, release=0.32, filter_env_amt=0.75,
                    stereo_width=0.45),
    ),
]

# ===========================  DEEP (12)  ======================================

PRESETS += [
    make_preset(
        "Dark Suitcase",
        "Deep",
        "The darkest Rhodes tone. Very high warmth, minimal bell, low brightness. Like playing in the dark.",
        ["rhodes", "dark", "deep", "warm"],
        {"brightness": 0.22, "warmth": 0.92, "movement": 0.08, "density": 0.72, "space": 0.42, "aggression": 0.15},
        okan_params(warmth=0.92, bell=0.12, brightness=2500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.008, decay=1.0, sustain=0.72, release=0.7, filter_env_amt=0.15,
                    stereo_width=0.42),
    ),
    make_preset(
        "Subsonic Keys",
        "Deep",
        "Very dark, very warm. The tones are pushing the lower limit of tine resonance. Dense and slow.",
        ["rhodes", "subsonic", "deep", "dense"],
        {"brightness": 0.15, "warmth": 0.95, "movement": 0.06, "density": 0.82, "space": 0.38, "aggression": 0.12},
        okan_params(warmth=0.95, bell=0.08, brightness=1800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.01, decay=1.1, sustain=0.75, release=0.78, filter_env_amt=0.12,
                    stereo_width=0.38),
    ),
    make_preset(
        "Midnight Low",
        "Deep",
        "The lowest register of the Rhodes at midnight warmth. Dense and resonant.",
        ["rhodes", "midnight", "low", "dark"],
        {"brightness": 0.2, "warmth": 0.9, "movement": 0.08, "density": 0.78, "space": 0.42, "aggression": 0.15},
        okan_params(warmth=0.9, bell=0.1, brightness=2200.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.009, decay=1.05, sustain=0.72, release=0.72, filter_env_amt=0.14,
                    stereo_width=0.42),
    ),
    make_preset(
        "Velvet Dark",
        "Deep",
        "Dark velvet warmth. The felt is thick, the tone is absolute. Nothing bright disturbs the low.",
        ["rhodes", "velvet", "dark", "warm"],
        {"brightness": 0.25, "warmth": 0.9, "movement": 0.06, "density": 0.72, "space": 0.4, "aggression": 0.1},
        okan_params(warmth=0.88, bell=0.15, brightness=3000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.01, decay=1.1, sustain=0.72, release=0.75, filter_env_amt=0.15,
                    stereo_width=0.42),
    ),
    make_preset(
        "Coal Tone",
        "Deep",
        "Dense, dark, heavy. Like coal — densely compressed organic material.",
        ["rhodes", "dense", "dark", "heavy"],
        {"brightness": 0.18, "warmth": 0.92, "movement": 0.06, "density": 0.85, "space": 0.35, "aggression": 0.15},
        okan_params(warmth=0.92, bell=0.1, brightness=2000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.012, decay=1.15, sustain=0.75, release=0.8, filter_env_amt=0.1,
                    stereo_width=0.35),
    ),
    make_preset(
        "Deep Groove",
        "Deep",
        "Low register groove. Dark, warm, rhythmic. For bassline-level Rhodes comping.",
        ["rhodes", "deep", "groove", "low"],
        {"brightness": 0.28, "warmth": 0.85, "movement": 0.1, "density": 0.78, "space": 0.4, "aggression": 0.35},
        okan_params(warmth=0.82, bell=0.18, brightness=3500.0, trem_rate=4.0, trem_depth=0.04,
                    attack=0.006, decay=0.82, sustain=0.68, release=0.55, filter_env_amt=0.28,
                    stereo_width=0.42),
    ),
    make_preset(
        "Shadow Rhodes",
        "Deep",
        "Operating in the shadows. Low warmth and brightness together create a compressed, thick tone.",
        ["rhodes", "shadow", "dark", "thick"],
        {"brightness": 0.22, "warmth": 0.88, "movement": 0.08, "density": 0.78, "space": 0.38, "aggression": 0.12},
        okan_params(warmth=0.88, bell=0.12, brightness=2500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.009, decay=1.05, sustain=0.72, release=0.72, filter_env_amt=0.12,
                    stereo_width=0.38),
    ),
    make_preset(
        "Cavernous",
        "Deep",
        "Wide stereo with very dark tone. A huge, reverberant dark space. Deep and spatial.",
        ["rhodes", "cavernous", "dark", "wide"],
        {"brightness": 0.2, "warmth": 0.88, "movement": 0.1, "density": 0.7, "space": 0.72, "aggression": 0.12},
        okan_params(warmth=0.88, bell=0.12, brightness=2500.0, trem_rate=4.0, trem_depth=0.06,
                    attack=0.008, decay=1.1, sustain=0.72, release=0.78, filter_env_amt=0.12,
                    stereo_width=0.85, macro_space=0.45),
    ),
    make_preset(
        "Root Dark",
        "Deep",
        "Maximum warmth, minimal bell, minimal brightness. The root frequency only.",
        ["rhodes", "root", "dark", "fundamental"],
        {"brightness": 0.12, "warmth": 0.96, "movement": 0.04, "density": 0.82, "space": 0.32, "aggression": 0.1},
        okan_params(warmth=0.96, bell=0.06, brightness=1500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.012, decay=1.15, sustain=0.78, release=0.85, filter_env_amt=0.08,
                    stereo_width=0.32),
    ),
    make_preset(
        "Dark Trem",
        "Deep",
        "Dark tone with slow tremolo. The oscillation moves through deep warmth like breathing.",
        ["rhodes", "dark", "tremolo", "deep"],
        {"brightness": 0.25, "warmth": 0.88, "movement": 0.45, "density": 0.7, "space": 0.5, "aggression": 0.15},
        okan_params(warmth=0.88, bell=0.15, brightness=3000.0, trem_rate=2.5, trem_depth=0.45,
                    attack=0.008, decay=1.0, sustain=0.7, release=0.68, filter_env_amt=0.15,
                    stereo_width=0.55, macro_movement=0.45),
    ),
    make_preset(
        "Muted Dark",
        "Deep",
        "Muted felt damping with dark tone. Very short natural sustain, compressed warmth.",
        ["rhodes", "muted", "dark", "damped"],
        {"brightness": 0.22, "warmth": 0.88, "movement": 0.06, "density": 0.72, "space": 0.35, "aggression": 0.15},
        okan_params(warmth=0.88, bell=0.1, brightness=2500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.01, decay=0.75, sustain=0.62, release=0.5, filter_env_amt=0.15,
                    stereo_width=0.35),
    ),
    make_preset(
        "Black Keys",
        "Deep",
        "Only the darkness. Low warmth, minimal bell, minimal stereo. The instrument as shadow.",
        ["rhodes", "dark", "shadow", "low"],
        {"brightness": 0.18, "warmth": 0.92, "movement": 0.06, "density": 0.78, "space": 0.38, "aggression": 0.12},
        okan_params(warmth=0.92, bell=0.08, brightness=2000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.01, decay=1.1, sustain=0.75, release=0.78, filter_env_amt=0.1,
                    stereo_width=0.38),
    ),
]

# ===========================  KINETIC (10)  ===================================

PRESETS += [
    make_preset(
        "Short Tine",
        "Kinetic",
        "Very short decay. Staccato Rhodes. Each note is a percussive event. No sustain pedal.",
        ["rhodes", "short", "staccato", "percussive"],
        {"brightness": 0.55, "warmth": 0.65, "movement": 0.08, "density": 0.6, "space": 0.42, "aggression": 0.65},
        okan_params(warmth=0.3, bell=0.55, brightness=7000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.35, sustain=0.42, release=0.28, filter_env_amt=0.55,
                    stereo_width=0.45),
    ),
    make_preset(
        "Funk Snap",
        "Kinetic",
        "Snap-style funk Rhodes. Very short, very bright, high bell. Chop and release.",
        ["rhodes", "funk", "snap", "short"],
        {"brightness": 0.68, "warmth": 0.52, "movement": 0.08, "density": 0.55, "space": 0.42, "aggression": 0.78},
        okan_params(warmth=0.2, bell=0.72, brightness=10000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.3, sustain=0.38, release=0.22, filter_env_amt=0.65,
                    stereo_width=0.42),
    ),
    make_preset(
        "Hard Tine",
        "Kinetic",
        "Maximum force. High brightness, full bell, very fast attack. The Rhodes hit hard.",
        ["rhodes", "hard", "bright", "forte"],
        {"brightness": 0.75, "warmth": 0.45, "movement": 0.06, "density": 0.6, "space": 0.42, "aggression": 0.88},
        okan_params(warmth=0.15, bell=0.8, brightness=12000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.5, sustain=0.45, release=0.35, filter_env_amt=0.72,
                    stereo_width=0.42),
    ),
    make_preset(
        "Percussive Body",
        "Kinetic",
        "High body resonance makes the Rhodes more percussive. Short decay, fast attack.",
        ["rhodes", "percussive", "body", "kinetic"],
        {"brightness": 0.55, "warmth": 0.68, "movement": 0.08, "density": 0.72, "space": 0.4, "aggression": 0.72},
        okan_params(warmth=0.55, bell=0.55, brightness=7000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.42, sustain=0.45, release=0.32, filter_env_amt=0.6,
                    stereo_width=0.42),
    ),
    make_preset(
        "Rhythm Comp",
        "Kinetic",
        "Rhythm section comping tone. Short and punchy. Every chord has a physical impact.",
        ["rhodes", "rhythm", "comp", "punchy"],
        {"brightness": 0.6, "warmth": 0.6, "movement": 0.08, "density": 0.65, "space": 0.42, "aggression": 0.72},
        okan_params(warmth=0.32, bell=0.62, brightness=8000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.45, sustain=0.45, release=0.32, filter_env_amt=0.62,
                    stereo_width=0.42),
    ),
    make_preset(
        "Staccato Rhodes",
        "Kinetic",
        "Pure staccato articulation. Attack is the entire note. Rhythm and attack only.",
        ["rhodes", "staccato", "attack", "rhythm"],
        {"brightness": 0.6, "warmth": 0.58, "movement": 0.06, "density": 0.58, "space": 0.38, "aggression": 0.75},
        okan_params(warmth=0.28, bell=0.58, brightness=8500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.28, sustain=0.35, release=0.2, filter_env_amt=0.65,
                    stereo_width=0.4),
    ),
    make_preset(
        "Velocity Punch",
        "Kinetic",
        "Velocity dynamics fully exposed. High filter env amount makes loud hits completely different from soft.",
        ["rhodes", "velocity", "punch", "dynamic"],
        {"brightness": 0.62, "warmth": 0.6, "movement": 0.08, "density": 0.62, "space": 0.45, "aggression": 0.7},
        okan_params(warmth=0.32, bell=0.65, brightness=8500.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.55, sustain=0.5, release=0.4, filter_env_amt=0.78,
                    stereo_width=0.45),
    ),
    make_preset(
        "R&B Chop",
        "Kinetic",
        "R&B chop patterns. Short, bright, high bell. For rhythmically complex arrangements.",
        ["rhodes", "r&b", "chop", "short"],
        {"brightness": 0.68, "warmth": 0.55, "movement": 0.08, "density": 0.6, "space": 0.42, "aggression": 0.72},
        okan_params(warmth=0.25, bell=0.72, brightness=10000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.38, sustain=0.42, release=0.28, filter_env_amt=0.68,
                    stereo_width=0.45),
    ),
    make_preset(
        "Impact Tine",
        "Kinetic",
        "The physical impact of finger on key transmitted through tine. Maximum velocity response.",
        ["rhodes", "impact", "kinetic", "forte"],
        {"brightness": 0.72, "warmth": 0.48, "movement": 0.06, "density": 0.6, "space": 0.42, "aggression": 0.88},
        okan_params(warmth=0.18, bell=0.78, brightness=11000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.45, sustain=0.42, release=0.32, filter_env_amt=0.72,
                    stereo_width=0.42),
    ),
    make_preset(
        "Drum Machine",
        "Kinetic",
        "Rhodes used as a drum machine hit. Very short, very bright, very high bell. Percussive instrument.",
        ["rhodes", "percussive", "drum", "short"],
        {"brightness": 0.75, "warmth": 0.42, "movement": 0.06, "density": 0.55, "space": 0.38, "aggression": 0.92},
        okan_params(warmth=0.12, bell=0.85, brightness=12000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.25, sustain=0.3, release=0.18, filter_env_amt=0.75,
                    stereo_width=0.38),
    ),
]

# ===========================  ETHEREAL (8)  ===================================

PRESETS += [
    make_preset(
        "Pad Rhodes",
        "Ethereal",
        "Rhodes as a synth pad. Very long release, slow attack, medium bell. Background harmonic texture.",
        ["rhodes", "pad", "ambient", "long"],
        {"brightness": 0.5, "warmth": 0.72, "movement": 0.18, "density": 0.52, "space": 0.72, "aggression": 0.06},
        okan_params(warmth=0.5, bell=0.5, brightness=6000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.08, decay=1.5, sustain=0.72, release=2.5, filter_env_amt=0.22,
                    stereo_width=0.75, macro_space=0.4),
    ),
    make_preset(
        "Dream Keys",
        "Ethereal",
        "Very slow attack, long release, slight LFO. Dream-state Rhodes. Notes arrive like waking memories.",
        ["rhodes", "dream", "ambient", "slow"],
        {"brightness": 0.48, "warmth": 0.72, "movement": 0.25, "density": 0.5, "space": 0.78, "aggression": 0.05},
        okan_params(warmth=0.52, bell=0.48, brightness=5800.0, trem_rate=4.0, trem_depth=0.05,
                    attack=0.15, decay=1.8, sustain=0.72, release=3.0, filter_env_amt=0.2,
                    stereo_width=0.8, lfo1_rate=0.12, lfo1_depth=0.06),
    ),
    make_preset(
        "Tine Cloud",
        "Ethereal",
        "Multiple tines forming a harmonic cloud. Long release, medium bell, wide stereo. For chord pads.",
        ["rhodes", "cloud", "pad", "wide"],
        {"brightness": 0.52, "warmth": 0.68, "movement": 0.15, "density": 0.48, "space": 0.85, "aggression": 0.06},
        okan_params(warmth=0.45, bell=0.55, brightness=6200.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.1, decay=1.6, sustain=0.7, release=2.8, filter_env_amt=0.22,
                    stereo_width=0.92, macro_space=0.5),
    ),
    make_preset(
        "Slow Swell",
        "Ethereal",
        "Chord swell from silence to full voice over 2 seconds. Ethereal arrival. Very slow attack.",
        ["rhodes", "swell", "slow", "ambient"],
        {"brightness": 0.5, "warmth": 0.7, "movement": 0.2, "density": 0.52, "space": 0.72, "aggression": 0.04},
        okan_params(warmth=0.48, bell=0.5, brightness=5800.0, trem_rate=4.0, trem_depth=0.06,
                    attack=0.35, decay=1.8, sustain=0.72, release=2.5, filter_env_amt=0.2,
                    stereo_width=0.75),
    ),
    make_preset(
        "Halo Keys",
        "Ethereal",
        "Bell resonance creates a halo around each note. High bell, long release, medium stereo.",
        ["rhodes", "halo", "bell", "ethereal"],
        {"brightness": 0.58, "warmth": 0.62, "movement": 0.18, "density": 0.45, "space": 0.72, "aggression": 0.08},
        okan_params(warmth=0.32, bell=0.8, brightness=7000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.08, decay=1.5, sustain=0.65, release=2.2, filter_env_amt=0.28,
                    stereo_width=0.72),
    ),
    make_preset(
        "Floating Chord",
        "Ethereal",
        "Chords floating in space. Wide stereo, very long release, slight tremolo. Weightless.",
        ["rhodes", "floating", "pad", "ambient"],
        {"brightness": 0.5, "warmth": 0.68, "movement": 0.22, "density": 0.45, "space": 0.88, "aggression": 0.05},
        okan_params(warmth=0.42, bell=0.52, brightness=6000.0, trem_rate=3.5, trem_depth=0.15,
                    attack=0.12, decay=1.6, sustain=0.7, release=3.0, filter_env_amt=0.2,
                    stereo_width=0.95, macro_space=0.55),
    ),
    make_preset(
        "Ambient Tine",
        "Ethereal",
        "The Rhodes as ambient texture. Maximum release, slow attack, gentle bell. Sustained harmonic field.",
        ["rhodes", "ambient", "texture", "long"],
        {"brightness": 0.5, "warmth": 0.7, "movement": 0.15, "density": 0.45, "space": 0.82, "aggression": 0.04},
        okan_params(warmth=0.48, bell=0.5, brightness=5800.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.2, decay=1.8, sustain=0.72, release=4.5, filter_env_amt=0.18,
                    stereo_width=0.85),
    ),
    make_preset(
        "Ghost Rhodes",
        "Ethereal",
        "Near-inaudible Rhodes. Very slow attack, maximum release, light bell. Notes are impressions.",
        ["rhodes", "ghost", "ambient", "quiet"],
        {"brightness": 0.45, "warmth": 0.72, "movement": 0.18, "density": 0.38, "space": 0.82, "aggression": 0.03},
        okan_params(warmth=0.5, bell=0.45, brightness=5500.0, trem_rate=4.0, trem_depth=0.04,
                    attack=0.4, decay=2.0, sustain=0.68, release=5.0, filter_env_amt=0.15,
                    stereo_width=0.85),
    ),
]

# ===========================  CRYSTALLINE (5)  ================================

PRESETS += [
    make_preset(
        "Pure Bell",
        "Crystalline",
        "Maximum bell value, high brightness. The Rhodes tine as a pure bell instrument. Crystal clarity.",
        ["rhodes", "bell", "crystal", "pure"],
        {"brightness": 0.82, "warmth": 0.3, "movement": 0.1, "density": 0.38, "space": 0.6, "aggression": 0.55},
        okan_params(warmth=0.08, bell=1.0, brightness=15000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.9, sustain=0.42, release=0.65, filter_env_amt=0.62,
                    stereo_width=0.62),
    ),
    make_preset(
        "Crystal Tine",
        "Crystalline",
        "Crystalline purity. Very high brightness, maximum bell, very low warmth. Notes ring like crystal glasses.",
        ["rhodes", "crystal", "bright", "bell"],
        {"brightness": 0.88, "warmth": 0.22, "movement": 0.12, "density": 0.35, "space": 0.65, "aggression": 0.62},
        okan_params(warmth=0.05, bell=0.95, brightness=17000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.85, sustain=0.38, release=0.65, filter_env_amt=0.68,
                    stereo_width=0.65),
    ),
    make_preset(
        "Glass Rhodes",
        "Crystalline",
        "The Rhodes reimagined as glass tines. High brightness and bell. Cold and resonant.",
        ["rhodes", "glass", "bright", "cold"],
        {"brightness": 0.85, "warmth": 0.25, "movement": 0.12, "density": 0.38, "space": 0.62, "aggression": 0.58},
        okan_params(warmth=0.06, bell=0.92, brightness=16000.0, trem_rate=4.0, trem_depth=0.06,
                    attack=0.003, decay=0.9, sustain=0.4, release=0.7, filter_env_amt=0.65,
                    stereo_width=0.62),
    ),
    make_preset(
        "Tine Diamond",
        "Crystalline",
        "Diamond-hard tines. Maximum brightness, maximum bell, very low warmth. Absolute clarity.",
        ["rhodes", "diamond", "bright", "crystal"],
        {"brightness": 0.92, "warmth": 0.18, "movement": 0.08, "density": 0.32, "space": 0.58, "aggression": 0.68},
        okan_params(warmth=0.04, bell=1.0, brightness=18000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.75, sustain=0.35, release=0.58, filter_env_amt=0.72,
                    stereo_width=0.58),
    ),
    make_preset(
        "Sine Bell",
        "Crystalline",
        "Near-pure sine bell tone. Maximum bell, high brightness, no warmth. Mathematically clean.",
        ["rhodes", "sine", "bell", "pure"],
        {"brightness": 0.88, "warmth": 0.15, "movement": 0.06, "density": 0.32, "space": 0.58, "aggression": 0.55},
        okan_params(warmth=0.02, bell=0.98, brightness=17000.0, trem_rate=4.0, trem_depth=0.0,
                    attack=0.003, decay=0.82, sustain=0.38, release=0.62, filter_env_amt=0.68,
                    stereo_width=0.58),
    ),
]

# ---------------------------------------------------------------------------
# COUNT CHECK
# ---------------------------------------------------------------------------

def main():
    counts = {}
    for p in PRESETS:
        m = p["mood"]
        counts[m] = counts.get(m, 0) + 1

    print(f"Total presets to write: {len(PRESETS)}")
    for mood, count in sorted(counts.items()):
        print(f"  {mood}: {count}")

    # Verify migration is 0.0 everywhere
    bad_migration = [p for p in PRESETS
                     if p["parameters"]["Okeanos"].get("okan_migration", 0.0) != 0.0]
    if bad_migration:
        print(f"ERROR: {len(bad_migration)} presets have okan_migration != 0.0!")
        for p in bad_migration:
            print(f"  {p['name']}")
        sys.exit(1)
    else:
        print("Migration safety check PASSED (all 0.0)")

    # Check aggression targets (12+ at >= 0.7)
    high_agg = [p for p in PRESETS if p["dna"]["aggression"] >= 0.7]
    print(f"High-aggression (>=0.7): {len(high_agg)}")

    written = 0
    for p in PRESETS:
        path = write_preset(p)
        written += 1

    print(f"Written: {written} presets")


if __name__ == "__main__":
    main()
