#!/usr/bin/env python3
"""
xpn_atmosphere_aggression_expander.py

Generates 50 Atmosphere presets targeting a spread aggression dimension.
Fleet DNA diversity analysis found Atmosphere aggression std=0.095 — locked
near zero with virtually no variation. This pack deliberately corrects that.

Tiers:
  calm-atmosphere  (10): aggression 0.05–0.15  (extreme other dims)
  tense-atmosphere (10): aggression 0.35–0.50  (unsettled undertone)
  charged-atmosphere (15): aggression 0.55–0.72 (electric, energized)
  storm-atmosphere (15): aggression 0.75–0.92  (driving, weather-system)

Even aggressive presets should feel like a weather system, not a drum machine.
Writes to Presets/XOmnibus/Atmosphere/. Skips existing files.
"""

import json
import os
import sys

PRESET_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "Presets", "XOmnibus", "Atmosphere"
)

# ---------------------------------------------------------------------------
# Preset definitions
# (name, engine, dna_dict, parameters_dict, macro_labels, tags, description)
# ---------------------------------------------------------------------------

CALM_ATMOSPHERE = [
    (
        "Pressure Ridge",
        "Orca",
        dict(brightness=0.15, warmth=0.92, movement=0.85, density=0.88, space=0.95, aggression=0.08),
        {
            "orca_filterCutoff": 0.22,
            "orca_filterReso": 0.08,
            "orca_drive": 0.05,
            "orca_lfoRate": 0.04,
            "orca_lfoDepth": 0.65,
            "orca_echoDelay": 0.72,
            "orca_echoFeedback": 0.82,
            "orca_reverbMix": 0.88,
            "orca_ampAttack": 3.5,
            "orca_ampDecay": 2.0,
            "orca_ampSustain": 0.92,
            "orca_ampRelease": 8.0,
            "orca_macroCharacter": 0.0,
            "orca_macroMovement": 0.0,
            "orca_macroCoupling": 0.0,
            "orca_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "calm", "deep", "pressure", "vast"],
        "Whale-song pressure ridge — warmth maxed, space infinite. Aggression near zero but movement and density create a sense of immense slow force."
    ),
    (
        "Thermocline",
        "Ouroboros",
        dict(brightness=0.35, warmth=0.78, movement=0.72, density=0.92, space=0.88, aggression=0.07),
        {
            "ouro_topology": 0,
            "ouro_rate": 220.0,
            "ouro_chaosIndex": 0.12,
            "ouro_leash": 0.88,
            "ouro_theta": 0.35,
            "ouro_phi": 0.55,
            "ouro_damping": 0.88,
            "ouro_injection": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "calm", "ouroboros", "thermocline", "deep"],
        "Lorenz trajectory at near-zero chaos — the attractor traces its path so slowly it reads as a breathing drone. Temperature boundary: dense below, open above."
    ),
    (
        "Fog Column",
        "Origami",
        dict(brightness=0.28, warmth=0.82, movement=0.65, density=0.95, space=0.75, aggression=0.09),
        {
            "origami_foldPoint": 0.55,
            "origami_foldAmt": 0.72,
            "origami_layers": 7,
            "origami_symmetry": 0.85,
            "origami_filterCutoff": 0.32,
            "origami_filterReso": 0.08,
            "origami_oscPitch": 0.0,
            "origami_ampAttack": 3.0,
            "origami_ampDecay": 1.5,
            "origami_ampSustain": 0.95,
            "origami_ampRelease": 7.0
        },
        ["CHARACTER", "FOLD", "COUPLING", "SPACE"],
        ["atmosphere", "calm", "fog", "dense", "warm"],
        "Seven fold layers at high symmetry — even harmonics dominate. The fold point sits high, creating a warm, rounded density. A fog column rising in still air."
    ),
    (
        "Mantle Convection",
        "Orbital",
        dict(brightness=0.22, warmth=0.88, movement=0.78, density=0.72, space=0.96, aggression=0.06),
        {
            "orb_brightness": 0.25,
            "orb_groupEnvRate": 0.03,
            "orb_groupEnvDepth": 0.85,
            "orb_oscCount": 16,
            "orb_spread": 0.92,
            "orb_detune": 0.18,
            "orb_filterCutoff": 0.35,
            "orb_filterReso": 0.05,
            "orb_ampAttack": 4.0,
            "orb_ampDecay": 2.0,
            "orb_ampSustain": 0.88,
            "orb_ampRelease": 10.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "calm", "orbital", "mantle", "geological"],
        "Sixteen oscillators at near-zero group envelope rate — vast geological time. Movement is real but takes minutes to perceive. The deep interior in motion."
    ),
    (
        "Abyssal Warmth",
        "Oblique",
        dict(brightness=0.18, warmth=0.95, movement=0.55, density=0.82, space=0.88, aggression=0.10),
        {
            "oblq_oscWave": 3,
            "oblq_oscFold": 0.08,
            "oblq_oscDetune": 5.0,
            "oblq_level": 0.72,
            "oblq_glide": 0.85,
            "oblq_percClick": 0.0,
            "oblq_percDecay": 0.01,
            "oblq_bounceRate": 1200.0,
            "oblq_bounceGravity": 0.15,
            "oblq_bounceDamp": 0.98,
            "oblq_bounceCnt": 3.0,
            "oblq_bounceSwing": 0.02,
            "oblq_clickTone": 200.0,
            "oblq_filterCut": 600.0,
            "oblq_filterRes": 0.04,
            "oblq_attack": 3.0,
            "oblq_decay": 5.0,
            "oblq_sustain": 0.95,
            "oblq_release": 9.0,
            "oblq_prismDelay": 800.0,
            "oblq_prismSpread": 0.88,
            "oblq_prismColor": 0.45,
            "oblq_prismWidth": 0.92,
            "oblq_prismFeedback": 0.72,
            "oblq_prismMix": 0.65,
            "oblq_prismDamp": 0.78,
            "oblq_phaserRate": 0.01,
            "oblq_phaserDepth": 0.55,
            "oblq_phaserFeedback": 0.45,
            "oblq_phaserMix": 0.5
        },
        ["SPACE", "FOLD", "PRISM DEPTH", "FILTER"],
        ["atmosphere", "calm", "oblique", "warm", "deep"],
        "Sine-adjacent wave with minimal fold, massive prism spread at low color. Three slow bounces ripple through deep reverb. Warmth as a physical property of deep water."
    ),
    (
        "Still Water Column",
        "Outwit",
        dict(brightness=0.42, warmth=0.68, movement=0.82, density=0.72, space=0.92, aggression=0.12),
        {
            "owit_rule": 110,
            "owit_armBalance": 0.65,
            "owit_mutationRate": 0.15,
            "owit_armSpread": 0.88,
            "owit_sync": 0.25,
            "owit_feedbackAmt": 0.05,
            "owit_chaos": 0.12,
            "owit_density": 0.35,
            "owit_ampAttack": 1.8,
            "owit_ampDecay": 2.5,
            "owit_ampSustain": 0.78,
            "owit_ampRelease": 7.0,
            "owit_filterCutoff": 0.55,
            "owit_filterRes": 0.12,
            "owit_lfoRate": 0.02,
            "owit_lfoDepth": 0.22,
            "owit_macroCharacter": 0.0,
            "owit_macroChaos": 0.0,
            "owit_macroCoupling": 0.0,
            "owit_macroSpace": 0.0
        },
        ["CHARACTER", "CHAOS", "COUPLING", "SPACE"],
        ["atmosphere", "calm", "outwit", "still", "cellular"],
        "Rule 110 — universally complex but visually still. Low mutation, high arm balance. Eight arms in equilibrium, each column shifting imperceptibly. The water column in thermodynamic rest."
    ),
    (
        "Bioluminescent Calm",
        "Optic",
        dict(brightness=0.72, warmth=0.45, movement=0.78, density=0.55, space=0.92, aggression=0.11),
        {
            "optic_reactivity": 0.35,
            "optic_inputGain": 0.6,
            "optic_autoPulse": 1,
            "optic_pulseRate": 0.06,
            "optic_pulseShape": 0.85,
            "optic_pulseSwing": 0.0,
            "optic_pulseEvolve": 0.72,
            "optic_pulseSubdiv": 0.15,
            "optic_pulseAccent": 0.22,
            "optic_modDepth": 0.38,
            "optic_modMixPulse": 0.45,
            "optic_modMixSpec": 0.62,
            "optic_vizMode": 2,
            "optic_vizFeedback": 0.82,
            "optic_vizSpeed": 0.08,
            "optic_vizIntensity": 0.35
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "calm", "optic", "bioluminescent", "glow"],
        "Pulse rate at geological pace, evolve at maximum — the pulse shape drifts over long periods. Feedback accumulates like light in deep water. Glowing calm."
    ),
    (
        "Deep Time",
        "Overworld",
        dict(brightness=0.38, warmth=0.72, movement=0.75, density=0.85, space=0.88, aggression=0.09),
        {
            "ow_eraBalance": 0.15,
            "ow_voiceCount": 8,
            "ow_spread": 0.82,
            "ow_detune": 0.12,
            "ow_filterCutoff": 0.38,
            "ow_filterReso": 0.08,
            "ow_glitchRate": 0.0,
            "ow_glitchDepth": 0.0,
            "ow_glitchType": 0,
            "ow_ampAttack": 2.5,
            "ow_ampDecay": 1.5,
            "ow_ampSustain": 0.88,
            "ow_ampRelease": 8.0,
            "ow_reverbMix": 0.72,
            "ow_macroCharacter": 0.0,
            "ow_macroMovement": 0.0,
            "ow_macroCoupling": 0.0,
            "ow_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "calm", "overworld", "era", "deep-time"],
        "ERA triangle at NES corner — pure chip warmth with zero glitch. Eight voices spread wide, detuned minimally. Movement comes from era drift: geological, not rhythmic."
    ),
    (
        "Crevasse Hymn",
        "Oblique",
        dict(brightness=0.25, warmth=0.88, movement=0.68, density=0.78, space=0.98, aggression=0.13),
        {
            "oblq_oscWave": 1,
            "oblq_oscFold": 0.22,
            "oblq_oscDetune": 8.0,
            "oblq_level": 0.68,
            "oblq_glide": 0.78,
            "oblq_percClick": 0.0,
            "oblq_percDecay": 0.01,
            "oblq_bounceRate": 2000.0,
            "oblq_bounceGravity": 0.08,
            "oblq_bounceDamp": 0.99,
            "oblq_bounceCnt": 2.0,
            "oblq_bounceSwing": 0.0,
            "oblq_clickTone": 300.0,
            "oblq_filterCut": 850.0,
            "oblq_filterRes": 0.06,
            "oblq_attack": 4.5,
            "oblq_decay": 6.0,
            "oblq_sustain": 0.98,
            "oblq_release": 12.0,
            "oblq_prismDelay": 600.0,
            "oblq_prismSpread": 0.98,
            "oblq_prismColor": 0.38,
            "oblq_prismWidth": 0.98,
            "oblq_prismFeedback": 0.85,
            "oblq_prismMix": 0.78,
            "oblq_prismDamp": 0.82,
            "oblq_phaserRate": 0.008,
            "oblq_phaserDepth": 0.72,
            "oblq_phaserFeedback": 0.55,
            "oblq_phaserMix": 0.58
        },
        ["SPACE", "FOLD", "PRISM DEPTH", "FILTER"],
        ["atmosphere", "calm", "oblique", "hymn", "crevasse", "vast"],
        "Triangle wave, minimal fold, two slow prism bounces across maximum spread. Release of 12 seconds — notes dissolve into the space they were born in. Singing ice."
    ),
    (
        "Sargasso Stillness",
        "Origami",
        dict(brightness=0.32, warmth=0.75, movement=0.88, density=0.65, space=0.95, aggression=0.14),
        {
            "origami_foldPoint": 0.28,
            "origami_foldAmt": 0.45,
            "origami_layers": 4,
            "origami_symmetry": 0.62,
            "origami_filterCutoff": 0.42,
            "origami_filterReso": 0.15,
            "origami_oscPitch": 0.0,
            "origami_ampAttack": 2.8,
            "origami_ampDecay": 2.0,
            "origami_ampSustain": 0.88,
            "origami_ampRelease": 9.0
        },
        ["CHARACTER", "FOLD", "COUPLING", "SPACE"],
        ["atmosphere", "calm", "origami", "stillness", "sargasso"],
        "Four fold layers at mid symmetry — balanced harmonic blend. Low fold point creates soft lower-harmonic emphasis. Movement comes from layer phase drift. Still at the centre of the gyre."
    ),
]

TENSE_ATMOSPHERE = [
    (
        "Fault Line",
        "Orca",
        dict(brightness=0.42, warmth=0.35, movement=0.62, density=0.78, space=0.72, aggression=0.38),
        {
            "orca_filterCutoff": 0.52,
            "orca_filterReso": 0.55,
            "orca_drive": 0.38,
            "orca_lfoRate": 0.18,
            "orca_lfoDepth": 0.72,
            "orca_echoDelay": 0.58,
            "orca_echoFeedback": 0.55,
            "orca_reverbMix": 0.62,
            "orca_ampAttack": 0.8,
            "orca_ampDecay": 1.2,
            "orca_ampSustain": 0.72,
            "orca_ampRelease": 4.0,
            "orca_macroCharacter": 0.0,
            "orca_macroMovement": 0.0,
            "orca_macroCoupling": 0.0,
            "orca_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "tense", "orca", "fault-line", "seismic"],
        "Filter resonance elevated, drive beginning to bite. LFO introduces irregular movement — not rhythm but unease. The tectonic plates are touching."
    ),
    (
        "Pressure Front",
        "Ouroboros",
        dict(brightness=0.48, warmth=0.42, movement=0.55, density=0.72, space=0.68, aggression=0.42),
        {
            "ouro_topology": 1,
            "ouro_rate": 330.0,
            "ouro_chaosIndex": 0.48,
            "ouro_leash": 0.55,
            "ouro_theta": 0.65,
            "ouro_phi": 0.42,
            "ouro_damping": 0.52,
            "ouro_injection": 0.12
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "tense", "ouroboros", "pressure", "front"],
        "Lorenz approaching chaos threshold — leash at 0.55 allows meaningful orbit deviation. Injection adds micro-turbulence. A weather front arriving from the wrong direction."
    ),
    (
        "Origami Threat",
        "Origami",
        dict(brightness=0.55, warmth=0.28, movement=0.58, density=0.82, space=0.55, aggression=0.45),
        {
            "origami_foldPoint": 0.35,
            "origami_foldAmt": 0.78,
            "origami_layers": 6,
            "origami_symmetry": 0.18,
            "origami_filterCutoff": 0.58,
            "origami_filterReso": 0.42,
            "origami_oscPitch": 0.0,
            "origami_ampAttack": 0.6,
            "origami_ampDecay": 0.8,
            "origami_ampSustain": 0.75,
            "origami_ampRelease": 3.5
        },
        ["CHARACTER", "FOLD", "COUPLING", "SPACE"],
        ["atmosphere", "tense", "origami", "threat", "odd-harmonic"],
        "Six layers at low symmetry — odd harmonics dominate, creating edge and dissonance. High fold amount folds the wave sharply. Not violent but wrong. Paper folding against its grain."
    ),
    (
        "Oblong Warning",
        "Oblong",
        dict(brightness=0.58, warmth=0.32, movement=0.52, density=0.68, space=0.58, aggression=0.48),
        {
            "bob_oscWave": 1,
            "bob_oscDetune": 0.38,
            "bob_fltCutoff": 0.55,
            "bob_fltReso": 0.62,
            "bob_drive": 0.42,
            "bob_lfo1Rate": 0.22,
            "bob_lfo1Depth": 0.48,
            "bob_ampAttack": 0.5,
            "bob_ampDecay": 0.8,
            "bob_ampSustain": 0.72,
            "bob_ampRelease": 3.0,
            "bob_macroCharacter": 0.0,
            "bob_macroMovement": 0.0,
            "bob_macroCoupling": 0.0,
            "bob_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "tense", "oblong", "warning", "detuned"],
        "Square wave with meaningful detune — the beating is present but slow, like a signal slightly off frequency. Filter resonance adds harmonic edge. An alarm being ignored."
    ),
    (
        "Turbulent Onset",
        "Onset",
        dict(brightness=0.52, warmth=0.38, movement=0.72, density=0.55, space=0.68, aggression=0.40),
        {
            "perc_v1_blend": 0.55,
            "perc_v1_algoMode": 2,
            "perc_v1_pitch": 0,
            "perc_v1_decay": 0.8,
            "perc_v1_tone": 0.42,
            "perc_v1_snap": 0.35,
            "perc_v1_body": 0.55,
            "perc_v1_character": 0.25,
            "perc_v1_level": 0.62,
            "perc_v1_pan": 0.0,
            "perc_v1_envShape": 1,
            "perc_v3_blend": 0.35,
            "perc_v3_algoMode": 1,
            "perc_v3_pitch": 0,
            "perc_v3_decay": 0.12,
            "perc_v3_tone": 0.48,
            "perc_v3_snap": 0.42,
            "perc_v3_body": 0.45,
            "perc_v3_character": 0.15,
            "perc_v3_level": 0.52,
            "perc_v3_pan": 0.15,
            "perc_v3_envShape": 0,
            "perc_v5_blend": 0.42,
            "perc_v5_algoMode": 3,
            "perc_v5_pitch": 0,
            "perc_v5_decay": 0.45,
            "perc_v5_tone": 0.55,
            "perc_v5_snap": 0.28,
            "perc_v5_body": 0.52,
            "perc_v5_character": 0.18,
            "perc_v5_level": 0.55,
            "perc_v5_pan": -0.12,
            "perc_v5_envShape": 0,
            "perc_level": 0.65,
            "perc_drive": 0.25,
            "perc_masterTone": 0.52,
            "perc_macro_machine": 0.48,
            "perc_macro_punch": 0.45,
            "perc_macro_space": 0.38,
            "perc_macro_mutate": 0.55,
            "perc_xvc_kick_to_snare_filter": 0.22,
            "perc_xvc_snare_to_hat_decay": 0.18,
            "perc_xvc_kick_to_tom_pitch": 0.05,
            "perc_xvc_snare_to_perc_blend": 0.08,
            "perc_xvc_hat_choke": 0.65,
            "perc_xvc_global_amount": 0.35,
            "perc_char_grit": 0.22,
            "perc_char_warmth": 0.42,
            "perc_fx_delay_time": 0.55,
            "perc_fx_delay_feedback": 0.42,
            "perc_fx_delay_mix": 0.28,
            "perc_fx_reverb_size": 0.65,
            "perc_fx_reverb_decay": 0.55,
            "perc_fx_reverb_mix": 0.48,
            "perc_fx_lofi_bits": 14.0,
            "perc_fx_lofi_mix": 0.12
        },
        ["MACHINE", "PUNCH", "SPACE", "MUTATE"],
        ["atmosphere", "tense", "onset", "turbulence", "storm-edge"],
        "Onset voices set to organic decay shapes with mid grit. Not playing a beat — three voices firing at unpredictable intervals like debris in wind. The feeling before a storm."
    ),
    (
        "Magnetic Interference",
        "Optic",
        dict(brightness=0.65, warmth=0.25, movement=0.68, density=0.62, space=0.72, aggression=0.45),
        {
            "optic_reactivity": 0.55,
            "optic_inputGain": 0.85,
            "optic_autoPulse": 1,
            "optic_pulseRate": 0.35,
            "optic_pulseShape": 0.45,
            "optic_pulseSwing": 0.18,
            "optic_pulseEvolve": 0.55,
            "optic_pulseSubdiv": 0.52,
            "optic_pulseAccent": 0.58,
            "optic_modDepth": 0.62,
            "optic_modMixPulse": 0.58,
            "optic_modMixSpec": 0.48,
            "optic_vizMode": 1,
            "optic_vizFeedback": 0.62,
            "optic_vizSpeed": 0.48,
            "optic_vizIntensity": 0.58
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "tense", "optic", "interference", "magnetic"],
        "AutoPulse at moderate rate with swing — the pulse is irregular, slightly wrong. Reactivity elevated, feedback accumulating. A screen with bad signal from a distant source."
    ),
    (
        "Thermocline Break",
        "Outwit",
        dict(brightness=0.48, warmth=0.38, movement=0.65, density=0.68, space=0.62, aggression=0.48),
        {
            "owit_rule": 30,
            "owit_armBalance": 0.52,
            "owit_mutationRate": 0.45,
            "owit_armSpread": 0.72,
            "owit_sync": 0.35,
            "owit_feedbackAmt": 0.28,
            "owit_chaos": 0.48,
            "owit_density": 0.55,
            "owit_ampAttack": 0.4,
            "owit_ampDecay": 1.2,
            "owit_ampSustain": 0.58,
            "owit_ampRelease": 3.5,
            "owit_filterCutoff": 0.62,
            "owit_filterRes": 0.45,
            "owit_lfoRate": 0.08,
            "owit_lfoDepth": 0.42,
            "owit_macroCharacter": 0.0,
            "owit_macroChaos": 0.0,
            "owit_macroCoupling": 0.0,
            "owit_macroSpace": 0.0
        },
        ["CHARACTER", "CHAOS", "COUPLING", "SPACE"],
        ["atmosphere", "tense", "outwit", "thermocline", "break"],
        "Rule 30 at mid chaos — genuinely unpredictable output. Arms partially desynchronized, feedback building. The water layers beginning to mix against their nature."
    ),
    (
        "Solar Wind",
        "Orbital",
        dict(brightness=0.62, warmth=0.28, movement=0.58, density=0.72, space=0.78, aggression=0.42),
        {
            "orb_brightness": 0.65,
            "orb_groupEnvRate": 0.35,
            "orb_groupEnvDepth": 0.72,
            "orb_oscCount": 8,
            "orb_spread": 0.68,
            "orb_detune": 0.38,
            "orb_filterCutoff": 0.62,
            "orb_filterReso": 0.38,
            "orb_ampAttack": 0.5,
            "orb_ampDecay": 1.2,
            "orb_ampSustain": 0.65,
            "orb_ampRelease": 4.5
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "tense", "orbital", "solar-wind", "charged"],
        "Eight oscillators at elevated detune, group envelope fluctuating at moderate rate. Spread allows voices to interfere. Not storm — charged particle stream. The quiet danger of radiation."
    ),
    (
        "Mirage Layer",
        "Overworld",
        dict(brightness=0.58, warmth=0.35, movement=0.62, density=0.68, space=0.72, aggression=0.35),
        {
            "ow_eraBalance": 0.55,
            "ow_voiceCount": 6,
            "ow_spread": 0.62,
            "ow_detune": 0.35,
            "ow_filterCutoff": 0.55,
            "ow_filterReso": 0.35,
            "ow_glitchRate": 0.18,
            "ow_glitchDepth": 0.35,
            "ow_glitchType": 2,
            "ow_ampAttack": 0.8,
            "ow_ampDecay": 1.0,
            "ow_ampSustain": 0.72,
            "ow_ampRelease": 4.0,
            "ow_reverbMix": 0.55,
            "ow_macroCharacter": 0.0,
            "ow_macroMovement": 0.0,
            "ow_macroCoupling": 0.0,
            "ow_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "tense", "overworld", "mirage", "glitch"],
        "ERA balanced between two systems, glitch rate introduces occasional bit-corruption. Six voices — not quite enough to fill the space. Something is being concealed behind the surface."
    ),
    (
        "Static Front",
        "Oblique",
        dict(brightness=0.52, warmth=0.32, movement=0.55, density=0.75, space=0.65, aggression=0.50),
        {
            "oblq_oscWave": 2,
            "oblq_oscFold": 0.45,
            "oblq_oscDetune": 18.0,
            "oblq_level": 0.72,
            "oblq_glide": 0.45,
            "oblq_percClick": 0.08,
            "oblq_percDecay": 0.05,
            "oblq_bounceRate": 450.0,
            "oblq_bounceGravity": 0.42,
            "oblq_bounceDamp": 0.88,
            "oblq_bounceCnt": 5.0,
            "oblq_bounceSwing": 0.12,
            "oblq_clickTone": 1200.0,
            "oblq_filterCut": 2200.0,
            "oblq_filterRes": 0.38,
            "oblq_attack": 0.4,
            "oblq_decay": 1.5,
            "oblq_sustain": 0.72,
            "oblq_release": 4.0,
            "oblq_prismDelay": 280.0,
            "oblq_prismSpread": 0.72,
            "oblq_prismColor": 0.65,
            "oblq_prismWidth": 0.78,
            "oblq_prismFeedback": 0.68,
            "oblq_prismMix": 0.58,
            "oblq_prismDamp": 0.45,
            "oblq_phaserRate": 0.12,
            "oblq_phaserDepth": 0.72,
            "oblq_phaserFeedback": 0.58,
            "oblq_phaserMix": 0.62
        },
        ["SPACE", "FOLD", "PRISM DEPTH", "FILTER"],
        ["atmosphere", "tense", "oblique", "static", "charged-air"],
        "Sawtooth with meaningful fold, five bounces at mid gravity. Prism color elevated — the refracted frequencies carry edge. An approaching electrical front: the air before lightning."
    ),
]

CHARGED_ATMOSPHERE = [
    (
        "Lightning Shelf",
        "Overworld",
        dict(brightness=0.78, warmth=0.22, movement=0.72, density=0.68, space=0.75, aggression=0.58),
        {
            "ow_eraBalance": 0.72,
            "ow_voiceCount": 8,
            "ow_spread": 0.72,
            "ow_detune": 0.48,
            "ow_filterCutoff": 0.72,
            "ow_filterReso": 0.55,
            "ow_glitchRate": 0.38,
            "ow_glitchDepth": 0.55,
            "ow_glitchType": 1,
            "ow_ampAttack": 0.3,
            "ow_ampDecay": 0.8,
            "ow_ampSustain": 0.68,
            "ow_ampRelease": 3.5,
            "ow_reverbMix": 0.62,
            "ow_macroCharacter": 0.0,
            "ow_macroMovement": 0.0,
            "ow_macroCoupling": 0.0,
            "ow_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "overworld", "lightning", "shelf-cloud"],
        "ERA pushed toward Genesis — richer harmonics. Glitch rate creates periodic bit-corruption like lightning strikes. Eight voices in electric tension. The shelf cloud building to the west."
    ),
    (
        "Optic Storm Cell",
        "Optic",
        dict(brightness=0.88, warmth=0.15, movement=0.78, density=0.72, space=0.62, aggression=0.65),
        {
            "optic_reactivity": 0.78,
            "optic_inputGain": 1.0,
            "optic_autoPulse": 1,
            "optic_pulseRate": 0.62,
            "optic_pulseShape": 0.58,
            "optic_pulseSwing": 0.28,
            "optic_pulseEvolve": 0.72,
            "optic_pulseSubdiv": 0.68,
            "optic_pulseAccent": 0.75,
            "optic_modDepth": 0.82,
            "optic_modMixPulse": 0.72,
            "optic_modMixSpec": 0.65,
            "optic_vizMode": 3,
            "optic_vizFeedback": 0.78,
            "optic_vizSpeed": 0.72,
            "optic_vizIntensity": 0.82
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "optic", "storm-cell", "electric"],
        "High reactivity, evolving pulse at charged rate. Visual feedback approaching saturation. Not noise yet — the system is still coherent. Inside the storm cell before it collapses."
    ),
    (
        "Oblique Charged Front",
        "Oblique",
        dict(brightness=0.72, warmth=0.25, movement=0.68, density=0.78, space=0.68, aggression=0.60),
        {
            "oblq_oscWave": 4,
            "oblq_oscFold": 0.65,
            "oblq_oscDetune": 28.0,
            "oblq_level": 0.78,
            "oblq_glide": 0.35,
            "oblq_percClick": 0.12,
            "oblq_percDecay": 0.08,
            "oblq_bounceRate": 320.0,
            "oblq_bounceGravity": 0.62,
            "oblq_bounceDamp": 0.78,
            "oblq_bounceCnt": 8.0,
            "oblq_bounceSwing": 0.22,
            "oblq_clickTone": 1800.0,
            "oblq_filterCut": 3500.0,
            "oblq_filterRes": 0.58,
            "oblq_attack": 0.2,
            "oblq_decay": 0.8,
            "oblq_sustain": 0.65,
            "oblq_release": 3.5,
            "oblq_prismDelay": 180.0,
            "oblq_prismSpread": 0.88,
            "oblq_prismColor": 0.82,
            "oblq_prismWidth": 0.92,
            "oblq_prismFeedback": 0.82,
            "oblq_prismMix": 0.72,
            "oblq_prismDamp": 0.32,
            "oblq_phaserRate": 0.35,
            "oblq_phaserDepth": 0.88,
            "oblq_phaserFeedback": 0.75,
            "oblq_phaserMix": 0.72
        },
        ["SPACE", "FOLD", "PRISM DEPTH", "FILTER"],
        ["atmosphere", "charged", "oblique", "electric-front", "prism"],
        "Eight bounces at high gravity, low damping — the echo cascade is energetic. Fold amount creating real harmonic aggression within the prism space. Atmosphere as charged particle field."
    ),
    (
        "Orbital Charge Ring",
        "Orbital",
        dict(brightness=0.72, warmth=0.22, movement=0.75, density=0.82, space=0.65, aggression=0.62),
        {
            "orb_brightness": 0.75,
            "orb_groupEnvRate": 0.58,
            "orb_groupEnvDepth": 0.82,
            "orb_oscCount": 12,
            "orb_spread": 0.82,
            "orb_detune": 0.52,
            "orb_filterCutoff": 0.72,
            "orb_filterReso": 0.52,
            "orb_ampAttack": 0.25,
            "orb_ampDecay": 0.8,
            "orb_ampSustain": 0.62,
            "orb_ampRelease": 3.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "orbital", "ring", "electric"],
        "Twelve oscillators at significant detune, group envelope oscillating at charged rate. Voice interference creates beating patterns. Not static anymore — the ring is energized."
    ),
    (
        "Onset Gale",
        "Onset",
        dict(brightness=0.62, warmth=0.28, movement=0.82, density=0.72, space=0.58, aggression=0.68),
        {
            "perc_v1_blend": 0.72,
            "perc_v1_algoMode": 2,
            "perc_v1_pitch": 0,
            "perc_v1_decay": 0.55,
            "perc_v1_tone": 0.65,
            "perc_v1_snap": 0.55,
            "perc_v1_body": 0.62,
            "perc_v1_character": 0.42,
            "perc_v1_level": 0.72,
            "perc_v1_pan": 0.0,
            "perc_v1_envShape": 1,
            "perc_v2_blend": 0.55,
            "perc_v2_algoMode": 0,
            "perc_v2_pitch": 0,
            "perc_v2_decay": 0.35,
            "perc_v2_tone": 0.58,
            "perc_v2_snap": 0.48,
            "perc_v2_body": 0.55,
            "perc_v2_character": 0.35,
            "perc_v2_level": 0.65,
            "perc_v2_pan": 0.2,
            "perc_v2_envShape": 0,
            "perc_v4_blend": 0.62,
            "perc_v4_algoMode": 3,
            "perc_v4_pitch": 0,
            "perc_v4_decay": 0.42,
            "perc_v4_tone": 0.62,
            "perc_v4_snap": 0.52,
            "perc_v4_body": 0.58,
            "perc_v4_character": 0.38,
            "perc_v4_level": 0.68,
            "perc_v4_pan": -0.2,
            "perc_v4_envShape": 1,
            "perc_v6_blend": 0.48,
            "perc_v6_algoMode": 1,
            "perc_v6_pitch": 0,
            "perc_v6_decay": 0.28,
            "perc_v6_tone": 0.55,
            "perc_v6_snap": 0.42,
            "perc_v6_body": 0.52,
            "perc_v6_character": 0.28,
            "perc_v6_level": 0.62,
            "perc_v6_pan": 0.1,
            "perc_v6_envShape": 0,
            "perc_level": 0.75,
            "perc_drive": 0.45,
            "perc_masterTone": 0.62,
            "perc_macro_machine": 0.65,
            "perc_macro_punch": 0.62,
            "perc_macro_space": 0.48,
            "perc_macro_mutate": 0.72,
            "perc_xvc_kick_to_snare_filter": 0.38,
            "perc_xvc_snare_to_hat_decay": 0.32,
            "perc_xvc_kick_to_tom_pitch": 0.18,
            "perc_xvc_snare_to_perc_blend": 0.22,
            "perc_xvc_hat_choke": 0.55,
            "perc_xvc_global_amount": 0.58,
            "perc_char_grit": 0.42,
            "perc_char_warmth": 0.28,
            "perc_fx_delay_time": 0.48,
            "perc_fx_delay_feedback": 0.55,
            "perc_fx_delay_mix": 0.42,
            "perc_fx_reverb_size": 0.72,
            "perc_fx_reverb_decay": 0.65,
            "perc_fx_reverb_mix": 0.55,
            "perc_fx_lofi_bits": 12.0,
            "perc_fx_lofi_mix": 0.22
        },
        ["MACHINE", "PUNCH", "SPACE", "MUTATE"],
        ["atmosphere", "charged", "onset", "gale", "wind"],
        "Four active voices at high character and drive, XVC cross-coupling elevated. Not a groove — a gale: objects hitting walls in sequence. Onset as weather system, not drummer."
    ),
    (
        "Arc Discharge",
        "Orca",
        dict(brightness=0.82, warmth=0.18, movement=0.72, density=0.78, space=0.58, aggression=0.70),
        {
            "orca_filterCutoff": 0.82,
            "orca_filterReso": 0.78,
            "orca_drive": 0.65,
            "orca_lfoRate": 0.45,
            "orca_lfoDepth": 0.85,
            "orca_echoDelay": 0.42,
            "orca_echoFeedback": 0.68,
            "orca_reverbMix": 0.52,
            "orca_ampAttack": 0.15,
            "orca_ampDecay": 0.8,
            "orca_ampSustain": 0.58,
            "orca_ampRelease": 3.0,
            "orca_macroCharacter": 0.0,
            "orca_macroMovement": 0.0,
            "orca_macroCoupling": 0.0,
            "orca_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "orca", "arc", "discharge"],
        "High filter resonance approaching self-oscillation, drive creating harmonic multiplication. LFO sweeps aggressively. An electric arc that shapes into atmosphere only via the reverb tail."
    ),
    (
        "Ouroboros Charged Loop",
        "Ouroboros",
        dict(brightness=0.65, warmth=0.25, movement=0.78, density=0.72, space=0.62, aggression=0.58),
        {
            "ouro_topology": 2,
            "ouro_rate": 440.0,
            "ouro_chaosIndex": 0.65,
            "ouro_leash": 0.38,
            "ouro_theta": 0.82,
            "ouro_phi": 0.28,
            "ouro_damping": 0.35,
            "ouro_injection": 0.28
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "ouroboros", "loop", "attractor"],
        "Chaos index at 0.65, leash partially released — the trajectory range is wide. Low damping means energy stays in the system. Injection adds periodic forcing. A charged orbit."
    ),
    (
        "Outwit Electric Arms",
        "Outwit",
        dict(brightness=0.72, warmth=0.22, movement=0.82, density=0.75, space=0.62, aggression=0.65),
        {
            "owit_rule": 73,
            "owit_armBalance": 0.42,
            "owit_mutationRate": 0.68,
            "owit_armSpread": 0.82,
            "owit_sync": 0.55,
            "owit_feedbackAmt": 0.52,
            "owit_chaos": 0.68,
            "owit_density": 0.72,
            "owit_ampAttack": 0.2,
            "owit_ampDecay": 0.8,
            "owit_ampSustain": 0.58,
            "owit_ampRelease": 3.0,
            "owit_filterCutoff": 0.78,
            "owit_filterRes": 0.62,
            "owit_lfoRate": 0.28,
            "owit_lfoDepth": 0.65,
            "owit_macroCharacter": 0.0,
            "owit_macroChaos": 0.0,
            "owit_macroCoupling": 0.0,
            "owit_macroSpace": 0.0
        },
        ["CHARACTER", "CHAOS", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "outwit", "electric", "arms"],
        "Rule 73 with high mutation — arms flickering with CA-computed randomness. High feedback and density. Still atmosphere — the space charge before breakdown."
    ),
    (
        "Origami Charged",
        "Origami",
        dict(brightness=0.68, warmth=0.22, movement=0.72, density=0.88, space=0.62, aggression=0.62),
        {
            "origami_foldPoint": 0.22,
            "origami_foldAmt": 0.88,
            "origami_layers": 8,
            "origami_symmetry": 0.08,
            "origami_filterCutoff": 0.72,
            "origami_filterReso": 0.55,
            "origami_oscPitch": 0.0,
            "origami_ampAttack": 0.3,
            "origami_ampDecay": 0.8,
            "origami_ampSustain": 0.65,
            "origami_ampRelease": 3.5
        },
        ["CHARACTER", "FOLD", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "origami", "electric-fold", "odd-harmonic"],
        "Eight layers at near-zero symmetry — maximum odd harmonic content. High fold amount, low fold point cuts into the wave aggressively. Dense, buzzing, charged atmospheric texture."
    ),
    (
        "Overworld Static Layer",
        "Overworld",
        dict(brightness=0.82, warmth=0.15, movement=0.75, density=0.72, space=0.68, aggression=0.72),
        {
            "ow_eraBalance": 0.88,
            "ow_voiceCount": 10,
            "ow_spread": 0.78,
            "ow_detune": 0.58,
            "ow_filterCutoff": 0.82,
            "ow_filterReso": 0.65,
            "ow_glitchRate": 0.55,
            "ow_glitchDepth": 0.72,
            "ow_glitchType": 3,
            "ow_ampAttack": 0.2,
            "ow_ampDecay": 0.6,
            "ow_ampSustain": 0.58,
            "ow_ampRelease": 3.0,
            "ow_reverbMix": 0.55,
            "ow_macroCharacter": 0.0,
            "ow_macroMovement": 0.0,
            "ow_macroCoupling": 0.0,
            "ow_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "overworld", "static", "glitch-field"],
        "ERA pushed near Genesis maximum, glitch rate creating dense corruption field. Ten voices in the mix — not clean, not broken. The atmosphere of a failing system that still functions."
    ),
    (
        "Oblique Prism Surge",
        "Oblique",
        dict(brightness=0.78, warmth=0.18, movement=0.78, density=0.82, space=0.72, aggression=0.68),
        {
            "oblq_oscWave": 2,
            "oblq_oscFold": 0.75,
            "oblq_oscDetune": 35.0,
            "oblq_level": 0.82,
            "oblq_glide": 0.25,
            "oblq_percClick": 0.18,
            "oblq_percDecay": 0.12,
            "oblq_bounceRate": 250.0,
            "oblq_bounceGravity": 0.75,
            "oblq_bounceDamp": 0.65,
            "oblq_bounceCnt": 11.0,
            "oblq_bounceSwing": 0.32,
            "oblq_clickTone": 2500.0,
            "oblq_filterCut": 5000.0,
            "oblq_filterRes": 0.72,
            "oblq_attack": 0.1,
            "oblq_decay": 0.5,
            "oblq_sustain": 0.58,
            "oblq_release": 3.0,
            "oblq_prismDelay": 140.0,
            "oblq_prismSpread": 0.92,
            "oblq_prismColor": 0.88,
            "oblq_prismWidth": 0.95,
            "oblq_prismFeedback": 0.88,
            "oblq_prismMix": 0.82,
            "oblq_prismDamp": 0.22,
            "oblq_phaserRate": 0.55,
            "oblq_phaserDepth": 0.92,
            "oblq_phaserFeedback": 0.82,
            "oblq_phaserMix": 0.78
        },
        ["SPACE", "FOLD", "PRISM DEPTH", "FILTER"],
        ["atmosphere", "charged", "oblique", "prism-surge", "energy"],
        "Eleven bounces at high gravity, low damping — energy surging through the prism. Fold at 0.75 creates aggressive harmonic content. Still atmosphere: not a beat, a wave breaking on itself."
    ),
    (
        "Orbital Ion Trail",
        "Orbital",
        dict(brightness=0.78, warmth=0.18, movement=0.82, density=0.78, space=0.72, aggression=0.55),
        {
            "orb_brightness": 0.82,
            "orb_groupEnvRate": 0.72,
            "orb_groupEnvDepth": 0.88,
            "orb_oscCount": 14,
            "orb_spread": 0.88,
            "orb_detune": 0.62,
            "orb_filterCutoff": 0.78,
            "orb_filterReso": 0.48,
            "orb_ampAttack": 0.15,
            "orb_ampDecay": 0.7,
            "orb_ampSustain": 0.55,
            "orb_ampRelease": 3.5
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "orbital", "ion-trail", "energized"],
        "Fourteen oscillators, group envelope rate elevated. Individual voices re-enter the mix with quick attacks. The ion trail of a charged object passing through atmosphere."
    ),
    (
        "Onset Charged Atmosphere",
        "Onset",
        dict(brightness=0.55, warmth=0.32, movement=0.88, density=0.78, space=0.62, aggression=0.70),
        {
            "perc_v1_blend": 0.82,
            "perc_v1_algoMode": 3,
            "perc_v1_pitch": 0,
            "perc_v1_decay": 0.42,
            "perc_v1_tone": 0.72,
            "perc_v1_snap": 0.65,
            "perc_v1_body": 0.68,
            "perc_v1_character": 0.55,
            "perc_v1_level": 0.78,
            "perc_v1_pan": 0.0,
            "perc_v1_envShape": 2,
            "perc_v3_blend": 0.68,
            "perc_v3_algoMode": 2,
            "perc_v3_pitch": 0,
            "perc_v3_decay": 0.28,
            "perc_v3_tone": 0.68,
            "perc_v3_snap": 0.58,
            "perc_v3_body": 0.62,
            "perc_v3_character": 0.48,
            "perc_v3_level": 0.72,
            "perc_v3_pan": 0.3,
            "perc_v3_envShape": 1,
            "perc_v5_blend": 0.72,
            "perc_v5_algoMode": 0,
            "perc_v5_pitch": 0,
            "perc_v5_decay": 0.55,
            "perc_v5_tone": 0.75,
            "perc_v5_snap": 0.62,
            "perc_v5_body": 0.65,
            "perc_v5_character": 0.52,
            "perc_v5_level": 0.75,
            "perc_v5_pan": -0.3,
            "perc_v5_envShape": 1,
            "perc_v7_blend": 0.58,
            "perc_v7_algoMode": 1,
            "perc_v7_pitch": 0,
            "perc_v7_decay": 0.38,
            "perc_v7_tone": 0.65,
            "perc_v7_snap": 0.55,
            "perc_v7_body": 0.58,
            "perc_v7_character": 0.42,
            "perc_v7_level": 0.68,
            "perc_v7_pan": 0.15,
            "perc_v7_envShape": 0,
            "perc_level": 0.82,
            "perc_drive": 0.62,
            "perc_masterTone": 0.72,
            "perc_macro_machine": 0.78,
            "perc_macro_punch": 0.75,
            "perc_macro_space": 0.55,
            "perc_macro_mutate": 0.82,
            "perc_xvc_kick_to_snare_filter": 0.52,
            "perc_xvc_snare_to_hat_decay": 0.48,
            "perc_xvc_kick_to_tom_pitch": 0.32,
            "perc_xvc_snare_to_perc_blend": 0.38,
            "perc_xvc_hat_choke": 0.45,
            "perc_xvc_global_amount": 0.72,
            "perc_char_grit": 0.58,
            "perc_char_warmth": 0.18,
            "perc_fx_delay_time": 0.62,
            "perc_fx_delay_feedback": 0.65,
            "perc_fx_delay_mix": 0.55,
            "perc_fx_reverb_size": 0.78,
            "perc_fx_reverb_decay": 0.72,
            "perc_fx_reverb_mix": 0.62,
            "perc_fx_lofi_bits": 10.0,
            "perc_fx_lofi_mix": 0.35
        },
        ["MACHINE", "PUNCH", "SPACE", "MUTATE"],
        ["atmosphere", "charged", "onset", "atmospheric-percussion", "electric"],
        "Four voices with high drive and grit, XVC fully engaged. Voices bleed into each other. Not a pattern — a charged atmospheric event. Lo-fi processing keeps it textural not clinical."
    ),
    (
        "Orca Hunt",
        "Orca",
        dict(brightness=0.75, warmth=0.2, movement=0.82, density=0.82, space=0.55, aggression=0.72),
        {
            "orca_filterCutoff": 0.88,
            "orca_filterReso": 0.85,
            "orca_drive": 0.72,
            "orca_lfoRate": 0.62,
            "orca_lfoDepth": 0.88,
            "orca_echoDelay": 0.35,
            "orca_echoFeedback": 0.78,
            "orca_reverbMix": 0.48,
            "orca_ampAttack": 0.08,
            "orca_ampDecay": 0.5,
            "orca_ampSustain": 0.52,
            "orca_ampRelease": 2.5,
            "orca_macroCharacter": 0.0,
            "orca_macroMovement": 0.0,
            "orca_macroCoupling": 0.0,
            "orca_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "charged", "orca", "hunt", "echolocation"],
        "Filter near self-oscillation, drive high, LFO scanning fast. Echo feedback creates the sense of echolocation returns. The ocean before a surface strike — charged, directional."
    ),
]

STORM_ATMOSPHERE = [
    (
        "Ouroboros Storm System",
        "Ouroboros",
        dict(brightness=0.72, warmth=0.18, movement=0.88, density=0.82, space=0.62, aggression=0.82),
        {
            "ouro_topology": 3,
            "ouro_rate": 880.0,
            "ouro_chaosIndex": 0.88,
            "ouro_leash": 0.15,
            "ouro_theta": 0.92,
            "ouro_phi": 0.12,
            "ouro_damping": 0.12,
            "ouro_injection": 0.45
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "ouroboros", "system", "cyclone"],
        "Chaos index near maximum, leash near zero — trajectory free. Near-zero damping keeps energy circulating. Injection forcing. The topology of a cyclone: rotating, self-sustaining, destructive."
    ),
    (
        "Onset Storm Surge",
        "Onset",
        dict(brightness=0.65, warmth=0.22, movement=0.92, density=0.88, space=0.55, aggression=0.88),
        {
            "perc_v1_blend": 0.92,
            "perc_v1_algoMode": 3,
            "perc_v1_pitch": 0,
            "perc_v1_decay": 0.35,
            "perc_v1_tone": 0.82,
            "perc_v1_snap": 0.78,
            "perc_v1_body": 0.72,
            "perc_v1_character": 0.72,
            "perc_v1_level": 0.88,
            "perc_v1_pan": 0.0,
            "perc_v1_envShape": 2,
            "perc_v2_blend": 0.78,
            "perc_v2_algoMode": 2,
            "perc_v2_pitch": 0,
            "perc_v2_decay": 0.22,
            "perc_v2_tone": 0.78,
            "perc_v2_snap": 0.72,
            "perc_v2_body": 0.65,
            "perc_v2_character": 0.65,
            "perc_v2_level": 0.82,
            "perc_v2_pan": 0.35,
            "perc_v2_envShape": 1,
            "perc_v3_blend": 0.85,
            "perc_v3_algoMode": 0,
            "perc_v3_pitch": 0,
            "perc_v3_decay": 0.45,
            "perc_v3_tone": 0.85,
            "perc_v3_snap": 0.82,
            "perc_v3_body": 0.75,
            "perc_v3_character": 0.68,
            "perc_v3_level": 0.85,
            "perc_v3_pan": -0.35,
            "perc_v3_envShape": 2,
            "perc_v4_blend": 0.72,
            "perc_v4_algoMode": 1,
            "perc_v4_pitch": 0,
            "perc_v4_decay": 0.28,
            "perc_v4_tone": 0.75,
            "perc_v4_snap": 0.68,
            "perc_v4_body": 0.68,
            "perc_v4_character": 0.62,
            "perc_v4_level": 0.78,
            "perc_v4_pan": 0.18,
            "perc_v4_envShape": 1,
            "perc_v5_blend": 0.88,
            "perc_v5_algoMode": 3,
            "perc_v5_pitch": 0,
            "perc_v5_decay": 0.52,
            "perc_v5_tone": 0.88,
            "perc_v5_snap": 0.75,
            "perc_v5_body": 0.78,
            "perc_v5_character": 0.75,
            "perc_v5_level": 0.88,
            "perc_v5_pan": -0.18,
            "perc_v5_envShape": 2,
            "perc_level": 0.92,
            "perc_drive": 0.82,
            "perc_masterTone": 0.82,
            "perc_macro_machine": 0.92,
            "perc_macro_punch": 0.88,
            "perc_macro_space": 0.62,
            "perc_macro_mutate": 0.88,
            "perc_xvc_kick_to_snare_filter": 0.72,
            "perc_xvc_snare_to_hat_decay": 0.65,
            "perc_xvc_kick_to_tom_pitch": 0.52,
            "perc_xvc_snare_to_perc_blend": 0.58,
            "perc_xvc_hat_choke": 0.35,
            "perc_xvc_global_amount": 0.88,
            "perc_char_grit": 0.78,
            "perc_char_warmth": 0.12,
            "perc_fx_delay_time": 0.72,
            "perc_fx_delay_feedback": 0.78,
            "perc_fx_delay_mix": 0.65,
            "perc_fx_reverb_size": 0.88,
            "perc_fx_reverb_decay": 0.82,
            "perc_fx_reverb_mix": 0.72,
            "perc_fx_lofi_bits": 8.0,
            "perc_fx_lofi_mix": 0.55
        },
        ["MACHINE", "PUNCH", "SPACE", "MUTATE"],
        ["atmosphere", "storm", "onset", "surge", "all-voices"],
        "All eight voices at high drive, grit maxed, XVC cross-coupling fully engaged. Lo-fi degradation at 8-bit keeps it textural. Not a beat — a storm surge: objects hitting everything at once."
    ),
    (
        "Overworld Storm ERA",
        "Overworld",
        dict(brightness=0.88, warmth=0.12, movement=0.88, density=0.85, space=0.55, aggression=0.85),
        {
            "ow_eraBalance": 0.95,
            "ow_voiceCount": 12,
            "ow_spread": 0.88,
            "ow_detune": 0.72,
            "ow_filterCutoff": 0.92,
            "ow_filterReso": 0.78,
            "ow_glitchRate": 0.75,
            "ow_glitchDepth": 0.88,
            "ow_glitchType": 4,
            "ow_ampAttack": 0.08,
            "ow_ampDecay": 0.4,
            "ow_ampSustain": 0.48,
            "ow_ampRelease": 2.5,
            "ow_reverbMix": 0.55,
            "ow_macroCharacter": 0.0,
            "ow_macroMovement": 0.0,
            "ow_macroCoupling": 0.0,
            "ow_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "overworld", "genesis", "glitch-storm"],
        "Near-maximum Genesis ERA, twelve voices, glitch rate creating constant corruption field. Not static — a glitch storm: the atmosphere of a world where digital law breaks down."
    ),
    (
        "Oblong Hurricane",
        "Oblong",
        dict(brightness=0.78, warmth=0.15, movement=0.88, density=0.88, space=0.48, aggression=0.78),
        {
            "bob_oscWave": 3,
            "bob_oscDetune": 0.95,
            "bob_fltCutoff": 0.88,
            "bob_fltReso": 0.92,
            "bob_drive": 0.85,
            "bob_lfo1Rate": 0.78,
            "bob_lfo1Depth": 0.88,
            "bob_ampAttack": 0.05,
            "bob_ampDecay": 0.3,
            "bob_ampSustain": 0.58,
            "bob_ampRelease": 2.5,
            "bob_macroCharacter": 0.0,
            "bob_macroMovement": 0.0,
            "bob_macroCoupling": 0.0,
            "bob_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "oblong", "hurricane", "beating"],
        "Maximum detune creates violent beating. Filter near self-oscillation. LFO slamming at high rate. Not rhythm — interference: two weather systems occupying the same space."
    ),
    (
        "Optic Phosphor Storm",
        "Optic",
        dict(brightness=0.98, warmth=0.05, movement=0.92, density=0.85, space=0.52, aggression=0.90),
        {
            "optic_reactivity": 0.92,
            "optic_inputGain": 1.0,
            "optic_autoPulse": 1,
            "optic_pulseRate": 0.88,
            "optic_pulseShape": 0.72,
            "optic_pulseSwing": 0.42,
            "optic_pulseEvolve": 0.88,
            "optic_pulseSubdiv": 0.85,
            "optic_pulseAccent": 0.92,
            "optic_modDepth": 0.92,
            "optic_modMixPulse": 0.88,
            "optic_modMixSpec": 0.82,
            "optic_vizMode": 4,
            "optic_vizFeedback": 0.92,
            "optic_vizSpeed": 0.92,
            "optic_vizIntensity": 0.95
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "optic", "phosphor", "white-out"],
        "AutoPulse at maximum rate with near-maximum swing and accent. Feedback near saturation. Brightness approaching white-out. A phosphor storm — visual processing as atmospheric event."
    ),
    (
        "Outwit Squall",
        "Outwit",
        dict(brightness=0.78, warmth=0.18, movement=0.92, density=0.88, space=0.55, aggression=0.82),
        {
            "owit_rule": 150,
            "owit_armBalance": 0.25,
            "owit_mutationRate": 0.88,
            "owit_armSpread": 0.92,
            "owit_sync": 0.72,
            "owit_feedbackAmt": 0.82,
            "owit_chaos": 0.88,
            "owit_density": 0.88,
            "owit_ampAttack": 0.08,
            "owit_ampDecay": 0.4,
            "owit_ampSustain": 0.52,
            "owit_ampRelease": 2.5,
            "owit_filterCutoff": 0.88,
            "owit_filterRes": 0.78,
            "owit_lfoRate": 0.72,
            "owit_lfoDepth": 0.85,
            "owit_macroCharacter": 0.0,
            "owit_macroChaos": 0.0,
            "owit_macroCoupling": 0.0,
            "owit_macroSpace": 0.0
        },
        ["CHARACTER", "CHAOS", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "outwit", "squall", "ca-storm"],
        "Rule 150 — additive CA with maximum mutation and feedback. Arms desynchronized at low balance. Density and chaos both near maximum. The octopus at the eye of the storm."
    ),
    (
        "Oblique Tempest",
        "Oblique",
        dict(brightness=0.82, warmth=0.12, movement=0.88, density=0.88, space=0.58, aggression=0.86),
        {
            "oblq_oscWave": 2,
            "oblq_oscFold": 0.88,
            "oblq_oscDetune": 48.0,
            "oblq_level": 0.92,
            "oblq_glide": 0.12,
            "oblq_percClick": 0.28,
            "oblq_percDecay": 0.18,
            "oblq_bounceRate": 180.0,
            "oblq_bounceGravity": 0.92,
            "oblq_bounceDamp": 0.45,
            "oblq_bounceCnt": 16.0,
            "oblq_bounceSwing": 0.48,
            "oblq_clickTone": 3500.0,
            "oblq_filterCut": 7000.0,
            "oblq_filterRes": 0.88,
            "oblq_attack": 0.05,
            "oblq_decay": 0.3,
            "oblq_sustain": 0.48,
            "oblq_release": 2.5,
            "oblq_prismDelay": 95.0,
            "oblq_prismSpread": 0.98,
            "oblq_prismColor": 0.95,
            "oblq_prismWidth": 0.98,
            "oblq_prismFeedback": 0.95,
            "oblq_prismMix": 0.92,
            "oblq_prismDamp": 0.12,
            "oblq_phaserRate": 0.88,
            "oblq_phaserDepth": 0.98,
            "oblq_phaserFeedback": 0.92,
            "oblq_phaserMix": 0.88
        },
        ["SPACE", "FOLD", "PRISM DEPTH", "FILTER"],
        ["atmosphere", "storm", "oblique", "tempest", "cascade"],
        "Maximum fold, maximum detune, sixteen bounces with minimal damping. Prism feedback near saturation. The prism bounce is now a tempest: energy reflecting endlessly off storm walls."
    ),
    (
        "Orca Breach",
        "Orca",
        dict(brightness=0.85, warmth=0.12, movement=0.92, density=0.88, space=0.48, aggression=0.88),
        {
            "orca_filterCutoff": 0.95,
            "orca_filterReso": 0.92,
            "orca_drive": 0.88,
            "orca_lfoRate": 0.85,
            "orca_lfoDepth": 0.95,
            "orca_echoDelay": 0.28,
            "orca_echoFeedback": 0.88,
            "orca_reverbMix": 0.55,
            "orca_ampAttack": 0.03,
            "orca_ampDecay": 0.3,
            "orca_ampSustain": 0.45,
            "orca_ampRelease": 2.5,
            "orca_macroCharacter": 0.0,
            "orca_macroMovement": 0.0,
            "orca_macroCoupling": 0.0,
            "orca_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "orca", "breach", "impact"],
        "Filter self-oscillating, drive at maximum, LFO scanning at predator speed. Echo feedback building into sustained tone. A 7-tonne breach: the ocean erupts and the air fills with water."
    ),
    (
        "Origami Torn",
        "Origami",
        dict(brightness=0.75, warmth=0.12, movement=0.85, density=0.92, space=0.52, aggression=0.80),
        {
            "origami_foldPoint": 0.12,
            "origami_foldAmt": 0.95,
            "origami_layers": 9,
            "origami_symmetry": 0.03,
            "origami_filterCutoff": 0.88,
            "origami_filterReso": 0.72,
            "origami_oscPitch": 0.0,
            "origami_ampAttack": 0.1,
            "origami_ampDecay": 0.4,
            "origami_ampSustain": 0.52,
            "origami_ampRelease": 2.8
        },
        ["CHARACTER", "FOLD", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "origami", "torn", "odd-harmonic-storm"],
        "Nine layers at near-zero symmetry, fold point at 0.12 — deep wave surgery. Near-maximum fold amount. The atmosphere of paper in wind: harmonic content unraveling."
    ),
    (
        "Orbital Debris Storm",
        "Orbital",
        dict(brightness=0.88, warmth=0.12, movement=0.92, density=0.92, space=0.55, aggression=0.85),
        {
            "orb_brightness": 0.92,
            "orb_groupEnvRate": 0.88,
            "orb_groupEnvDepth": 0.95,
            "orb_oscCount": 16,
            "orb_spread": 0.95,
            "orb_detune": 0.78,
            "orb_filterCutoff": 0.92,
            "orb_filterReso": 0.68,
            "orb_ampAttack": 0.05,
            "orb_ampDecay": 0.35,
            "orb_ampSustain": 0.45,
            "orb_ampRelease": 2.5
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "orbital", "debris", "field"],
        "Sixteen oscillators at maximum detune, group envelope rate near maximum. Not a chord ring — a debris field in rapid orbit. The atmosphere of breakdown: ordered system approaching noise."
    ),
    (
        "Overworld Cascade Collapse",
        "Overworld",
        dict(brightness=0.92, warmth=0.08, movement=0.95, density=0.92, space=0.45, aggression=0.92),
        {
            "ow_eraBalance": 0.98,
            "ow_voiceCount": 16,
            "ow_spread": 0.95,
            "ow_detune": 0.88,
            "ow_filterCutoff": 0.98,
            "ow_filterReso": 0.88,
            "ow_glitchRate": 0.92,
            "ow_glitchDepth": 0.95,
            "ow_glitchType": 5,
            "ow_ampAttack": 0.03,
            "ow_ampDecay": 0.25,
            "ow_ampSustain": 0.38,
            "ow_ampRelease": 2.0,
            "ow_reverbMix": 0.45,
            "ow_macroCharacter": 0.0,
            "ow_macroMovement": 0.0,
            "ow_macroCoupling": 0.0,
            "ow_macroSpace": 0.0
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "overworld", "cascade", "collapse", "maximum"],
        "Maximum Genesis ERA, sixteen voices at maximum detune, glitch at near-maximum. The digital atmosphere in catastrophic failure mode — still coherent enough to be atmospheric, not noise."
    ),
    (
        "Ouroboros Bifurcation",
        "Ouroboros",
        dict(brightness=0.78, warmth=0.15, movement=0.95, density=0.85, space=0.58, aggression=0.78),
        {
            "ouro_topology": 2,
            "ouro_rate": 1320.0,
            "ouro_chaosIndex": 0.92,
            "ouro_leash": 0.08,
            "ouro_theta": 0.98,
            "ouro_phi": 0.05,
            "ouro_damping": 0.05,
            "ouro_injection": 0.62
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "ouroboros", "bifurcation", "chaos"],
        "Near-maximum chaos, near-zero leash and damping. Rate at 1320Hz — the trajectory is making audible choices. Injection at 0.62 adds forcing. Period-doubling at the edge of full chaos."
    ),
    (
        "Outwit Deep Storm",
        "Outwit",
        dict(brightness=0.82, warmth=0.12, movement=0.95, density=0.92, space=0.52, aggression=0.90),
        {
            "owit_rule": 90,
            "owit_armBalance": 0.15,
            "owit_mutationRate": 0.95,
            "owit_armSpread": 0.98,
            "owit_sync": 0.88,
            "owit_feedbackAmt": 0.92,
            "owit_chaos": 0.95,
            "owit_density": 0.95,
            "owit_ampAttack": 0.03,
            "owit_ampDecay": 0.25,
            "owit_ampSustain": 0.45,
            "owit_ampRelease": 2.0,
            "owit_filterCutoff": 0.95,
            "owit_filterRes": 0.88,
            "owit_lfoRate": 0.88,
            "owit_lfoDepth": 0.92,
            "owit_macroCharacter": 0.0,
            "owit_macroChaos": 0.0,
            "owit_macroCoupling": 0.0,
            "owit_macroSpace": 0.0
        },
        ["CHARACTER", "CHAOS", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "outwit", "deep-storm", "rule-90"],
        "Rule 90 — fractal/Sierpinski pattern. Maximum mutation and feedback. All eight arms firing at near-maximum chaos. The fractal storm: self-similar at every scale."
    ),
    (
        "Optic Coronal Mass",
        "Optic",
        dict(brightness=0.95, warmth=0.08, movement=0.95, density=0.88, space=0.58, aggression=0.75),
        {
            "optic_reactivity": 0.95,
            "optic_inputGain": 1.0,
            "optic_autoPulse": 1,
            "optic_pulseRate": 0.92,
            "optic_pulseShape": 0.88,
            "optic_pulseSwing": 0.55,
            "optic_pulseEvolve": 0.95,
            "optic_pulseSubdiv": 0.92,
            "optic_pulseAccent": 0.98,
            "optic_modDepth": 0.95,
            "optic_modMixPulse": 0.92,
            "optic_modMixSpec": 0.88,
            "optic_vizMode": 3,
            "optic_vizFeedback": 0.95,
            "optic_vizSpeed": 0.98,
            "optic_vizIntensity": 0.88
        },
        ["CHARACTER", "MOVEMENT", "COUPLING", "SPACE"],
        ["atmosphere", "storm", "optic", "coronal-mass", "solar"],
        "Near-maximum everything. The pulse is no longer a pulse — it is a continuous charged ejection. The atmosphere of a coronal mass event: light as storm."
    ),
    (
        "Onset Typhoon",
        "Onset",
        dict(brightness=0.72, warmth=0.15, movement=0.98, density=0.95, space=0.45, aggression=0.92),
        {
            "perc_v1_blend": 0.95,
            "perc_v1_algoMode": 3,
            "perc_v1_pitch": 0,
            "perc_v1_decay": 0.28,
            "perc_v1_tone": 0.92,
            "perc_v1_snap": 0.88,
            "perc_v1_body": 0.82,
            "perc_v1_character": 0.85,
            "perc_v1_level": 0.92,
            "perc_v1_pan": 0.0,
            "perc_v1_envShape": 2,
            "perc_v2_blend": 0.88,
            "perc_v2_algoMode": 2,
            "perc_v2_pitch": 0,
            "perc_v2_decay": 0.18,
            "perc_v2_tone": 0.88,
            "perc_v2_snap": 0.85,
            "perc_v2_body": 0.78,
            "perc_v2_character": 0.82,
            "perc_v2_level": 0.88,
            "perc_v2_pan": 0.45,
            "perc_v2_envShape": 2,
            "perc_v3_blend": 0.92,
            "perc_v3_algoMode": 1,
            "perc_v3_pitch": 0,
            "perc_v3_decay": 0.38,
            "perc_v3_tone": 0.92,
            "perc_v3_snap": 0.88,
            "perc_v3_body": 0.85,
            "perc_v3_character": 0.88,
            "perc_v3_level": 0.92,
            "perc_v3_pan": -0.45,
            "perc_v3_envShape": 2,
            "perc_v4_blend": 0.85,
            "perc_v4_algoMode": 0,
            "perc_v4_pitch": 0,
            "perc_v4_decay": 0.22,
            "perc_v4_tone": 0.85,
            "perc_v4_snap": 0.82,
            "perc_v4_body": 0.75,
            "perc_v4_character": 0.78,
            "perc_v4_level": 0.85,
            "perc_v4_pan": 0.28,
            "perc_v4_envShape": 1,
            "perc_v5_blend": 0.92,
            "perc_v5_algoMode": 3,
            "perc_v5_pitch": 0,
            "perc_v5_decay": 0.45,
            "perc_v5_tone": 0.92,
            "perc_v5_snap": 0.88,
            "perc_v5_body": 0.82,
            "perc_v5_character": 0.85,
            "perc_v5_level": 0.92,
            "perc_v5_pan": -0.28,
            "perc_v5_envShape": 2,
            "perc_v6_blend": 0.82,
            "perc_v6_algoMode": 2,
            "perc_v6_pitch": 0,
            "perc_v6_decay": 0.32,
            "perc_v6_tone": 0.85,
            "perc_v6_snap": 0.82,
            "perc_v6_body": 0.72,
            "perc_v6_character": 0.75,
            "perc_v6_level": 0.85,
            "perc_v6_pan": 0.12,
            "perc_v6_envShape": 1,
            "perc_level": 0.95,
            "perc_drive": 0.92,
            "perc_masterTone": 0.88,
            "perc_macro_machine": 0.98,
            "perc_macro_punch": 0.95,
            "perc_macro_space": 0.65,
            "perc_macro_mutate": 0.95,
            "perc_xvc_kick_to_snare_filter": 0.88,
            "perc_xvc_snare_to_hat_decay": 0.82,
            "perc_xvc_kick_to_tom_pitch": 0.72,
            "perc_xvc_snare_to_perc_blend": 0.75,
            "perc_xvc_hat_choke": 0.22,
            "perc_xvc_global_amount": 0.95,
            "perc_char_grit": 0.92,
            "perc_char_warmth": 0.08,
            "perc_fx_delay_time": 0.82,
            "perc_fx_delay_feedback": 0.88,
            "perc_fx_delay_mix": 0.75,
            "perc_fx_reverb_size": 0.92,
            "perc_fx_reverb_decay": 0.88,
            "perc_fx_reverb_mix": 0.78,
            "perc_fx_lofi_bits": 6.0,
            "perc_fx_lofi_mix": 0.72
        },
        ["MACHINE", "PUNCH", "SPACE", "MUTATE"],
        ["atmosphere", "storm", "onset", "typhoon", "maximum-aggression"],
        "Six voices at near-maximum drive and character. XVC global at 0.95 — all voices bleeding. 6-bit lo-fi at 0.72 transforms the output into textural storm rather than drum. Onset as typhoon."
    ),
]

# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------

def build_preset(name, engine, dna, parameters, macro_labels, tags, description, tier_tag):
    return {
        "schema_version": 1,
        "name": name,
        "mood": "Atmosphere",
        "engines": [engine],
        "author": "XO_OX Designs — Atmosphere Aggression Expander 2026-03-16",
        "version": "1.0.0",
        "description": description,
        "tags": tags,
        "macroLabels": macro_labels,
        "couplingIntensity": "None",
        "tempo": None,
        "created": "2026-03-16",
        "legacy": {"sourceInstrument": None, "sourceCategory": None, "sourcePresetName": None},
        "parameters": {engine: parameters},
        "coupling": {"pairs": []},
        "sequencer": None,
        "dna": dna
    }


def filename_for(name):
    safe = name.replace(" ", "_").replace("/", "-").replace("'", "")
    return f"{safe}.xometa"


def main():
    os.makedirs(PRESET_DIR, exist_ok=True)

    all_tiers = [
        ("calm-atmosphere", CALM_ATMOSPHERE),
        ("tense-atmosphere", TENSE_ATMOSPHERE),
        ("charged-atmosphere", CHARGED_ATMOSPHERE),
        ("storm-atmosphere", STORM_ATMOSPHERE),
    ]

    written = 0
    skipped = 0
    total = 0

    for tier_tag, presets in all_tiers:
        for (name, engine, dna, parameters, macro_labels, tags, description) in presets:
            total += 1
            fname = filename_for(name)
            fpath = os.path.join(PRESET_DIR, fname)
            if os.path.exists(fpath):
                print(f"  SKIP  {fname}")
                skipped += 1
                continue
            preset = build_preset(name, engine, dna, parameters, macro_labels, tags, description, tier_tag)
            with open(fpath, "w") as f:
                json.dump(preset, f, indent=2)
            print(f"  WRITE {fname}  [{tier_tag}]  aggression={dna['aggression']:.2f}")
            written += 1

    print()
    print(f"Done. {written} written, {skipped} skipped, {total} total.")
    print()
    print("Aggression distribution check:")
    for tier_tag, presets in all_tiers:
        aggressions = [p[2]['aggression'] for p in presets]
        print(f"  {tier_tag:25s}  n={len(aggressions)}  "
              f"min={min(aggressions):.2f}  max={max(aggressions):.2f}  "
              f"mean={sum(aggressions)/len(aggressions):.2f}")


if __name__ == "__main__":
    main()
