"""
xpn_pack_ci_config_generator.py

Generates a GitHub Actions CI configuration file for automated .xpn pack
quality gating — producing a .github/workflows/xpn_qa.yml ready to drop
into any XO_OX pack repository.

CLI usage:
    python xpn_pack_ci_config_generator.py [--output .github/workflows/xpn_qa.yml]
                                            [--tier signal|form|doctrine]
                                            [--python-version 3.11]

Importable:
    from xpn_pack_ci_config_generator import generate_ci_config
"""

import argparse
import os
import sys

# ---------------------------------------------------------------------------
# Tier thresholds
# ---------------------------------------------------------------------------

TIER_THRESHOLDS = {
    "signal": 70,
    "form": 80,
    "doctrine": 90,
}

TIER_DESCRIPTIONS = {
    "signal": "signal (70) — entry-level packs, basic integrity required",
    "form": "form (80) — standard XO_OX quality bar",
    "doctrine": "doctrine (90) — flagship packs, full doctrine compliance",
}

# ---------------------------------------------------------------------------
# YAML template
# ---------------------------------------------------------------------------

WORKFLOW_TEMPLATE = """\
# XPN Pack QA — generated by xpn_pack_ci_config_generator.py
# Tier: {tier} | Score threshold: {threshold} | Python: {python_version}
#
# Drop this file at .github/workflows/xpn_qa.yml in any XO_OX pack repo.
# Tools required in the repo:
#   Tools/xpn_pack_integrity_check.py
#   Tools/xpn_expansion_json_lint.py
#   Tools/xpn_pack_score.py

name: XPN Pack QA

on:
  push:
    branches:
      - 'packs/**'
  pull_request:
    paths:
      - '**/*.xpn'

jobs:
  # ------------------------------------------------------------------
  # discover — find all .xpn files and emit them as a JSON array
  # ------------------------------------------------------------------
  discover:
    name: Discover .xpn packs
    runs-on: ubuntu-latest
    outputs:
      packs: ${{{{ steps.find.outputs.packs }}}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find .xpn files
        id: find
        run: |
          PACKS=$(find . -name '*.xpn' -not -path './.git/*' \\
            | sort \\
            | jq -R -s -c 'split("\\n") | map(select(length > 0))')
          echo "packs=$PACKS" >> "$GITHUB_OUTPUT"
          echo "Discovered packs: $PACKS"

  # ------------------------------------------------------------------
  # qa — run integrity / lint / score for every pack in the matrix
  # ------------------------------------------------------------------
  qa:
    name: QA ${{{{ matrix.pack }}}}
    needs: discover
    runs-on: ubuntu-latest
    if: ${{{{ needs.discover.outputs.packs != '[]' }}}}

    strategy:
      fail-fast: false
      matrix:
        pack: ${{{{ fromJson(needs.discover.outputs.packs) }}}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: '{python_version}'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Most XO_OX tools are stdlib-only; install extras if needed
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Integrity check — ${{{{ matrix.pack }}}}
        run: |
          python Tools/xpn_pack_integrity_check.py "${{{{ matrix.pack }}}}" --strict

      - name: JSON lint — ${{{{ matrix.pack }}}}
        run: |
          python Tools/xpn_expansion_json_lint.py "${{{{ matrix.pack }}}}" --strict

      - name: Score check (threshold {threshold}) — ${{{{ matrix.pack }}}}
        id: score
        run: |
          python Tools/xpn_pack_score.py "${{{{ matrix.pack }}}}" --strict --threshold {threshold}

  # ------------------------------------------------------------------
  # summary — post a PR comment with scores and pass/fail per pack
  # ------------------------------------------------------------------
  summary:
    name: Post QA summary
    needs: [discover, qa]
    runs-on: ubuntu-latest
    # Always run so we post even on partial failure
    if: always() && github.event_name == 'pull_request'

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: '{python_version}'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Collect scores
        id: collect
        run: |
          PACKS='${{{{ needs.discover.outputs.packs }}}}'
          THRESHOLD={threshold}
          TIER="{tier}"
          SUMMARY="## XPN Pack QA Summary\\n"
          SUMMARY+="**Tier:** ${{TIER}} | **Score threshold:** ${{THRESHOLD}}\\n\\n"
          SUMMARY+="| Pack | Integrity | Lint | Score | Status |\\n"
          SUMMARY+="|------|-----------|------|-------|--------|\\n"
          OVERALL_PASS=true

          for PACK in $(echo "$PACKS" | jq -r '.[]'); do
            BASENAME=$(basename "$PACK")
            INT_STATUS="pass"
            LINT_STATUS="pass"
            SCORE_STATUS="pass"
            SCORE_VAL="—"

            # Run integrity check
            if ! python Tools/xpn_pack_integrity_check.py "$PACK" --strict 2>/dev/null; then
              INT_STATUS="FAIL"
              OVERALL_PASS=false
            fi

            # Run lint check
            if ! python Tools/xpn_expansion_json_lint.py "$PACK" --strict 2>/dev/null; then
              LINT_STATUS="FAIL"
              OVERALL_PASS=false
            fi

            # Run score check and capture value
            SCORE_OUTPUT=$(python Tools/xpn_pack_score.py "$PACK" --threshold ${{THRESHOLD}} 2>&1 || true)
            SCORE_VAL=$(echo "$SCORE_OUTPUT" | grep -oP 'score[:\\s]+\\K[0-9]+' | head -1 || echo "—")
            if ! python Tools/xpn_pack_score.py "$PACK" --strict --threshold ${{THRESHOLD}} 2>/dev/null; then
              SCORE_STATUS="FAIL"
              OVERALL_PASS=false
            fi

            ROW_STATUS="✅ pass"
            if [ "$INT_STATUS" = "FAIL" ] || [ "$LINT_STATUS" = "FAIL" ] || [ "$SCORE_STATUS" = "FAIL" ]; then
              ROW_STATUS="❌ fail"
            fi

            SUMMARY+="| \\`${{BASENAME}}\\` | ${{INT_STATUS}} | ${{LINT_STATUS}} | ${{SCORE_VAL}} | ${{ROW_STATUS}} |\\n"
          done

          if [ "$OVERALL_PASS" = true ]; then
            SUMMARY+="\\n**Result: All packs passed QA.** ✅"
          else
            SUMMARY+="\\n**Result: One or more packs failed QA.** ❌ Fix errors before merging."
          fi

          # Write to file so the comment step can read it cleanly
          printf "%b" "$SUMMARY" > qa_summary.md
          echo "overall_pass=$OVERALL_PASS" >> "$GITHUB_OUTPUT"

      - name: Find existing QA comment
        uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{{{ github.event.pull_request.number }}}}
          comment-author: 'github-actions[bot]'
          body-includes: 'XPN Pack QA Summary'

      - name: Create or update PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{{{ steps.find_comment.outputs.comment-id }}}}
          issue-number: ${{{{ github.event.pull_request.number }}}}
          body-file: qa_summary.md
          edit-mode: replace
"""

# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def generate_ci_config(tier: str = "form", python_version: str = "3.11") -> str:
    """Return the rendered GitHub Actions workflow YAML as a string."""
    if tier not in TIER_THRESHOLDS:
        raise ValueError(
            f"Unknown tier '{tier}'. Valid tiers: {', '.join(TIER_THRESHOLDS)}"
        )
    threshold = TIER_THRESHOLDS[tier]
    return WORKFLOW_TEMPLATE.format(
        tier=tier,
        threshold=threshold,
        python_version=python_version,
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a GitHub Actions CI configuration for XPN pack quality gating. "
            "Outputs a .github/workflows/xpn_qa.yml ready to drop into any XO_OX pack repo."
        )
    )
    parser.add_argument(
        "--output",
        metavar="PATH",
        default=None,
        help=(
            "Path to write the generated YAML. "
            "Defaults to stdout. "
            "Example: .github/workflows/xpn_qa.yml"
        ),
    )
    parser.add_argument(
        "--tier",
        choices=list(TIER_THRESHOLDS.keys()),
        default="form",
        help=(
            "Pack quality tier — sets the xpn_pack_score threshold. "
            + " | ".join(f"{k}: {v}" for k, v in TIER_THRESHOLDS.items())
            + " (default: form)"
        ),
    )
    parser.add_argument(
        "--python-version",
        default="3.11",
        metavar="VERSION",
        help="Python version for the workflow runner (default: 3.11).",
    )

    args = parser.parse_args()

    try:
        yaml_content = generate_ci_config(
            tier=args.tier,
            python_version=args.python_version,
        )
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.output:
        output_path = os.path.abspath(args.output)
        parent_dir = os.path.dirname(output_path)
        if parent_dir and not os.path.isdir(parent_dir):
            os.makedirs(parent_dir, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write(yaml_content)
        print(f"Written: {output_path}")
        print(f"Tier:    {args.tier} (score threshold: {TIER_THRESHOLDS[args.tier]})")
        print(f"Python:  {args.python_version}")
    else:
        sys.stdout.write(yaml_content)

    return 0


if __name__ == "__main__":
    sys.exit(main())
